// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nvidiaaicr

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi-nvidia-aicr/sdk/go/nvidiaaicr/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ClusterStack struct {
	pulumi.ResourceState

	ComponentCount     pulumi.IntOutput         `pulumi:"componentCount"`
	DeployedComponents pulumi.StringArrayOutput `pulumi:"deployedComponents"`
	RecipeName         pulumi.StringOutput      `pulumi:"recipeName"`
	RecipeVersion      pulumi.StringOutput      `pulumi:"recipeVersion"`
}

// NewClusterStack registers a new resource with the given unique name, arguments, and options.
func NewClusterStack(ctx *pulumi.Context,
	name string, args *ClusterStackArgs, opts ...pulumi.ResourceOption) (*ClusterStack, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ClusterStack
	err := ctx.RegisterRemoteComponentResource("nvidia-aicr:index:ClusterStack", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type clusterStackArgs struct {
	Accelerator        string                       `pulumi:"accelerator"`
	ComponentOverrides map[string]ComponentOverride `pulumi:"componentOverrides"`
	Context            *string                      `pulumi:"context"`
	Intent             string                       `pulumi:"intent"`
	Kubeconfig         *string                      `pulumi:"kubeconfig"`
	KubeconfigPath     *string                      `pulumi:"kubeconfigPath"`
	Os                 *string                      `pulumi:"os"`
	Platform           *string                      `pulumi:"platform"`
	Service            string                       `pulumi:"service"`
	SkipAwait          *bool                        `pulumi:"skipAwait"`
	SkipComponents     []string                     `pulumi:"skipComponents"`
}

// The set of arguments for constructing a ClusterStack resource.
type ClusterStackArgs struct {
	Accelerator        string
	ComponentOverrides ComponentOverrideMapInput
	Context            *string
	Intent             string
	Kubeconfig         pulumi.StringPtrInput
	KubeconfigPath     *string
	Os                 *string
	Platform           *string
	Service            string
	SkipAwait          *bool
	SkipComponents     pulumi.StringArrayInput
}

func (ClusterStackArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterStackArgs)(nil)).Elem()
}

type ClusterStackInput interface {
	pulumi.Input

	ToClusterStackOutput() ClusterStackOutput
	ToClusterStackOutputWithContext(ctx context.Context) ClusterStackOutput
}

func (*ClusterStack) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterStack)(nil)).Elem()
}

func (i *ClusterStack) ToClusterStackOutput() ClusterStackOutput {
	return i.ToClusterStackOutputWithContext(context.Background())
}

func (i *ClusterStack) ToClusterStackOutputWithContext(ctx context.Context) ClusterStackOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterStackOutput)
}

// ClusterStackArrayInput is an input type that accepts ClusterStackArray and ClusterStackArrayOutput values.
// You can construct a concrete instance of `ClusterStackArrayInput` via:
//
//	ClusterStackArray{ ClusterStackArgs{...} }
type ClusterStackArrayInput interface {
	pulumi.Input

	ToClusterStackArrayOutput() ClusterStackArrayOutput
	ToClusterStackArrayOutputWithContext(context.Context) ClusterStackArrayOutput
}

type ClusterStackArray []ClusterStackInput

func (ClusterStackArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClusterStack)(nil)).Elem()
}

func (i ClusterStackArray) ToClusterStackArrayOutput() ClusterStackArrayOutput {
	return i.ToClusterStackArrayOutputWithContext(context.Background())
}

func (i ClusterStackArray) ToClusterStackArrayOutputWithContext(ctx context.Context) ClusterStackArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterStackArrayOutput)
}

// ClusterStackMapInput is an input type that accepts ClusterStackMap and ClusterStackMapOutput values.
// You can construct a concrete instance of `ClusterStackMapInput` via:
//
//	ClusterStackMap{ "key": ClusterStackArgs{...} }
type ClusterStackMapInput interface {
	pulumi.Input

	ToClusterStackMapOutput() ClusterStackMapOutput
	ToClusterStackMapOutputWithContext(context.Context) ClusterStackMapOutput
}

type ClusterStackMap map[string]ClusterStackInput

func (ClusterStackMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClusterStack)(nil)).Elem()
}

func (i ClusterStackMap) ToClusterStackMapOutput() ClusterStackMapOutput {
	return i.ToClusterStackMapOutputWithContext(context.Background())
}

func (i ClusterStackMap) ToClusterStackMapOutputWithContext(ctx context.Context) ClusterStackMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterStackMapOutput)
}

type ClusterStackOutput struct{ *pulumi.OutputState }

func (ClusterStackOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ClusterStack)(nil)).Elem()
}

func (o ClusterStackOutput) ToClusterStackOutput() ClusterStackOutput {
	return o
}

func (o ClusterStackOutput) ToClusterStackOutputWithContext(ctx context.Context) ClusterStackOutput {
	return o
}

func (o ClusterStackOutput) ComponentCount() pulumi.IntOutput {
	return o.ApplyT(func(v *ClusterStack) pulumi.IntOutput { return v.ComponentCount }).(pulumi.IntOutput)
}

func (o ClusterStackOutput) DeployedComponents() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ClusterStack) pulumi.StringArrayOutput { return v.DeployedComponents }).(pulumi.StringArrayOutput)
}

func (o ClusterStackOutput) RecipeName() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterStack) pulumi.StringOutput { return v.RecipeName }).(pulumi.StringOutput)
}

func (o ClusterStackOutput) RecipeVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ClusterStack) pulumi.StringOutput { return v.RecipeVersion }).(pulumi.StringOutput)
}

type ClusterStackArrayOutput struct{ *pulumi.OutputState }

func (ClusterStackArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ClusterStack)(nil)).Elem()
}

func (o ClusterStackArrayOutput) ToClusterStackArrayOutput() ClusterStackArrayOutput {
	return o
}

func (o ClusterStackArrayOutput) ToClusterStackArrayOutputWithContext(ctx context.Context) ClusterStackArrayOutput {
	return o
}

func (o ClusterStackArrayOutput) Index(i pulumi.IntInput) ClusterStackOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ClusterStack {
		return vs[0].([]*ClusterStack)[vs[1].(int)]
	}).(ClusterStackOutput)
}

type ClusterStackMapOutput struct{ *pulumi.OutputState }

func (ClusterStackMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ClusterStack)(nil)).Elem()
}

func (o ClusterStackMapOutput) ToClusterStackMapOutput() ClusterStackMapOutput {
	return o
}

func (o ClusterStackMapOutput) ToClusterStackMapOutputWithContext(ctx context.Context) ClusterStackMapOutput {
	return o
}

func (o ClusterStackMapOutput) MapIndex(k pulumi.StringInput) ClusterStackOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ClusterStack {
		return vs[0].(map[string]*ClusterStack)[vs[1].(string)]
	}).(ClusterStackOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterStackInput)(nil)).Elem(), &ClusterStack{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterStackArrayInput)(nil)).Elem(), ClusterStackArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ClusterStackMapInput)(nil)).Elem(), ClusterStackMap{})
	pulumi.RegisterOutputType(ClusterStackOutput{})
	pulumi.RegisterOutputType(ClusterStackArrayOutput{})
	pulumi.RegisterOutputType(ClusterStackMapOutput{})
}
