// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nvidiaaicr

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-nvidia-aicr/sdk/go/nvidiaaicr/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ComponentOverride struct {
	Namespace *string                `pulumi:"namespace"`
	Values    map[string]interface{} `pulumi:"values"`
	Version   *string                `pulumi:"version"`
}

// ComponentOverrideInput is an input type that accepts ComponentOverrideArgs and ComponentOverrideOutput values.
// You can construct a concrete instance of `ComponentOverrideInput` via:
//
//	ComponentOverrideArgs{...}
type ComponentOverrideInput interface {
	pulumi.Input

	ToComponentOverrideOutput() ComponentOverrideOutput
	ToComponentOverrideOutputWithContext(context.Context) ComponentOverrideOutput
}

type ComponentOverrideArgs struct {
	Namespace pulumi.StringPtrInput `pulumi:"namespace"`
	Values    pulumi.MapInput       `pulumi:"values"`
	Version   pulumi.StringPtrInput `pulumi:"version"`
}

func (ComponentOverrideArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ComponentOverride)(nil)).Elem()
}

func (i ComponentOverrideArgs) ToComponentOverrideOutput() ComponentOverrideOutput {
	return i.ToComponentOverrideOutputWithContext(context.Background())
}

func (i ComponentOverrideArgs) ToComponentOverrideOutputWithContext(ctx context.Context) ComponentOverrideOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComponentOverrideOutput)
}

// ComponentOverrideMapInput is an input type that accepts ComponentOverrideMap and ComponentOverrideMapOutput values.
// You can construct a concrete instance of `ComponentOverrideMapInput` via:
//
//	ComponentOverrideMap{ "key": ComponentOverrideArgs{...} }
type ComponentOverrideMapInput interface {
	pulumi.Input

	ToComponentOverrideMapOutput() ComponentOverrideMapOutput
	ToComponentOverrideMapOutputWithContext(context.Context) ComponentOverrideMapOutput
}

type ComponentOverrideMap map[string]ComponentOverrideInput

func (ComponentOverrideMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ComponentOverride)(nil)).Elem()
}

func (i ComponentOverrideMap) ToComponentOverrideMapOutput() ComponentOverrideMapOutput {
	return i.ToComponentOverrideMapOutputWithContext(context.Background())
}

func (i ComponentOverrideMap) ToComponentOverrideMapOutputWithContext(ctx context.Context) ComponentOverrideMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ComponentOverrideMapOutput)
}

type ComponentOverrideOutput struct{ *pulumi.OutputState }

func (ComponentOverrideOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ComponentOverride)(nil)).Elem()
}

func (o ComponentOverrideOutput) ToComponentOverrideOutput() ComponentOverrideOutput {
	return o
}

func (o ComponentOverrideOutput) ToComponentOverrideOutputWithContext(ctx context.Context) ComponentOverrideOutput {
	return o
}

func (o ComponentOverrideOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ComponentOverride) *string { return v.Namespace }).(pulumi.StringPtrOutput)
}

func (o ComponentOverrideOutput) Values() pulumi.MapOutput {
	return o.ApplyT(func(v ComponentOverride) map[string]interface{} { return v.Values }).(pulumi.MapOutput)
}

func (o ComponentOverrideOutput) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ComponentOverride) *string { return v.Version }).(pulumi.StringPtrOutput)
}

type ComponentOverrideMapOutput struct{ *pulumi.OutputState }

func (ComponentOverrideMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]ComponentOverride)(nil)).Elem()
}

func (o ComponentOverrideMapOutput) ToComponentOverrideMapOutput() ComponentOverrideMapOutput {
	return o
}

func (o ComponentOverrideMapOutput) ToComponentOverrideMapOutputWithContext(ctx context.Context) ComponentOverrideMapOutput {
	return o
}

func (o ComponentOverrideMapOutput) MapIndex(k pulumi.StringInput) ComponentOverrideOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) ComponentOverride {
		return vs[0].(map[string]ComponentOverride)[vs[1].(string)]
	}).(ComponentOverrideOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ComponentOverrideInput)(nil)).Elem(), ComponentOverrideArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*ComponentOverrideMapInput)(nil)).Elem(), ComponentOverrideMap{})
	pulumi.RegisterOutputType(ComponentOverrideOutput{})
	pulumi.RegisterOutputType(ComponentOverrideMapOutput{})
}
