// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package nvidiaaicr

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi-labs/pulumi-nvidia-aicr/sdk/go/nvidiaaicr/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Runs an AICR recipe's empirical validation (cluster snapshot +
// deployment/conformance/performance checks) against a live cluster and
// records structured per-check results in Pulumi state.
//
// The run happens at deploy time (never at preview). The validation harness
// deploys short-lived agent and validator Jobs plus per-run RBAC on the target
// cluster and cleans them up afterward; the validation namespace (default
// "aicr-validation") is created on first run and deliberately persists.
//
// Privilege level: the snapshot-agent Job runs as a privileged container
// (bound to a read-only node-inspection ClusterRole), and validator Jobs run
// under a per-run cluster-admin ClusterRoleBinding — both removed after the
// run, including on cancellation. The kubeconfig identity needs RBAC to
// create/patch Namespaces, ClusterRoles, and ClusterRoleBindings.
//
// Any input change replaces the resource, which re-runs validation (delete is
// a no-op). With `strict: true`, a failed run fails the update while persisting
// full results, and validation re-runs on every subsequent `pulumi up` until it
// passes — use `dependsOn` to gate downstream resources on it.
type ValidationRun struct {
	pulumi.CustomResourceState

	// When the run completed, RFC 3339.
	CompletedAt pulumi.StringOutput `pulumi:"completedAt"`
	// Kubeconfig context to select. Defaults to the kubeconfig's current-context.
	Context pulumi.StringPtrOutput `pulumi:"context"`
	// Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
	// the object inline.
	Criteria RecipeCriteriaOutput `pulumi:"criteria"`
	// The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
	CtrfReport pulumi.StringPtrOutput `pulumi:"ctrfReport"`
	// Number of checks that failed.
	Failed pulumi.IntOutput `pulumi:"failed"`
	// Names of image pull Secrets (in the validation namespace) for the
	// validation pods.
	ImagePullSecrets pulumi.StringArrayOutput `pulumi:"imagePullSecrets"`
	// Registry override for the snapshot-agent and validator images (air-gapped
	// mirrors). Unset keeps the default registry (ghcr.io).
	ImageRegistry pulumi.StringPtrOutput `pulumi:"imageRegistry"`
	// If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
	// Default: false (state-size control; per-check results are always in
	// `phaseResults`).
	IncludeCtrfReport pulumi.BoolPtrOutput `pulumi:"includeCtrfReport"`
	// Kubeconfig contents for the target cluster. Mutually exclusive with
	// `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
	// var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
	// duration of the run and removed afterward.
	Kubeconfig pulumi.StringPtrOutput `pulumi:"kubeconfig"`
	// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
	KubeconfigPath pulumi.StringPtrOutput `pulumi:"kubeconfigPath"`
	// Namespace for the validation harness — use a dedicated one: it hosts the
	// privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
	// on first run and deliberately never deletes it. Must be a valid DNS-1123
	// label and not a "kube-" system namespace. Default: "aicr-validation".
	Namespace pulumi.StringPtrOutput `pulumi:"namespace"`
	// Node selector applied to the validation workload pods. Use when GPU nodes
	// carry non-standard labels.
	NodeSelector pulumi.StringMapOutput `pulumi:"nodeSelector"`
	// Number of checks with an inconclusive outcome (crash, OOM, timeout;
	// includes CTRF "pending").
	Other pulumi.IntOutput `pulumi:"other"`
	// Number of checks that passed.
	Passed pulumi.IntOutput `pulumi:"passed"`
	// Per-check results across all phases run.
	PhaseResults CheckResultArrayOutput `pulumi:"phaseResults"`
	// Validation phases to run: any of "deployment", "conformance",
	// "performance". Default: ["deployment", "conformance"] — "performance" is an
	// explicit opt-in (long-running and hardware-bound).
	Phases pulumi.StringArrayOutput `pulumi:"phases"`
	// The readiness pre-flight failure message; empty unless status is
	// "readiness-failed".
	ReadinessMessage pulumi.StringOutput `pulumi:"readinessMessage"`
	// Recipe-data version assertion (not a pin). When set, it must equal this
	// provider build's embedded AICR recipe-data version or Create fails before
	// any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
	// provider upgrade between deploy and validate.
	RecipeDataVersion pulumi.StringPtrOutput `pulumi:"recipeDataVersion"`
	// The resolved AICR recipe name that was validated.
	RecipeName pulumi.StringOutput `pulumi:"recipeName"`
	// The AICR recipe data version that was validated.
	RecipeVersion pulumi.StringOutput `pulumi:"recipeVersion"`
	// Whether the snapshot agent requires GPU nodes. Set false for
	// hardware-free clusters (kind). Default: true.
	RequireGpu pulumi.BoolPtrOutput `pulumi:"requireGpu"`
	// The run identifier labeling this run's cluster-side artifacts.
	RunId pulumi.StringOutput `pulumi:"runId"`
	// Number of checks that were skipped.
	Skipped pulumi.IntOutput `pulumi:"skipped"`
	// Rollup verdict: "passed", "failed", or "readiness-failed". Checks with
	// status "other" never flip the rollup (they are counted and listed).
	// Infrastructure errors have no status — they fail the update outright.
	Status pulumi.StringOutput `pulumi:"status"`
	// If true, a failed (or readiness-failed) validation fails the update while
	// still persisting the full results in state. The engine then re-runs
	// validation on every subsequent `pulumi up` until it passes. Default: false —
	// results are recorded and the update succeeds; read the `status` output.
	Strict pulumi.BoolPtrOutput `pulumi:"strict"`
	// Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
	TimeoutMinutes pulumi.IntPtrOutput `pulumi:"timeoutMinutes"`
	// Tolerations applied to the validation workload pods (e.g. NCCL benchmark
	// pods). Required in practice on tainted GPU node groups; when unset, the
	// validator's default tolerate-all is kept.
	Tolerations TolerationArrayOutput `pulumi:"tolerations"`
	// Arbitrary values; changing any of them replaces the resource and re-runs
	// validation (every input change does). Wire `triggers: [stack.deployedComponents]`
	// for re-validation cadence.
	Triggers pulumi.ArrayOutput `pulumi:"triggers"`
}

// NewValidationRun registers a new resource with the given unique name, arguments, and options.
func NewValidationRun(ctx *pulumi.Context,
	name string, args *ValidationRunArgs, opts ...pulumi.ResourceOption) (*ValidationRun, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Criteria == nil {
		return nil, errors.New("invalid value for required argument 'Criteria'")
	}
	if args.IncludeCtrfReport == nil {
		args.IncludeCtrfReport = pulumi.BoolPtr(false)
	}
	if args.Namespace == nil {
		args.Namespace = pulumi.StringPtr("aicr-validation")
	}
	if args.RequireGpu == nil {
		args.RequireGpu = pulumi.BoolPtr(true)
	}
	if args.Strict == nil {
		args.Strict = pulumi.BoolPtr(false)
	}
	if args.TimeoutMinutes == nil {
		args.TimeoutMinutes = pulumi.IntPtr(30)
	}
	if args.Kubeconfig != nil {
		args.Kubeconfig = pulumi.ToSecret(args.Kubeconfig).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"kubeconfig",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ValidationRun
	err := ctx.RegisterResource("nvidia-aicr:index:ValidationRun", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetValidationRun gets an existing ValidationRun resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetValidationRun(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ValidationRunState, opts ...pulumi.ResourceOption) (*ValidationRun, error) {
	var resource ValidationRun
	err := ctx.ReadResource("nvidia-aicr:index:ValidationRun", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ValidationRun resources.
type validationRunState struct {
}

type ValidationRunState struct {
}

func (ValidationRunState) ElementType() reflect.Type {
	return reflect.TypeOf((*validationRunState)(nil)).Elem()
}

type validationRunArgs struct {
	// Kubeconfig context to select. Defaults to the kubeconfig's current-context.
	Context *string `pulumi:"context"`
	// Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
	// the object inline.
	Criteria RecipeCriteria `pulumi:"criteria"`
	// Names of image pull Secrets (in the validation namespace) for the
	// validation pods.
	ImagePullSecrets []string `pulumi:"imagePullSecrets"`
	// Registry override for the snapshot-agent and validator images (air-gapped
	// mirrors). Unset keeps the default registry (ghcr.io).
	ImageRegistry *string `pulumi:"imageRegistry"`
	// If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
	// Default: false (state-size control; per-check results are always in
	// `phaseResults`).
	IncludeCtrfReport *bool `pulumi:"includeCtrfReport"`
	// Kubeconfig contents for the target cluster. Mutually exclusive with
	// `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
	// var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
	// duration of the run and removed afterward.
	Kubeconfig *string `pulumi:"kubeconfig"`
	// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
	KubeconfigPath *string `pulumi:"kubeconfigPath"`
	// Namespace for the validation harness — use a dedicated one: it hosts the
	// privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
	// on first run and deliberately never deletes it. Must be a valid DNS-1123
	// label and not a "kube-" system namespace. Default: "aicr-validation".
	Namespace *string `pulumi:"namespace"`
	// Node selector applied to the validation workload pods. Use when GPU nodes
	// carry non-standard labels.
	NodeSelector map[string]string `pulumi:"nodeSelector"`
	// Validation phases to run: any of "deployment", "conformance",
	// "performance". Default: ["deployment", "conformance"] — "performance" is an
	// explicit opt-in (long-running and hardware-bound).
	Phases []string `pulumi:"phases"`
	// Recipe-data version assertion (not a pin). When set, it must equal this
	// provider build's embedded AICR recipe-data version or Create fails before
	// any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
	// provider upgrade between deploy and validate.
	RecipeDataVersion *string `pulumi:"recipeDataVersion"`
	// Whether the snapshot agent requires GPU nodes. Set false for
	// hardware-free clusters (kind). Default: true.
	RequireGpu *bool `pulumi:"requireGpu"`
	// If true, a failed (or readiness-failed) validation fails the update while
	// still persisting the full results in state. The engine then re-runs
	// validation on every subsequent `pulumi up` until it passes. Default: false —
	// results are recorded and the update succeeds; read the `status` output.
	Strict *bool `pulumi:"strict"`
	// Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
	TimeoutMinutes *int `pulumi:"timeoutMinutes"`
	// Tolerations applied to the validation workload pods (e.g. NCCL benchmark
	// pods). Required in practice on tainted GPU node groups; when unset, the
	// validator's default tolerate-all is kept.
	Tolerations []Toleration `pulumi:"tolerations"`
	// Arbitrary values; changing any of them replaces the resource and re-runs
	// validation (every input change does). Wire `triggers: [stack.deployedComponents]`
	// for re-validation cadence.
	Triggers []interface{} `pulumi:"triggers"`
}

// The set of arguments for constructing a ValidationRun resource.
type ValidationRunArgs struct {
	// Kubeconfig context to select. Defaults to the kubeconfig's current-context.
	Context pulumi.StringPtrInput
	// Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
	// the object inline.
	Criteria RecipeCriteriaInput
	// Names of image pull Secrets (in the validation namespace) for the
	// validation pods.
	ImagePullSecrets pulumi.StringArrayInput
	// Registry override for the snapshot-agent and validator images (air-gapped
	// mirrors). Unset keeps the default registry (ghcr.io).
	ImageRegistry pulumi.StringPtrInput
	// If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
	// Default: false (state-size control; per-check results are always in
	// `phaseResults`).
	IncludeCtrfReport pulumi.BoolPtrInput
	// Kubeconfig contents for the target cluster. Mutually exclusive with
	// `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
	// var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
	// duration of the run and removed afterward.
	Kubeconfig pulumi.StringPtrInput
	// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
	KubeconfigPath pulumi.StringPtrInput
	// Namespace for the validation harness — use a dedicated one: it hosts the
	// privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
	// on first run and deliberately never deletes it. Must be a valid DNS-1123
	// label and not a "kube-" system namespace. Default: "aicr-validation".
	Namespace pulumi.StringPtrInput
	// Node selector applied to the validation workload pods. Use when GPU nodes
	// carry non-standard labels.
	NodeSelector pulumi.StringMapInput
	// Validation phases to run: any of "deployment", "conformance",
	// "performance". Default: ["deployment", "conformance"] — "performance" is an
	// explicit opt-in (long-running and hardware-bound).
	Phases pulumi.StringArrayInput
	// Recipe-data version assertion (not a pin). When set, it must equal this
	// provider build's embedded AICR recipe-data version or Create fails before
	// any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
	// provider upgrade between deploy and validate.
	RecipeDataVersion pulumi.StringPtrInput
	// Whether the snapshot agent requires GPU nodes. Set false for
	// hardware-free clusters (kind). Default: true.
	RequireGpu pulumi.BoolPtrInput
	// If true, a failed (or readiness-failed) validation fails the update while
	// still persisting the full results in state. The engine then re-runs
	// validation on every subsequent `pulumi up` until it passes. Default: false —
	// results are recorded and the update succeeds; read the `status` output.
	Strict pulumi.BoolPtrInput
	// Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
	TimeoutMinutes pulumi.IntPtrInput
	// Tolerations applied to the validation workload pods (e.g. NCCL benchmark
	// pods). Required in practice on tainted GPU node groups; when unset, the
	// validator's default tolerate-all is kept.
	Tolerations TolerationArrayInput
	// Arbitrary values; changing any of them replaces the resource and re-runs
	// validation (every input change does). Wire `triggers: [stack.deployedComponents]`
	// for re-validation cadence.
	Triggers pulumi.ArrayInput
}

func (ValidationRunArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*validationRunArgs)(nil)).Elem()
}

type ValidationRunInput interface {
	pulumi.Input

	ToValidationRunOutput() ValidationRunOutput
	ToValidationRunOutputWithContext(ctx context.Context) ValidationRunOutput
}

func (*ValidationRun) ElementType() reflect.Type {
	return reflect.TypeOf((**ValidationRun)(nil)).Elem()
}

func (i *ValidationRun) ToValidationRunOutput() ValidationRunOutput {
	return i.ToValidationRunOutputWithContext(context.Background())
}

func (i *ValidationRun) ToValidationRunOutputWithContext(ctx context.Context) ValidationRunOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ValidationRunOutput)
}

// ValidationRunArrayInput is an input type that accepts ValidationRunArray and ValidationRunArrayOutput values.
// You can construct a concrete instance of `ValidationRunArrayInput` via:
//
//	ValidationRunArray{ ValidationRunArgs{...} }
type ValidationRunArrayInput interface {
	pulumi.Input

	ToValidationRunArrayOutput() ValidationRunArrayOutput
	ToValidationRunArrayOutputWithContext(context.Context) ValidationRunArrayOutput
}

type ValidationRunArray []ValidationRunInput

func (ValidationRunArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ValidationRun)(nil)).Elem()
}

func (i ValidationRunArray) ToValidationRunArrayOutput() ValidationRunArrayOutput {
	return i.ToValidationRunArrayOutputWithContext(context.Background())
}

func (i ValidationRunArray) ToValidationRunArrayOutputWithContext(ctx context.Context) ValidationRunArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ValidationRunArrayOutput)
}

// ValidationRunMapInput is an input type that accepts ValidationRunMap and ValidationRunMapOutput values.
// You can construct a concrete instance of `ValidationRunMapInput` via:
//
//	ValidationRunMap{ "key": ValidationRunArgs{...} }
type ValidationRunMapInput interface {
	pulumi.Input

	ToValidationRunMapOutput() ValidationRunMapOutput
	ToValidationRunMapOutputWithContext(context.Context) ValidationRunMapOutput
}

type ValidationRunMap map[string]ValidationRunInput

func (ValidationRunMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ValidationRun)(nil)).Elem()
}

func (i ValidationRunMap) ToValidationRunMapOutput() ValidationRunMapOutput {
	return i.ToValidationRunMapOutputWithContext(context.Background())
}

func (i ValidationRunMap) ToValidationRunMapOutputWithContext(ctx context.Context) ValidationRunMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ValidationRunMapOutput)
}

type ValidationRunOutput struct{ *pulumi.OutputState }

func (ValidationRunOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ValidationRun)(nil)).Elem()
}

func (o ValidationRunOutput) ToValidationRunOutput() ValidationRunOutput {
	return o
}

func (o ValidationRunOutput) ToValidationRunOutputWithContext(ctx context.Context) ValidationRunOutput {
	return o
}

// When the run completed, RFC 3339.
func (o ValidationRunOutput) CompletedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringOutput { return v.CompletedAt }).(pulumi.StringOutput)
}

// Kubeconfig context to select. Defaults to the kubeconfig's current-context.
func (o ValidationRunOutput) Context() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.Context }).(pulumi.StringPtrOutput)
}

// Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
// the object inline.
func (o ValidationRunOutput) Criteria() RecipeCriteriaOutput {
	return o.ApplyT(func(v *ValidationRun) RecipeCriteriaOutput { return v.Criteria }).(RecipeCriteriaOutput)
}

// The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
func (o ValidationRunOutput) CtrfReport() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.CtrfReport }).(pulumi.StringPtrOutput)
}

// Number of checks that failed.
func (o ValidationRunOutput) Failed() pulumi.IntOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.IntOutput { return v.Failed }).(pulumi.IntOutput)
}

// Names of image pull Secrets (in the validation namespace) for the
// validation pods.
func (o ValidationRunOutput) ImagePullSecrets() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringArrayOutput { return v.ImagePullSecrets }).(pulumi.StringArrayOutput)
}

// Registry override for the snapshot-agent and validator images (air-gapped
// mirrors). Unset keeps the default registry (ghcr.io).
func (o ValidationRunOutput) ImageRegistry() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.ImageRegistry }).(pulumi.StringPtrOutput)
}

// If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
// Default: false (state-size control; per-check results are always in
// `phaseResults`).
func (o ValidationRunOutput) IncludeCtrfReport() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.BoolPtrOutput { return v.IncludeCtrfReport }).(pulumi.BoolPtrOutput)
}

// Kubeconfig contents for the target cluster. Mutually exclusive with
// `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
// var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
// duration of the run and removed afterward.
func (o ValidationRunOutput) Kubeconfig() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.Kubeconfig }).(pulumi.StringPtrOutput)
}

// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
func (o ValidationRunOutput) KubeconfigPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.KubeconfigPath }).(pulumi.StringPtrOutput)
}

// Namespace for the validation harness — use a dedicated one: it hosts the
// privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
// on first run and deliberately never deletes it. Must be a valid DNS-1123
// label and not a "kube-" system namespace. Default: "aicr-validation".
func (o ValidationRunOutput) Namespace() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.Namespace }).(pulumi.StringPtrOutput)
}

// Node selector applied to the validation workload pods. Use when GPU nodes
// carry non-standard labels.
func (o ValidationRunOutput) NodeSelector() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringMapOutput { return v.NodeSelector }).(pulumi.StringMapOutput)
}

// Number of checks with an inconclusive outcome (crash, OOM, timeout;
// includes CTRF "pending").
func (o ValidationRunOutput) Other() pulumi.IntOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.IntOutput { return v.Other }).(pulumi.IntOutput)
}

// Number of checks that passed.
func (o ValidationRunOutput) Passed() pulumi.IntOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.IntOutput { return v.Passed }).(pulumi.IntOutput)
}

// Per-check results across all phases run.
func (o ValidationRunOutput) PhaseResults() CheckResultArrayOutput {
	return o.ApplyT(func(v *ValidationRun) CheckResultArrayOutput { return v.PhaseResults }).(CheckResultArrayOutput)
}

// Validation phases to run: any of "deployment", "conformance",
// "performance". Default: ["deployment", "conformance"] — "performance" is an
// explicit opt-in (long-running and hardware-bound).
func (o ValidationRunOutput) Phases() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringArrayOutput { return v.Phases }).(pulumi.StringArrayOutput)
}

// The readiness pre-flight failure message; empty unless status is
// "readiness-failed".
func (o ValidationRunOutput) ReadinessMessage() pulumi.StringOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringOutput { return v.ReadinessMessage }).(pulumi.StringOutput)
}

// Recipe-data version assertion (not a pin). When set, it must equal this
// provider build's embedded AICR recipe-data version or Create fails before
// any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
// provider upgrade between deploy and validate.
func (o ValidationRunOutput) RecipeDataVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringPtrOutput { return v.RecipeDataVersion }).(pulumi.StringPtrOutput)
}

// The resolved AICR recipe name that was validated.
func (o ValidationRunOutput) RecipeName() pulumi.StringOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringOutput { return v.RecipeName }).(pulumi.StringOutput)
}

// The AICR recipe data version that was validated.
func (o ValidationRunOutput) RecipeVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringOutput { return v.RecipeVersion }).(pulumi.StringOutput)
}

// Whether the snapshot agent requires GPU nodes. Set false for
// hardware-free clusters (kind). Default: true.
func (o ValidationRunOutput) RequireGpu() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.BoolPtrOutput { return v.RequireGpu }).(pulumi.BoolPtrOutput)
}

// The run identifier labeling this run's cluster-side artifacts.
func (o ValidationRunOutput) RunId() pulumi.StringOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringOutput { return v.RunId }).(pulumi.StringOutput)
}

// Number of checks that were skipped.
func (o ValidationRunOutput) Skipped() pulumi.IntOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.IntOutput { return v.Skipped }).(pulumi.IntOutput)
}

// Rollup verdict: "passed", "failed", or "readiness-failed". Checks with
// status "other" never flip the rollup (they are counted and listed).
// Infrastructure errors have no status — they fail the update outright.
func (o ValidationRunOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// If true, a failed (or readiness-failed) validation fails the update while
// still persisting the full results in state. The engine then re-runs
// validation on every subsequent `pulumi up` until it passes. Default: false —
// results are recorded and the update succeeds; read the `status` output.
func (o ValidationRunOutput) Strict() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.BoolPtrOutput { return v.Strict }).(pulumi.BoolPtrOutput)
}

// Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
func (o ValidationRunOutput) TimeoutMinutes() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.IntPtrOutput { return v.TimeoutMinutes }).(pulumi.IntPtrOutput)
}

// Tolerations applied to the validation workload pods (e.g. NCCL benchmark
// pods). Required in practice on tainted GPU node groups; when unset, the
// validator's default tolerate-all is kept.
func (o ValidationRunOutput) Tolerations() TolerationArrayOutput {
	return o.ApplyT(func(v *ValidationRun) TolerationArrayOutput { return v.Tolerations }).(TolerationArrayOutput)
}

// Arbitrary values; changing any of them replaces the resource and re-runs
// validation (every input change does). Wire `triggers: [stack.deployedComponents]`
// for re-validation cadence.
func (o ValidationRunOutput) Triggers() pulumi.ArrayOutput {
	return o.ApplyT(func(v *ValidationRun) pulumi.ArrayOutput { return v.Triggers }).(pulumi.ArrayOutput)
}

type ValidationRunArrayOutput struct{ *pulumi.OutputState }

func (ValidationRunArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ValidationRun)(nil)).Elem()
}

func (o ValidationRunArrayOutput) ToValidationRunArrayOutput() ValidationRunArrayOutput {
	return o
}

func (o ValidationRunArrayOutput) ToValidationRunArrayOutputWithContext(ctx context.Context) ValidationRunArrayOutput {
	return o
}

func (o ValidationRunArrayOutput) Index(i pulumi.IntInput) ValidationRunOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ValidationRun {
		return vs[0].([]*ValidationRun)[vs[1].(int)]
	}).(ValidationRunOutput)
}

type ValidationRunMapOutput struct{ *pulumi.OutputState }

func (ValidationRunMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ValidationRun)(nil)).Elem()
}

func (o ValidationRunMapOutput) ToValidationRunMapOutput() ValidationRunMapOutput {
	return o
}

func (o ValidationRunMapOutput) ToValidationRunMapOutputWithContext(ctx context.Context) ValidationRunMapOutput {
	return o
}

func (o ValidationRunMapOutput) MapIndex(k pulumi.StringInput) ValidationRunOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ValidationRun {
		return vs[0].(map[string]*ValidationRun)[vs[1].(string)]
	}).(ValidationRunOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ValidationRunInput)(nil)).Elem(), &ValidationRun{})
	pulumi.RegisterInputType(reflect.TypeOf((*ValidationRunArrayInput)(nil)).Elem(), ValidationRunArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ValidationRunMapInput)(nil)).Elem(), ValidationRunMap{})
	pulumi.RegisterOutputType(ValidationRunOutput{})
	pulumi.RegisterOutputType(ValidationRunArrayOutput{})
	pulumi.RegisterOutputType(ValidationRunMapOutput{})
}
