// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NvidiaAicr
{
    [NvidiaAicrResourceType("nvidia-aicr:index:ClusterStack")]
    public partial class ClusterStack : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// Number of components deployed.
        /// </summary>
        [Output("componentCount")]
        public Output<int> ComponentCount { get; private set; } = null!;

        /// <summary>
        /// Names of all components deployed as part of this stack, in topological order.
        /// </summary>
        [Output("deployedComponents")]
        public Output<ImmutableArray<string>> DeployedComponents { get; private set; } = null!;

        /// <summary>
        /// The resolved AICR recipe name (e.g., "h100-eks-ubuntu-training-kubeflow").
        /// </summary>
        [Output("recipeName")]
        public Output<string> RecipeName { get; private set; } = null!;

        /// <summary>
        /// The AICR recipe data version embedded in this provider build.
        /// </summary>
        [Output("recipeVersion")]
        public Output<string> RecipeVersion { get; private set; } = null!;


        /// <summary>
        /// Create a ClusterStack resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ClusterStack(string name, ClusterStackArgs args, ComponentResourceOptions? options = null)
            : base("nvidia-aicr:index:ClusterStack", name, args ?? new ClusterStackArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class ClusterStackArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GPU accelerator type. Selects the AICR recipe family.
        /// 
        /// Supported values: "h100", "gb200", "b200".
        /// </summary>
        [Input("accelerator", required: true)]
        public string Accelerator { get; set; } = null!;

        [Input("componentOverrides")]
        private InputMap<Inputs.ComponentOverrideArgs>? _componentOverrides;

        /// <summary>
        /// Per-component overrides. Map of AICR component name to override settings
        /// (version, namespace, Helm values). Values are deep-merged with the recipe
        /// defaults; only the keys you specify are changed.
        /// </summary>
        public InputMap<Inputs.ComponentOverrideArgs> ComponentOverrides
        {
            get => _componentOverrides ?? (_componentOverrides = new InputMap<Inputs.ComponentOverrideArgs>());
            set => _componentOverrides = value;
        }

        /// <summary>
        /// Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
        /// </summary>
        [Input("context")]
        public string? Context { get; set; }

        /// <summary>
        /// Workload intent. Selects between training-oriented and inference-oriented
        /// component sets.
        /// 
        /// Supported values: "training", "inference".
        /// </summary>
        [Input("intent", required: true)]
        public string Intent { get; set; } = null!;

        /// <summary>
        /// Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
        /// Accepts computed outputs from cluster resources (e.g., an EKS cluster's
        /// KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
        /// 
        /// If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
        /// (KUBECONFIG env var or ~/.kube/config) is used.
        /// </summary>
        [Input("kubeconfig")]
        public Input<string>? Kubeconfig { get; set; }

        /// <summary>
        /// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        /// Prefer `kubeconfig` when chaining off a cluster resource's output.
        /// </summary>
        [Input("kubeconfigPath")]
        public string? KubeconfigPath { get; set; }

        /// <summary>
        /// Operating system flavor.
        /// 
        /// Supported values: "ubuntu" (default), "cos" (Container-Optimized OS, GKE only).
        /// </summary>
        [Input("os")]
        public string? Os { get; set; }

        /// <summary>
        /// ML platform/framework to layer on top of the base recipe.
        /// 
        /// Supported values: "kubeflow" (training), "dynamo" (inference), "nim" (inference, EKS+H100 only).
        /// Leave unset for a base recipe with no platform components.
        /// </summary>
        [Input("platform")]
        public string? Platform { get; set; }

        /// <summary>
        /// Kubernetes service. Selects cloud-specific operators and storage drivers.
        /// 
        /// Supported values: "aks", "eks", "gke", "kind", "oke". Use "kind" for local
        /// hardware-free development of the deployment pipeline.
        /// </summary>
        [Input("service", required: true)]
        public string Service { get; set; } = null!;

        /// <summary>
        /// If true, do not wait for each Helm release to become ready before continuing.
        /// Faster previews/updates at the cost of losing readiness signal. Default: false.
        /// </summary>
        [Input("skipAwait")]
        public bool? SkipAwait { get; set; }

        [Input("skipComponents")]
        private InputList<string>? _skipComponents;

        /// <summary>
        /// Component names to exclude from the deployment. Useful for swapping in your
        /// own installation of a component (e.g., bring-your-own cert-manager) or for
        /// deploying onto bare-metal where cloud-specific operators are not relevant.
        /// </summary>
        public InputList<string> SkipComponents
        {
            get => _skipComponents ?? (_skipComponents = new InputList<string>());
            set => _skipComponents = value;
        }

        public ClusterStackArgs()
        {
            Os = "ubuntu";
            SkipAwait = false;
        }
        public static new ClusterStackArgs Empty => new ClusterStackArgs();
    }
}
