// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class CheckResult {
    /**
     * @return The check&#39;s failure or diagnostic message, if any.
     * 
     */
    private String message;
    /**
     * @return The check&#39;s name (e.g. &#34;gpu-operator-health&#34;).
     * 
     */
    private String name;
    /**
     * @return The validation phase the check ran in.
     * 
     */
    private String phase;
    /**
     * @return The check&#39;s status: &#34;passed&#34;, &#34;failed&#34;, &#34;skipped&#34;, &#34;pending&#34;, or &#34;other&#34;.
     * 
     */
    private String status;

    private CheckResult() {}
    /**
     * @return The check&#39;s failure or diagnostic message, if any.
     * 
     */
    public String message() {
        return this.message;
    }
    /**
     * @return The check&#39;s name (e.g. &#34;gpu-operator-health&#34;).
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return The validation phase the check ran in.
     * 
     */
    public String phase() {
        return this.phase;
    }
    /**
     * @return The check&#39;s status: &#34;passed&#34;, &#34;failed&#34;, &#34;skipped&#34;, &#34;pending&#34;, or &#34;other&#34;.
     * 
     */
    public String status() {
        return this.status;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(CheckResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String message;
        private String name;
        private String phase;
        private String status;
        public Builder() {}
        public Builder(CheckResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.message = defaults.message;
    	      this.name = defaults.name;
    	      this.phase = defaults.phase;
    	      this.status = defaults.status;
        }

        @CustomType.Setter
        public Builder message(String message) {
            if (message == null) {
              throw new MissingRequiredPropertyException("CheckResult", "message");
            }
            this.message = message;
            return this;
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("CheckResult", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder phase(String phase) {
            if (phase == null) {
              throw new MissingRequiredPropertyException("CheckResult", "phase");
            }
            this.phase = phase;
            return this;
        }
        @CustomType.Setter
        public Builder status(String status) {
            if (status == null) {
              throw new MissingRequiredPropertyException("CheckResult", "status");
            }
            this.status = status;
            return this;
        }
        public CheckResult build() {
            final var _resultValue = new CheckResult();
            _resultValue.message = message;
            _resultValue.name = name;
            _resultValue.phase = phase;
            _resultValue.status = status;
            return _resultValue;
        }
    }
}
