// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class RecipeCriteria {
    /**
     * @return GPU accelerator type. Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
     * 
     */
    private String accelerator;
    /**
     * @return Workload intent. Supported values: &#34;training&#34;, &#34;inference&#34;.
     * 
     */
    private String intent;
    /**
     * @return Worker-node count hint used to size the recipe.
     * 
     */
    private @Nullable Integer nodes;
    /**
     * @return Operating system flavor of the worker nodes. Leave unset for OS-agnostic
     * resolution. Supported values: &#34;ubuntu&#34;, &#34;cos&#34;, &#34;ol&#34;.
     * 
     */
    private @Nullable String os;
    /**
     * @return ML platform/framework. Supported values: &#34;kubeflow&#34; (training),
     * &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
     * 
     */
    private @Nullable String platform;
    /**
     * @return Kubernetes service. Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;.
     * 
     */
    private String service;
    /**
     * @return Recipe components the stack intentionally did not deploy (ClusterStack&#39;s
     * `skipComponents`). ValidationRun treats them as out of scope rather than
     * missing: checks that presuppose one of them (e.g. the gpu-operator health,
     * DCGM metrics, and GPU-HPA checks when &#34;gpu-operator&#34; is skipped) are reported
     * &#34;skipped&#34; with a reason instead of failing, and the SDK&#39;s component-aware
     * checks see the components as disabled. A ClusterStack&#39;s `criteria` output
     * carries its own skipComponents, so wiring it keeps validation aligned with
     * the deployed subset automatically. Skipping does not verify a replacement
     * you run yourself — those checks are simply not made.
     * 
     */
    private @Nullable List<String> skipComponents;

    private RecipeCriteria() {}
    /**
     * @return GPU accelerator type. Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
     * 
     */
    public String accelerator() {
        return this.accelerator;
    }
    /**
     * @return Workload intent. Supported values: &#34;training&#34;, &#34;inference&#34;.
     * 
     */
    public String intent() {
        return this.intent;
    }
    /**
     * @return Worker-node count hint used to size the recipe.
     * 
     */
    public Optional<Integer> nodes() {
        return Optional.ofNullable(this.nodes);
    }
    /**
     * @return Operating system flavor of the worker nodes. Leave unset for OS-agnostic
     * resolution. Supported values: &#34;ubuntu&#34;, &#34;cos&#34;, &#34;ol&#34;.
     * 
     */
    public Optional<String> os() {
        return Optional.ofNullable(this.os);
    }
    /**
     * @return ML platform/framework. Supported values: &#34;kubeflow&#34; (training),
     * &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
     * 
     */
    public Optional<String> platform() {
        return Optional.ofNullable(this.platform);
    }
    /**
     * @return Kubernetes service. Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;.
     * 
     */
    public String service() {
        return this.service;
    }
    /**
     * @return Recipe components the stack intentionally did not deploy (ClusterStack&#39;s
     * `skipComponents`). ValidationRun treats them as out of scope rather than
     * missing: checks that presuppose one of them (e.g. the gpu-operator health,
     * DCGM metrics, and GPU-HPA checks when &#34;gpu-operator&#34; is skipped) are reported
     * &#34;skipped&#34; with a reason instead of failing, and the SDK&#39;s component-aware
     * checks see the components as disabled. A ClusterStack&#39;s `criteria` output
     * carries its own skipComponents, so wiring it keeps validation aligned with
     * the deployed subset automatically. Skipping does not verify a replacement
     * you run yourself — those checks are simply not made.
     * 
     */
    public List<String> skipComponents() {
        return this.skipComponents == null ? List.of() : this.skipComponents;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(RecipeCriteria defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String accelerator;
        private String intent;
        private @Nullable Integer nodes;
        private @Nullable String os;
        private @Nullable String platform;
        private String service;
        private @Nullable List<String> skipComponents;
        public Builder() {}
        public Builder(RecipeCriteria defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.accelerator = defaults.accelerator;
    	      this.intent = defaults.intent;
    	      this.nodes = defaults.nodes;
    	      this.os = defaults.os;
    	      this.platform = defaults.platform;
    	      this.service = defaults.service;
    	      this.skipComponents = defaults.skipComponents;
        }

        @CustomType.Setter
        public Builder accelerator(String accelerator) {
            if (accelerator == null) {
              throw new MissingRequiredPropertyException("RecipeCriteria", "accelerator");
            }
            this.accelerator = accelerator;
            return this;
        }
        @CustomType.Setter
        public Builder intent(String intent) {
            if (intent == null) {
              throw new MissingRequiredPropertyException("RecipeCriteria", "intent");
            }
            this.intent = intent;
            return this;
        }
        @CustomType.Setter
        public Builder nodes(@Nullable Integer nodes) {

            this.nodes = nodes;
            return this;
        }
        @CustomType.Setter
        public Builder os(@Nullable String os) {

            this.os = os;
            return this;
        }
        @CustomType.Setter
        public Builder platform(@Nullable String platform) {

            this.platform = platform;
            return this;
        }
        @CustomType.Setter
        public Builder service(String service) {
            if (service == null) {
              throw new MissingRequiredPropertyException("RecipeCriteria", "service");
            }
            this.service = service;
            return this;
        }
        @CustomType.Setter
        public Builder skipComponents(@Nullable List<String> skipComponents) {

            this.skipComponents = skipComponents;
            return this;
        }
        public Builder skipComponents(String... skipComponents) {
            return skipComponents(List.of(skipComponents));
        }
        public RecipeCriteria build() {
            final var _resultValue = new RecipeCriteria();
            _resultValue.accelerator = accelerator;
            _resultValue.intent = intent;
            _resultValue.nodes = nodes;
            _resultValue.os = os;
            _resultValue.platform = platform;
            _resultValue.service = service;
            _resultValue.skipComponents = skipComponents;
            return _resultValue;
        }
    }
}
