// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class Toleration {
    /**
     * @return The taint effect to match: &#34;NoSchedule&#34;, &#34;PreferNoSchedule&#34;, or
     * &#34;NoExecute&#34;. Empty matches all effects.
     * 
     */
    private @Nullable String effect;
    /**
     * @return The taint key the toleration applies to. Empty means match all keys
     * (with operator &#34;Exists&#34;).
     * 
     */
    private @Nullable String key;
    /**
     * @return Key-value relationship: &#34;Exists&#34; or &#34;Equal&#34;. Default: &#34;Equal&#34;.
     * 
     */
    private @Nullable String operator;
    /**
     * @return How long the pod tolerates a &#34;NoExecute&#34; taint, in seconds.
     * 
     */
    private @Nullable Integer tolerationSeconds;
    /**
     * @return The taint value to match (with operator &#34;Equal&#34;).
     * 
     */
    private @Nullable String value;

    private Toleration() {}
    /**
     * @return The taint effect to match: &#34;NoSchedule&#34;, &#34;PreferNoSchedule&#34;, or
     * &#34;NoExecute&#34;. Empty matches all effects.
     * 
     */
    public Optional<String> effect() {
        return Optional.ofNullable(this.effect);
    }
    /**
     * @return The taint key the toleration applies to. Empty means match all keys
     * (with operator &#34;Exists&#34;).
     * 
     */
    public Optional<String> key() {
        return Optional.ofNullable(this.key);
    }
    /**
     * @return Key-value relationship: &#34;Exists&#34; or &#34;Equal&#34;. Default: &#34;Equal&#34;.
     * 
     */
    public Optional<String> operator() {
        return Optional.ofNullable(this.operator);
    }
    /**
     * @return How long the pod tolerates a &#34;NoExecute&#34; taint, in seconds.
     * 
     */
    public Optional<Integer> tolerationSeconds() {
        return Optional.ofNullable(this.tolerationSeconds);
    }
    /**
     * @return The taint value to match (with operator &#34;Equal&#34;).
     * 
     */
    public Optional<String> value() {
        return Optional.ofNullable(this.value);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(Toleration defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String effect;
        private @Nullable String key;
        private @Nullable String operator;
        private @Nullable Integer tolerationSeconds;
        private @Nullable String value;
        public Builder() {}
        public Builder(Toleration defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.effect = defaults.effect;
    	      this.key = defaults.key;
    	      this.operator = defaults.operator;
    	      this.tolerationSeconds = defaults.tolerationSeconds;
    	      this.value = defaults.value;
        }

        @CustomType.Setter
        public Builder effect(@Nullable String effect) {

            this.effect = effect;
            return this;
        }
        @CustomType.Setter
        public Builder key(@Nullable String key) {

            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder operator(@Nullable String operator) {

            this.operator = operator;
            return this;
        }
        @CustomType.Setter
        public Builder tolerationSeconds(@Nullable Integer tolerationSeconds) {

            this.tolerationSeconds = tolerationSeconds;
            return this;
        }
        @CustomType.Setter
        public Builder value(@Nullable String value) {

            this.value = value;
            return this;
        }
        public Toleration build() {
            final var _resultValue = new Toleration();
            _resultValue.effect = effect;
            _resultValue.key = key;
            _resultValue.operator = operator;
            _resultValue.tolerationSeconds = tolerationSeconds;
            _resultValue.value = value;
            return _resultValue;
        }
    }
}
