// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Outputs
{

    /// <summary>
    /// The outcome of one validator check.
    /// </summary>
    [OutputType]
    public sealed class CheckResult
    {
        /// <summary>
        /// The check's failure or diagnostic message, if any.
        /// </summary>
        public readonly string Message;
        /// <summary>
        /// The check's name (e.g. "gpu-operator-health").
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The validation phase the check ran in.
        /// </summary>
        public readonly string Phase;
        /// <summary>
        /// The check's status: "passed", "failed", "skipped", "pending", or "other".
        /// </summary>
        public readonly string Status;

        [OutputConstructor]
        private CheckResult(
            string message,

            string name,

            string phase,

            string status)
        {
            Message = message;
            Name = name;
            Phase = phase;
            Status = status;
        }
    }
}
