// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Outputs
{

    /// <summary>
    /// Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
    /// intent / os / platform / nodes inputs. Wire a ClusterStack's `criteria`
    /// output here so deployment and validation resolve the identical recipe.
    /// </summary>
    [OutputType]
    public sealed class RecipeCriteria
    {
        /// <summary>
        /// GPU accelerator type. Supported values: "h100", "gb200", "b200".
        /// </summary>
        public readonly string Accelerator;
        /// <summary>
        /// Workload intent. Supported values: "training", "inference".
        /// </summary>
        public readonly string Intent;
        /// <summary>
        /// Worker-node count hint used to size the recipe.
        /// </summary>
        public readonly int? Nodes;
        /// <summary>
        /// Operating system flavor of the worker nodes. Leave unset for OS-agnostic
        /// resolution. Supported values: "ubuntu", "cos", "ol".
        /// </summary>
        public readonly string? Os;
        /// <summary>
        /// ML platform/framework. Supported values: "kubeflow" (training),
        /// "dynamo" (inference), "nim" (inference, EKS+H100 only).
        /// </summary>
        public readonly string? Platform;
        /// <summary>
        /// Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
        /// </summary>
        public readonly string Service;

        [OutputConstructor]
        private RecipeCriteria(
            string accelerator,

            string intent,

            int? nodes,

            string? os,

            string? platform,

            string service)
        {
            Accelerator = accelerator;
            Intent = intent;
            Nodes = nodes;
            Os = os;
            Platform = platform;
            Service = service;
        }
    }
}
