// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Outputs
{

    /// <summary>
    /// Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
    /// intent / os / platform / nodes inputs, plus the skipComponents the stack
    /// deployed without. Wire a ClusterStack's `criteria` output here so deployment
    /// and validation resolve the identical recipe and agree on which of its
    /// components are in scope.
    /// </summary>
    [OutputType]
    public sealed class RecipeCriteria
    {
        /// <summary>
        /// GPU accelerator type. Supported values: "h100", "gb200", "b200".
        /// </summary>
        public readonly string Accelerator;
        /// <summary>
        /// Workload intent. Supported values: "training", "inference".
        /// </summary>
        public readonly string Intent;
        /// <summary>
        /// Worker-node count hint used to size the recipe.
        /// </summary>
        public readonly int? Nodes;
        /// <summary>
        /// Operating system flavor of the worker nodes. Leave unset for OS-agnostic
        /// resolution. Supported values: "ubuntu", "cos", "ol".
        /// </summary>
        public readonly string? Os;
        /// <summary>
        /// ML platform/framework. Supported values: "kubeflow" (training),
        /// "dynamo" (inference), "nim" (inference, EKS+H100 only).
        /// </summary>
        public readonly string? Platform;
        /// <summary>
        /// Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
        /// </summary>
        public readonly string Service;
        /// <summary>
        /// Recipe components the stack intentionally did not deploy (ClusterStack's
        /// `skipComponents`). ValidationRun treats them as out of scope rather than
        /// missing: checks that presuppose one of them (e.g. the gpu-operator health,
        /// DCGM metrics, and GPU-HPA checks when "gpu-operator" is skipped) are reported
        /// "skipped" with a reason instead of failing, and the SDK's component-aware
        /// checks see the components as disabled. A ClusterStack's `criteria` output
        /// carries its own skipComponents, so wiring it keeps validation aligned with
        /// the deployed subset automatically. Skipping does not verify a replacement
        /// you run yourself — those checks are simply not made.
        /// </summary>
        public readonly ImmutableArray<string> SkipComponents;

        [OutputConstructor]
        private RecipeCriteria(
            string accelerator,

            string intent,

            int? nodes,

            string? os,

            string? platform,

            string service,

            ImmutableArray<string> skipComponents)
        {
            Accelerator = accelerator;
            Intent = intent;
            Nodes = nodes;
            Os = os;
            Platform = platform;
            Service = service;
            SkipComponents = skipComponents;
        }
    }
}
