// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Outputs
{

    /// <summary>
    /// A Kubernetes pod toleration applied to validation workload pods.
    /// </summary>
    [OutputType]
    public sealed class Toleration
    {
        /// <summary>
        /// The taint effect to match: "NoSchedule", "PreferNoSchedule", or
        /// "NoExecute". Empty matches all effects.
        /// </summary>
        public readonly string? Effect;
        /// <summary>
        /// The taint key the toleration applies to. Empty means match all keys
        /// (with operator "Exists").
        /// </summary>
        public readonly string? Key;
        /// <summary>
        /// Key-value relationship: "Exists" or "Equal". Default: "Equal".
        /// </summary>
        public readonly string? Operator;
        /// <summary>
        /// How long the pod tolerates a "NoExecute" taint, in seconds.
        /// </summary>
        public readonly int? TolerationSeconds;
        /// <summary>
        /// The taint value to match (with operator "Equal").
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private Toleration(
            string? effect,

            string? key,

            string? @operator,

            int? tolerationSeconds,

            string? value)
        {
            Effect = effect;
            Key = key;
            Operator = @operator;
            TolerationSeconds = tolerationSeconds;
            Value = value;
        }
    }
}
