# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._inputs import *

__all__ = ['ClusterStackArgs', 'ClusterStack']

@pulumi.input_type
class ClusterStackArgs:
    def __init__(__self__, *,
                 accelerator: _builtins.str,
                 intent: _builtins.str,
                 service: _builtins.str,
                 component_overrides: Optional[pulumi.Input[Mapping[str, pulumi.Input['ComponentOverrideArgs']]]] = None,
                 context: Optional[_builtins.str] = None,
                 kubeconfig: Optional[pulumi.Input[_builtins.str]] = None,
                 kubeconfig_path: Optional[_builtins.str] = None,
                 os: Optional[_builtins.str] = None,
                 platform: Optional[_builtins.str] = None,
                 skip_await: Optional[_builtins.bool] = None,
                 skip_components: Optional[pulumi.Input[Sequence[_builtins.str]]] = None):
        """
        The set of arguments for constructing a ClusterStack resource.

        :param _builtins.str accelerator: GPU accelerator type. Selects the AICR recipe family.
               
               Supported values: "h100", "gb200", "b200".
        :param _builtins.str intent: Workload intent. Selects between training-oriented and inference-oriented
               component sets.
               
               Supported values: "training", "inference".
        :param _builtins.str service: Kubernetes service. Selects cloud-specific operators and storage drivers.
               
               Supported values: "aks", "eks", "gke", "kind", "oke". Use "kind" for local
               hardware-free development of the deployment pipeline.
        :param pulumi.Input[Mapping[str, pulumi.Input['ComponentOverrideArgs']]] component_overrides: Per-component overrides. Map of AICR component name to override settings
               (version, namespace, Helm values). Values are deep-merged with the recipe
               defaults; only the keys you specify are changed.
        :param _builtins.str context: Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
        :param pulumi.Input[_builtins.str] kubeconfig: Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
               Accepts computed outputs from cluster resources (e.g., an EKS cluster's
               KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
               
               If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
               (KUBECONFIG env var or ~/.kube/config) is used.
        :param _builtins.str kubeconfig_path: Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
               Prefer `kubeconfig` when chaining off a cluster resource's output.
        :param _builtins.str os: Operating system flavor.
               
               Supported values: "ubuntu" (default), "cos" (Container-Optimized OS, GKE only).
        :param _builtins.str platform: ML platform/framework to layer on top of the base recipe.
               
               Supported values: "kubeflow" (training), "dynamo" (inference), "nim" (inference, EKS+H100 only).
               Leave unset for a base recipe with no platform components.
        :param _builtins.bool skip_await: If true, do not wait for each Helm release to become ready before continuing.
               Faster previews/updates at the cost of losing readiness signal. Default: false.
        :param pulumi.Input[Sequence[_builtins.str]] skip_components: Component names to exclude from the deployment. Useful for swapping in your
               own installation of a component (e.g., bring-your-own cert-manager) or for
               deploying onto bare-metal where cloud-specific operators are not relevant.
        """
        pulumi.set(__self__, "accelerator", accelerator)
        pulumi.set(__self__, "intent", intent)
        pulumi.set(__self__, "service", service)
        if component_overrides is not None:
            pulumi.set(__self__, "component_overrides", component_overrides)
        if context is not None:
            pulumi.set(__self__, "context", context)
        if kubeconfig is not None:
            pulumi.set(__self__, "kubeconfig", kubeconfig)
        if kubeconfig_path is not None:
            pulumi.set(__self__, "kubeconfig_path", kubeconfig_path)
        if os is None:
            os = 'ubuntu'
        if os is not None:
            pulumi.set(__self__, "os", os)
        if platform is not None:
            pulumi.set(__self__, "platform", platform)
        if skip_await is None:
            skip_await = False
        if skip_await is not None:
            pulumi.set(__self__, "skip_await", skip_await)
        if skip_components is not None:
            pulumi.set(__self__, "skip_components", skip_components)

    @_builtins.property
    @pulumi.getter
    def accelerator(self) -> _builtins.str:
        """
        GPU accelerator type. Selects the AICR recipe family.

        Supported values: "h100", "gb200", "b200".
        """
        return pulumi.get(self, "accelerator")

    @accelerator.setter
    def accelerator(self, value: _builtins.str):
        pulumi.set(self, "accelerator", value)

    @_builtins.property
    @pulumi.getter
    def intent(self) -> _builtins.str:
        """
        Workload intent. Selects between training-oriented and inference-oriented
        component sets.

        Supported values: "training", "inference".
        """
        return pulumi.get(self, "intent")

    @intent.setter
    def intent(self, value: _builtins.str):
        pulumi.set(self, "intent", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> _builtins.str:
        """
        Kubernetes service. Selects cloud-specific operators and storage drivers.

        Supported values: "aks", "eks", "gke", "kind", "oke". Use "kind" for local
        hardware-free development of the deployment pipeline.
        """
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: _builtins.str):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter(name="componentOverrides")
    def component_overrides(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input['ComponentOverrideArgs']]]]:
        """
        Per-component overrides. Map of AICR component name to override settings
        (version, namespace, Helm values). Values are deep-merged with the recipe
        defaults; only the keys you specify are changed.
        """
        return pulumi.get(self, "component_overrides")

    @component_overrides.setter
    def component_overrides(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input['ComponentOverrideArgs']]]]):
        pulumi.set(self, "component_overrides", value)

    @_builtins.property
    @pulumi.getter
    def context(self) -> Optional[_builtins.str]:
        """
        Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
        """
        return pulumi.get(self, "context")

    @context.setter
    def context(self, value: Optional[_builtins.str]):
        pulumi.set(self, "context", value)

    @_builtins.property
    @pulumi.getter
    def kubeconfig(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
        Accepts computed outputs from cluster resources (e.g., an EKS cluster's
        KubeconfigJson). Mutually exclusive with `kubeconfigPath`.

        If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
        (KUBECONFIG env var or ~/.kube/config) is used.
        """
        return pulumi.get(self, "kubeconfig")

    @kubeconfig.setter
    def kubeconfig(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "kubeconfig", value)

    @_builtins.property
    @pulumi.getter(name="kubeconfigPath")
    def kubeconfig_path(self) -> Optional[_builtins.str]:
        """
        Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        Prefer `kubeconfig` when chaining off a cluster resource's output.
        """
        return pulumi.get(self, "kubeconfig_path")

    @kubeconfig_path.setter
    def kubeconfig_path(self, value: Optional[_builtins.str]):
        pulumi.set(self, "kubeconfig_path", value)

    @_builtins.property
    @pulumi.getter
    def os(self) -> Optional[_builtins.str]:
        """
        Operating system flavor.

        Supported values: "ubuntu" (default), "cos" (Container-Optimized OS, GKE only).
        """
        return pulumi.get(self, "os")

    @os.setter
    def os(self, value: Optional[_builtins.str]):
        pulumi.set(self, "os", value)

    @_builtins.property
    @pulumi.getter
    def platform(self) -> Optional[_builtins.str]:
        """
        ML platform/framework to layer on top of the base recipe.

        Supported values: "kubeflow" (training), "dynamo" (inference), "nim" (inference, EKS+H100 only).
        Leave unset for a base recipe with no platform components.
        """
        return pulumi.get(self, "platform")

    @platform.setter
    def platform(self, value: Optional[_builtins.str]):
        pulumi.set(self, "platform", value)

    @_builtins.property
    @pulumi.getter(name="skipAwait")
    def skip_await(self) -> Optional[_builtins.bool]:
        """
        If true, do not wait for each Helm release to become ready before continuing.
        Faster previews/updates at the cost of losing readiness signal. Default: false.
        """
        return pulumi.get(self, "skip_await")

    @skip_await.setter
    def skip_await(self, value: Optional[_builtins.bool]):
        pulumi.set(self, "skip_await", value)

    @_builtins.property
    @pulumi.getter(name="skipComponents")
    def skip_components(self) -> Optional[pulumi.Input[Sequence[_builtins.str]]]:
        """
        Component names to exclude from the deployment. Useful for swapping in your
        own installation of a component (e.g., bring-your-own cert-manager) or for
        deploying onto bare-metal where cloud-specific operators are not relevant.
        """
        return pulumi.get(self, "skip_components")

    @skip_components.setter
    def skip_components(self, value: Optional[pulumi.Input[Sequence[_builtins.str]]]):
        pulumi.set(self, "skip_components", value)


@pulumi.type_token("nvidia-aicr:index:ClusterStack")
class ClusterStack(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accelerator: Optional[_builtins.str] = None,
                 component_overrides: Optional[pulumi.Input[Mapping[str, pulumi.Input[Union['ComponentOverrideArgs', 'ComponentOverrideArgsDict']]]]] = None,
                 context: Optional[_builtins.str] = None,
                 intent: Optional[_builtins.str] = None,
                 kubeconfig: Optional[pulumi.Input[_builtins.str]] = None,
                 kubeconfig_path: Optional[_builtins.str] = None,
                 os: Optional[_builtins.str] = None,
                 platform: Optional[_builtins.str] = None,
                 service: Optional[_builtins.str] = None,
                 skip_await: Optional[_builtins.bool] = None,
                 skip_components: Optional[pulumi.Input[Sequence[_builtins.str]]] = None,
                 __props__=None):
        """
        Create a ClusterStack resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param _builtins.str accelerator: GPU accelerator type. Selects the AICR recipe family.
               
               Supported values: "h100", "gb200", "b200".
        :param pulumi.Input[Mapping[str, pulumi.Input[Union['ComponentOverrideArgs', 'ComponentOverrideArgsDict']]]] component_overrides: Per-component overrides. Map of AICR component name to override settings
               (version, namespace, Helm values). Values are deep-merged with the recipe
               defaults; only the keys you specify are changed.
        :param _builtins.str context: Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
        :param _builtins.str intent: Workload intent. Selects between training-oriented and inference-oriented
               component sets.
               
               Supported values: "training", "inference".
        :param pulumi.Input[_builtins.str] kubeconfig: Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
               Accepts computed outputs from cluster resources (e.g., an EKS cluster's
               KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
               
               If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
               (KUBECONFIG env var or ~/.kube/config) is used.
        :param _builtins.str kubeconfig_path: Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
               Prefer `kubeconfig` when chaining off a cluster resource's output.
        :param _builtins.str os: Operating system flavor.
               
               Supported values: "ubuntu" (default), "cos" (Container-Optimized OS, GKE only).
        :param _builtins.str platform: ML platform/framework to layer on top of the base recipe.
               
               Supported values: "kubeflow" (training), "dynamo" (inference), "nim" (inference, EKS+H100 only).
               Leave unset for a base recipe with no platform components.
        :param _builtins.str service: Kubernetes service. Selects cloud-specific operators and storage drivers.
               
               Supported values: "aks", "eks", "gke", "kind", "oke". Use "kind" for local
               hardware-free development of the deployment pipeline.
        :param _builtins.bool skip_await: If true, do not wait for each Helm release to become ready before continuing.
               Faster previews/updates at the cost of losing readiness signal. Default: false.
        :param pulumi.Input[Sequence[_builtins.str]] skip_components: Component names to exclude from the deployment. Useful for swapping in your
               own installation of a component (e.g., bring-your-own cert-manager) or for
               deploying onto bare-metal where cloud-specific operators are not relevant.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ClusterStackArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a ClusterStack resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ClusterStackArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ClusterStackArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accelerator: Optional[_builtins.str] = None,
                 component_overrides: Optional[pulumi.Input[Mapping[str, pulumi.Input[Union['ComponentOverrideArgs', 'ComponentOverrideArgsDict']]]]] = None,
                 context: Optional[_builtins.str] = None,
                 intent: Optional[_builtins.str] = None,
                 kubeconfig: Optional[pulumi.Input[_builtins.str]] = None,
                 kubeconfig_path: Optional[_builtins.str] = None,
                 os: Optional[_builtins.str] = None,
                 platform: Optional[_builtins.str] = None,
                 service: Optional[_builtins.str] = None,
                 skip_await: Optional[_builtins.bool] = None,
                 skip_components: Optional[pulumi.Input[Sequence[_builtins.str]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ClusterStackArgs.__new__(ClusterStackArgs)

            if accelerator is None and not opts.urn:
                raise TypeError("Missing required property 'accelerator'")
            __props__.__dict__["accelerator"] = accelerator
            __props__.__dict__["component_overrides"] = component_overrides
            __props__.__dict__["context"] = context
            if intent is None and not opts.urn:
                raise TypeError("Missing required property 'intent'")
            __props__.__dict__["intent"] = intent
            __props__.__dict__["kubeconfig"] = kubeconfig
            __props__.__dict__["kubeconfig_path"] = kubeconfig_path
            if os is None:
                os = 'ubuntu'
            __props__.__dict__["os"] = os
            __props__.__dict__["platform"] = platform
            if service is None and not opts.urn:
                raise TypeError("Missing required property 'service'")
            __props__.__dict__["service"] = service
            if skip_await is None:
                skip_await = False
            __props__.__dict__["skip_await"] = skip_await
            __props__.__dict__["skip_components"] = skip_components
            __props__.__dict__["component_count"] = None
            __props__.__dict__["deployed_components"] = None
            __props__.__dict__["recipe_name"] = None
            __props__.__dict__["recipe_version"] = None
        super(ClusterStack, __self__).__init__(
            'nvidia-aicr:index:ClusterStack',
            resource_name,
            __props__,
            opts,
            remote=True)

    @_builtins.property
    @pulumi.getter(name="componentCount")
    def component_count(self) -> pulumi.Output[_builtins.int]:
        """
        Number of components deployed.
        """
        return pulumi.get(self, "component_count")

    @_builtins.property
    @pulumi.getter(name="deployedComponents")
    def deployed_components(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Names of all components deployed as part of this stack, in topological order.
        """
        return pulumi.get(self, "deployed_components")

    @_builtins.property
    @pulumi.getter(name="recipeName")
    def recipe_name(self) -> pulumi.Output[_builtins.str]:
        """
        The resolved AICR recipe name (e.g., "h100-eks-ubuntu-training-kubeflow").
        """
        return pulumi.get(self, "recipe_name")

    @_builtins.property
    @pulumi.getter(name="recipeVersion")
    def recipe_version(self) -> pulumi.Output[_builtins.str]:
        """
        The AICR recipe data version embedded in this provider build.
        """
        return pulumi.get(self, "recipe_version")

