# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import errno
from setuptools import setup, find_packages
from setuptools.command.install import install
from subprocess import check_call


VERSION = "0.0.0"
def readme():
    try:
        with open('README.md', encoding='utf-8') as f:
            return f.read()
    except FileNotFoundError:
        return "nvidia-aicr Pulumi Package - Development Version"


setup(name='pulumi_nvidia_aicr',
      python_requires='>=3.9',
      version=VERSION,
      description="Deploy validated NVIDIA AI Cluster Runtime (AICR) recipes for GPU-accelerated Kubernetes clusters.",
      long_description=readme(),
      long_description_content_type='text/markdown',
      keywords='pulumi nvidia aicr gpu kubernetes category/cloud',
      url='https://github.com/pulumi/pulumi-nvidia-aicr',
      project_urls={
          'Repository': 'https://github.com/pulumi/pulumi-nvidia-aicr'
      },
      license='Apache-2.0',
      packages=find_packages(),
      package_data={
          'pulumi_nvidia_aicr': [
              'py.typed',
              'pulumi-plugin.json',
          ]
      },
      install_requires=[
          'parver>=0.2.1',
          'pulumi>=3.165.0,<4.0.0',
          'semver>=2.8.1',
          'typing-extensions>=4.11,<5; python_version < "3.11"'
      ],
      zip_safe=False)
