// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nvidiaaicr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.nvidiaaicr.ClusterStackArgs;
import com.pulumi.nvidiaaicr.Utilities;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="nvidia-aicr:index:ClusterStack")
public class ClusterStack extends com.pulumi.resources.ComponentResource {
    /**
     * Number of components deployed.
     * 
     */
    @Export(name="componentCount", refs={Integer.class}, tree="[0]")
    private Output<Integer> componentCount;

    /**
     * @return Number of components deployed.
     * 
     */
    public Output<Integer> componentCount() {
        return this.componentCount;
    }
    /**
     * Names of all components deployed as part of this stack, in topological order.
     * 
     */
    @Export(name="deployedComponents", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> deployedComponents;

    /**
     * @return Names of all components deployed as part of this stack, in topological order.
     * 
     */
    public Output<List<String>> deployedComponents() {
        return this.deployedComponents;
    }
    /**
     * The resolved AICR recipe name (e.g., &#34;h100-eks-ubuntu-training-kubeflow&#34;).
     * 
     */
    @Export(name="recipeName", refs={String.class}, tree="[0]")
    private Output<String> recipeName;

    /**
     * @return The resolved AICR recipe name (e.g., &#34;h100-eks-ubuntu-training-kubeflow&#34;).
     * 
     */
    public Output<String> recipeName() {
        return this.recipeName;
    }
    /**
     * The AICR recipe data version embedded in this provider build.
     * 
     */
    @Export(name="recipeVersion", refs={String.class}, tree="[0]")
    private Output<String> recipeVersion;

    /**
     * @return The AICR recipe data version embedded in this provider build.
     * 
     */
    public Output<String> recipeVersion() {
        return this.recipeVersion;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ClusterStack(java.lang.String name) {
        this(name, ClusterStackArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ClusterStack(java.lang.String name, ClusterStackArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ClusterStack(java.lang.String name, ClusterStackArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        super("nvidia-aicr:index:ClusterStack", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), true);
    }

    private static ClusterStackArgs makeArgs(ClusterStackArgs args, @Nullable com.pulumi.resources.ComponentResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ClusterStackArgs.Empty : args;
    }

    private static com.pulumi.resources.ComponentResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.ComponentResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.ComponentResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.ComponentResourceOptions.merge(defaultOptions, options, id);
    }

}
