// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nvidiaaicr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.nvidiaaicr.inputs.ComponentOverrideArgs;
import java.lang.Boolean;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ClusterStackArgs extends com.pulumi.resources.ResourceArgs {

    public static final ClusterStackArgs Empty = new ClusterStackArgs();

    /**
     * GPU accelerator type. Selects the AICR recipe family.
     * 
     * Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
     * 
     */
    @Import(name="accelerator", required=true)
    private String accelerator;

    /**
     * @return GPU accelerator type. Selects the AICR recipe family.
     * 
     * Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
     * 
     */
    public String accelerator() {
        return this.accelerator;
    }

    /**
     * Per-component overrides. Map of AICR component name to override settings
     * (version, namespace, Helm values). Values are deep-merged with the recipe
     * defaults; only the keys you specify are changed.
     * 
     */
    @Import(name="componentOverrides")
    private @Nullable Output<Map<String,ComponentOverrideArgs>> componentOverrides;

    /**
     * @return Per-component overrides. Map of AICR component name to override settings
     * (version, namespace, Helm values). Values are deep-merged with the recipe
     * defaults; only the keys you specify are changed.
     * 
     */
    public Optional<Output<Map<String,ComponentOverrideArgs>>> componentOverrides() {
        return Optional.ofNullable(this.componentOverrides);
    }

    /**
     * Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
     * 
     */
    @Import(name="context")
    private @Nullable String context;

    /**
     * @return Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
     * 
     */
    public Optional<String> context() {
        return Optional.ofNullable(this.context);
    }

    /**
     * Workload intent. Selects between training-oriented and inference-oriented
     * component sets.
     * 
     * Supported values: &#34;training&#34;, &#34;inference&#34;.
     * 
     */
    @Import(name="intent", required=true)
    private String intent;

    /**
     * @return Workload intent. Selects between training-oriented and inference-oriented
     * component sets.
     * 
     * Supported values: &#34;training&#34;, &#34;inference&#34;.
     * 
     */
    public String intent() {
        return this.intent;
    }

    /**
     * Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
     * Accepts computed outputs from cluster resources (e.g., an EKS cluster&#39;s
     * KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
     * 
     * If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
     * (KUBECONFIG env var or ~/.kube/config) is used.
     * 
     */
    @Import(name="kubeconfig")
    private @Nullable Output<String> kubeconfig;

    /**
     * @return Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
     * Accepts computed outputs from cluster resources (e.g., an EKS cluster&#39;s
     * KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
     * 
     * If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
     * (KUBECONFIG env var or ~/.kube/config) is used.
     * 
     */
    public Optional<Output<String>> kubeconfig() {
        return Optional.ofNullable(this.kubeconfig);
    }

    /**
     * Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * Prefer `kubeconfig` when chaining off a cluster resource&#39;s output.
     * 
     */
    @Import(name="kubeconfigPath")
    private @Nullable String kubeconfigPath;

    /**
     * @return Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * Prefer `kubeconfig` when chaining off a cluster resource&#39;s output.
     * 
     */
    public Optional<String> kubeconfigPath() {
        return Optional.ofNullable(this.kubeconfigPath);
    }

    /**
     * Operating system flavor.
     * 
     * Supported values: &#34;ubuntu&#34; (default), &#34;cos&#34; (Container-Optimized OS, GKE only).
     * 
     */
    @Import(name="os")
    private @Nullable String os;

    /**
     * @return Operating system flavor.
     * 
     * Supported values: &#34;ubuntu&#34; (default), &#34;cos&#34; (Container-Optimized OS, GKE only).
     * 
     */
    public Optional<String> os() {
        return Optional.ofNullable(this.os);
    }

    /**
     * ML platform/framework to layer on top of the base recipe.
     * 
     * Supported values: &#34;kubeflow&#34; (training), &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
     * Leave unset for a base recipe with no platform components.
     * 
     */
    @Import(name="platform")
    private @Nullable String platform;

    /**
     * @return ML platform/framework to layer on top of the base recipe.
     * 
     * Supported values: &#34;kubeflow&#34; (training), &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
     * Leave unset for a base recipe with no platform components.
     * 
     */
    public Optional<String> platform() {
        return Optional.ofNullable(this.platform);
    }

    /**
     * Kubernetes service. Selects cloud-specific operators and storage drivers.
     * 
     * Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;. Use &#34;kind&#34; for local
     * hardware-free development of the deployment pipeline.
     * 
     */
    @Import(name="service", required=true)
    private String service;

    /**
     * @return Kubernetes service. Selects cloud-specific operators and storage drivers.
     * 
     * Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;. Use &#34;kind&#34; for local
     * hardware-free development of the deployment pipeline.
     * 
     */
    public String service() {
        return this.service;
    }

    /**
     * If true, do not wait for each Helm release to become ready before continuing.
     * Faster previews/updates at the cost of losing readiness signal. Default: false.
     * 
     */
    @Import(name="skipAwait")
    private @Nullable Boolean skipAwait;

    /**
     * @return If true, do not wait for each Helm release to become ready before continuing.
     * Faster previews/updates at the cost of losing readiness signal. Default: false.
     * 
     */
    public Optional<Boolean> skipAwait() {
        return Optional.ofNullable(this.skipAwait);
    }

    /**
     * Component names to exclude from the deployment. Useful for swapping in your
     * own installation of a component (e.g., bring-your-own cert-manager) or for
     * deploying onto bare-metal where cloud-specific operators are not relevant.
     * 
     */
    @Import(name="skipComponents")
    private @Nullable Output<List<String>> skipComponents;

    /**
     * @return Component names to exclude from the deployment. Useful for swapping in your
     * own installation of a component (e.g., bring-your-own cert-manager) or for
     * deploying onto bare-metal where cloud-specific operators are not relevant.
     * 
     */
    public Optional<Output<List<String>>> skipComponents() {
        return Optional.ofNullable(this.skipComponents);
    }

    private ClusterStackArgs() {}

    private ClusterStackArgs(ClusterStackArgs $) {
        this.accelerator = $.accelerator;
        this.componentOverrides = $.componentOverrides;
        this.context = $.context;
        this.intent = $.intent;
        this.kubeconfig = $.kubeconfig;
        this.kubeconfigPath = $.kubeconfigPath;
        this.os = $.os;
        this.platform = $.platform;
        this.service = $.service;
        this.skipAwait = $.skipAwait;
        this.skipComponents = $.skipComponents;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ClusterStackArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ClusterStackArgs $;

        public Builder() {
            $ = new ClusterStackArgs();
        }

        public Builder(ClusterStackArgs defaults) {
            $ = new ClusterStackArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accelerator GPU accelerator type. Selects the AICR recipe family.
         * 
         * Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
         * 
         * @return builder
         * 
         */
        public Builder accelerator(String accelerator) {
            $.accelerator = accelerator;
            return this;
        }

        /**
         * @param componentOverrides Per-component overrides. Map of AICR component name to override settings
         * (version, namespace, Helm values). Values are deep-merged with the recipe
         * defaults; only the keys you specify are changed.
         * 
         * @return builder
         * 
         */
        public Builder componentOverrides(@Nullable Output<Map<String,ComponentOverrideArgs>> componentOverrides) {
            $.componentOverrides = componentOverrides;
            return this;
        }

        /**
         * @param componentOverrides Per-component overrides. Map of AICR component name to override settings
         * (version, namespace, Helm values). Values are deep-merged with the recipe
         * defaults; only the keys you specify are changed.
         * 
         * @return builder
         * 
         */
        public Builder componentOverrides(Map<String,ComponentOverrideArgs> componentOverrides) {
            return componentOverrides(Output.of(componentOverrides));
        }

        /**
         * @param context Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
         * 
         * @return builder
         * 
         */
        public Builder context(@Nullable String context) {
            $.context = context;
            return this;
        }

        /**
         * @param intent Workload intent. Selects between training-oriented and inference-oriented
         * component sets.
         * 
         * Supported values: &#34;training&#34;, &#34;inference&#34;.
         * 
         * @return builder
         * 
         */
        public Builder intent(String intent) {
            $.intent = intent;
            return this;
        }

        /**
         * @param kubeconfig Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
         * Accepts computed outputs from cluster resources (e.g., an EKS cluster&#39;s
         * KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
         * 
         * If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
         * (KUBECONFIG env var or ~/.kube/config) is used.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfig(@Nullable Output<String> kubeconfig) {
            $.kubeconfig = kubeconfig;
            return this;
        }

        /**
         * @param kubeconfig Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
         * Accepts computed outputs from cluster resources (e.g., an EKS cluster&#39;s
         * KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
         * 
         * If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
         * (KUBECONFIG env var or ~/.kube/config) is used.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfig(String kubeconfig) {
            return kubeconfig(Output.of(kubeconfig));
        }

        /**
         * @param kubeconfigPath Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
         * Prefer `kubeconfig` when chaining off a cluster resource&#39;s output.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfigPath(@Nullable String kubeconfigPath) {
            $.kubeconfigPath = kubeconfigPath;
            return this;
        }

        /**
         * @param os Operating system flavor.
         * 
         * Supported values: &#34;ubuntu&#34; (default), &#34;cos&#34; (Container-Optimized OS, GKE only).
         * 
         * @return builder
         * 
         */
        public Builder os(@Nullable String os) {
            $.os = os;
            return this;
        }

        /**
         * @param platform ML platform/framework to layer on top of the base recipe.
         * 
         * Supported values: &#34;kubeflow&#34; (training), &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
         * Leave unset for a base recipe with no platform components.
         * 
         * @return builder
         * 
         */
        public Builder platform(@Nullable String platform) {
            $.platform = platform;
            return this;
        }

        /**
         * @param service Kubernetes service. Selects cloud-specific operators and storage drivers.
         * 
         * Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;. Use &#34;kind&#34; for local
         * hardware-free development of the deployment pipeline.
         * 
         * @return builder
         * 
         */
        public Builder service(String service) {
            $.service = service;
            return this;
        }

        /**
         * @param skipAwait If true, do not wait for each Helm release to become ready before continuing.
         * Faster previews/updates at the cost of losing readiness signal. Default: false.
         * 
         * @return builder
         * 
         */
        public Builder skipAwait(@Nullable Boolean skipAwait) {
            $.skipAwait = skipAwait;
            return this;
        }

        /**
         * @param skipComponents Component names to exclude from the deployment. Useful for swapping in your
         * own installation of a component (e.g., bring-your-own cert-manager) or for
         * deploying onto bare-metal where cloud-specific operators are not relevant.
         * 
         * @return builder
         * 
         */
        public Builder skipComponents(@Nullable Output<List<String>> skipComponents) {
            $.skipComponents = skipComponents;
            return this;
        }

        /**
         * @param skipComponents Component names to exclude from the deployment. Useful for swapping in your
         * own installation of a component (e.g., bring-your-own cert-manager) or for
         * deploying onto bare-metal where cloud-specific operators are not relevant.
         * 
         * @return builder
         * 
         */
        public Builder skipComponents(List<String> skipComponents) {
            return skipComponents(Output.of(skipComponents));
        }

        /**
         * @param skipComponents Component names to exclude from the deployment. Useful for swapping in your
         * own installation of a component (e.g., bring-your-own cert-manager) or for
         * deploying onto bare-metal where cloud-specific operators are not relevant.
         * 
         * @return builder
         * 
         */
        public Builder skipComponents(String... skipComponents) {
            return skipComponents(List.of(skipComponents));
        }

        public ClusterStackArgs build() {
            if ($.accelerator == null) {
                throw new MissingRequiredPropertyException("ClusterStackArgs", "accelerator");
            }
            if ($.intent == null) {
                throw new MissingRequiredPropertyException("ClusterStackArgs", "intent");
            }
            $.os = Codegen.stringProp("os").arg($.os).def("ubuntu").getNullable();
            if ($.service == null) {
                throw new MissingRequiredPropertyException("ClusterStackArgs", "service");
            }
            $.skipAwait = Codegen.booleanProp("skipAwait").arg($.skipAwait).def(false).getNullable();
            return $;
        }
    }

}
