# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .cluster_stack import *
from .provider import *
from .validation_run import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "nvidia-aicr",
  "mod": "index",
  "fqn": "pulumi_labs_nvidia_aicr",
  "classes": {
   "nvidia-aicr:index:ClusterStack": "ClusterStack",
   "nvidia-aicr:index:ValidationRun": "ValidationRun"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "nvidia-aicr",
  "token": "pulumi:providers:nvidia-aicr",
  "fqn": "pulumi_labs_nvidia_aicr",
  "class": "Provider"
 }
]
"""
)
