# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'CheckResult',
    'RecipeCriteria',
    'Toleration',
]

@pulumi.output_type
class CheckResult(dict):
    """
    The outcome of one validator check.
    """
    def __init__(__self__, *,
                 message: _builtins.str,
                 name: _builtins.str,
                 phase: _builtins.str,
                 status: _builtins.str):
        """
        The outcome of one validator check.

        :param _builtins.str message: The check's failure or diagnostic message, if any.
        :param _builtins.str name: The check's name (e.g. "gpu-operator-health").
        :param _builtins.str phase: The validation phase the check ran in.
        :param _builtins.str status: The check's status: "passed", "failed", "skipped", "pending", or "other".
        """
        pulumi.set(__self__, "message", message)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "phase", phase)
        pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter
    def message(self) -> _builtins.str:
        """
        The check's failure or diagnostic message, if any.
        """
        return pulumi.get(self, "message")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The check's name (e.g. "gpu-operator-health").
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def phase(self) -> _builtins.str:
        """
        The validation phase the check ran in.
        """
        return pulumi.get(self, "phase")

    @_builtins.property
    @pulumi.getter
    def status(self) -> _builtins.str:
        """
        The check's status: "passed", "failed", "skipped", "pending", or "other".
        """
        return pulumi.get(self, "status")


@pulumi.output_type
class RecipeCriteria(dict):
    """
    Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
    intent / os / platform / nodes inputs. Wire a ClusterStack's `criteria`
    output here so deployment and validation resolve the identical recipe.
    """
    def __init__(__self__, *,
                 accelerator: _builtins.str,
                 intent: _builtins.str,
                 service: _builtins.str,
                 nodes: Optional[_builtins.int] = None,
                 os: Optional[_builtins.str] = None,
                 platform: Optional[_builtins.str] = None):
        """
        Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
        intent / os / platform / nodes inputs. Wire a ClusterStack's `criteria`
        output here so deployment and validation resolve the identical recipe.

        :param _builtins.str accelerator: GPU accelerator type. Supported values: "h100", "gb200", "b200".
        :param _builtins.str intent: Workload intent. Supported values: "training", "inference".
        :param _builtins.str service: Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
        :param _builtins.int nodes: Worker-node count hint used to size the recipe.
        :param _builtins.str os: Operating system flavor of the worker nodes. Leave unset for OS-agnostic
               resolution. Supported values: "ubuntu", "cos", "ol".
        :param _builtins.str platform: ML platform/framework. Supported values: "kubeflow" (training),
               "dynamo" (inference), "nim" (inference, EKS+H100 only).
        """
        pulumi.set(__self__, "accelerator", accelerator)
        pulumi.set(__self__, "intent", intent)
        pulumi.set(__self__, "service", service)
        if nodes is not None:
            pulumi.set(__self__, "nodes", nodes)
        if os is not None:
            pulumi.set(__self__, "os", os)
        if platform is not None:
            pulumi.set(__self__, "platform", platform)

    @_builtins.property
    @pulumi.getter
    def accelerator(self) -> _builtins.str:
        """
        GPU accelerator type. Supported values: "h100", "gb200", "b200".
        """
        return pulumi.get(self, "accelerator")

    @_builtins.property
    @pulumi.getter
    def intent(self) -> _builtins.str:
        """
        Workload intent. Supported values: "training", "inference".
        """
        return pulumi.get(self, "intent")

    @_builtins.property
    @pulumi.getter
    def service(self) -> _builtins.str:
        """
        Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
        """
        return pulumi.get(self, "service")

    @_builtins.property
    @pulumi.getter
    def nodes(self) -> Optional[_builtins.int]:
        """
        Worker-node count hint used to size the recipe.
        """
        return pulumi.get(self, "nodes")

    @_builtins.property
    @pulumi.getter
    def os(self) -> Optional[_builtins.str]:
        """
        Operating system flavor of the worker nodes. Leave unset for OS-agnostic
        resolution. Supported values: "ubuntu", "cos", "ol".
        """
        return pulumi.get(self, "os")

    @_builtins.property
    @pulumi.getter
    def platform(self) -> Optional[_builtins.str]:
        """
        ML platform/framework. Supported values: "kubeflow" (training),
        "dynamo" (inference), "nim" (inference, EKS+H100 only).
        """
        return pulumi.get(self, "platform")


@pulumi.output_type
class Toleration(dict):
    """
    A Kubernetes pod toleration applied to validation workload pods.
    """
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "tolerationSeconds":
            suggest = "toleration_seconds"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in Toleration. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        Toleration.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        Toleration.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 effect: Optional[_builtins.str] = None,
                 key: Optional[_builtins.str] = None,
                 operator: Optional[_builtins.str] = None,
                 toleration_seconds: Optional[_builtins.int] = None,
                 value: Optional[_builtins.str] = None):
        """
        A Kubernetes pod toleration applied to validation workload pods.

        :param _builtins.str effect: The taint effect to match: "NoSchedule", "PreferNoSchedule", or
               "NoExecute". Empty matches all effects.
        :param _builtins.str key: The taint key the toleration applies to. Empty means match all keys
               (with operator "Exists").
        :param _builtins.str operator: Key-value relationship: "Exists" or "Equal". Default: "Equal".
        :param _builtins.int toleration_seconds: How long the pod tolerates a "NoExecute" taint, in seconds.
        :param _builtins.str value: The taint value to match (with operator "Equal").
        """
        if effect is not None:
            pulumi.set(__self__, "effect", effect)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if operator is not None:
            pulumi.set(__self__, "operator", operator)
        if toleration_seconds is not None:
            pulumi.set(__self__, "toleration_seconds", toleration_seconds)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def effect(self) -> Optional[_builtins.str]:
        """
        The taint effect to match: "NoSchedule", "PreferNoSchedule", or
        "NoExecute". Empty matches all effects.
        """
        return pulumi.get(self, "effect")

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[_builtins.str]:
        """
        The taint key the toleration applies to. Empty means match all keys
        (with operator "Exists").
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def operator(self) -> Optional[_builtins.str]:
        """
        Key-value relationship: "Exists" or "Equal". Default: "Equal".
        """
        return pulumi.get(self, "operator")

    @_builtins.property
    @pulumi.getter(name="tolerationSeconds")
    def toleration_seconds(self) -> Optional[_builtins.int]:
        """
        How long the pod tolerates a "NoExecute" taint, in seconds.
        """
        return pulumi.get(self, "toleration_seconds")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        The taint value to match (with operator "Equal").
        """
        return pulumi.get(self, "value")


