# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ValidationRunArgs', 'ValidationRun']

@pulumi.input_type
class ValidationRunArgs:
    def __init__(__self__, *,
                 criteria: pulumi.Input['RecipeCriteriaArgs'],
                 context: pulumi.Input[Optional[_builtins.str]] = None,
                 image_pull_secrets: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 image_registry: pulumi.Input[Optional[_builtins.str]] = None,
                 include_ctrf_report: pulumi.Input[Optional[_builtins.bool]] = None,
                 kubeconfig: pulumi.Input[Optional[_builtins.str]] = None,
                 kubeconfig_path: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 node_selector: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 phases: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 recipe_data_version: pulumi.Input[Optional[_builtins.str]] = None,
                 require_gpu: pulumi.Input[Optional[_builtins.bool]] = None,
                 strict: pulumi.Input[Optional[_builtins.bool]] = None,
                 timeout_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 tolerations: pulumi.Input[Optional[Sequence[pulumi.Input['TolerationArgs']]]] = None,
                 triggers: pulumi.Input[Optional[Sequence[Any]]] = None):
        """
        The set of arguments for constructing a ValidationRun resource.

        :param pulumi.Input['RecipeCriteriaArgs'] criteria: Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
               the object inline.
        :param pulumi.Input[_builtins.str] context: Kubeconfig context to select. Defaults to the kubeconfig's current-context.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] image_pull_secrets: Names of image pull Secrets (in the validation namespace) for the
               validation pods.
        :param pulumi.Input[_builtins.str] image_registry: Registry override for the snapshot-agent and validator images (air-gapped
               mirrors). Unset keeps the default registry (ghcr.io).
        :param pulumi.Input[_builtins.bool] include_ctrf_report: If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
               Default: false (state-size control; per-check results are always in
               `phaseResults`).
        :param pulumi.Input[_builtins.str] kubeconfig: Kubeconfig contents for the target cluster. Mutually exclusive with
               `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
               var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
               duration of the run and removed afterward.
        :param pulumi.Input[_builtins.str] kubeconfig_path: Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        :param pulumi.Input[_builtins.str] namespace: Namespace for the validation harness — use a dedicated one: it hosts the
               privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
               on first run and deliberately never deletes it. Must be a valid DNS-1123
               label and not a "kube-" system namespace. Default: "aicr-validation".
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] node_selector: Node selector applied to the validation workload pods. Use when GPU nodes
               carry non-standard labels.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] phases: Validation phases to run: any of "deployment", "conformance",
               "performance". Default: ["deployment", "conformance"] — "performance" is an
               explicit opt-in (long-running and hardware-bound).
        :param pulumi.Input[_builtins.str] recipe_data_version: Recipe-data version assertion (not a pin). When set, it must equal this
               provider build's embedded AICR recipe-data version or Create fails before
               any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
               provider upgrade between deploy and validate.
        :param pulumi.Input[_builtins.bool] require_gpu: Whether the snapshot agent requires GPU nodes. Set false for
               hardware-free clusters (kind). Default: true.
        :param pulumi.Input[_builtins.bool] strict: If true, a failed (or readiness-failed) validation fails the update while
               still persisting the full results in state. The engine then re-runs
               validation on every subsequent `pulumi up` until it passes. Default: false —
               results are recorded and the update succeeds; read the `status` output.
        :param pulumi.Input[_builtins.int] timeout_minutes: Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
        :param pulumi.Input[Sequence[pulumi.Input['TolerationArgs']]] tolerations: Tolerations applied to the validation workload pods (e.g. NCCL benchmark
               pods). Required in practice on tainted GPU node groups; when unset, the
               validator's default tolerate-all is kept.
        :param pulumi.Input[Sequence[Any]] triggers: Arbitrary values; changing any of them replaces the resource and re-runs
               validation (every input change does). Wire `triggers: [stack.deployedComponents]`
               for re-validation cadence.
        """
        pulumi.set(__self__, "criteria", criteria)
        if context is not None:
            pulumi.set(__self__, "context", context)
        if image_pull_secrets is not None:
            pulumi.set(__self__, "image_pull_secrets", image_pull_secrets)
        if image_registry is not None:
            pulumi.set(__self__, "image_registry", image_registry)
        if include_ctrf_report is None:
            include_ctrf_report = False
        if include_ctrf_report is not None:
            pulumi.set(__self__, "include_ctrf_report", include_ctrf_report)
        if kubeconfig is not None:
            pulumi.set(__self__, "kubeconfig", kubeconfig)
        if kubeconfig_path is not None:
            pulumi.set(__self__, "kubeconfig_path", kubeconfig_path)
        if namespace is None:
            namespace = 'aicr-validation'
        if namespace is not None:
            pulumi.set(__self__, "namespace", namespace)
        if node_selector is not None:
            pulumi.set(__self__, "node_selector", node_selector)
        if phases is not None:
            pulumi.set(__self__, "phases", phases)
        if recipe_data_version is not None:
            pulumi.set(__self__, "recipe_data_version", recipe_data_version)
        if require_gpu is None:
            require_gpu = True
        if require_gpu is not None:
            pulumi.set(__self__, "require_gpu", require_gpu)
        if strict is None:
            strict = False
        if strict is not None:
            pulumi.set(__self__, "strict", strict)
        if timeout_minutes is None:
            timeout_minutes = 30
        if timeout_minutes is not None:
            pulumi.set(__self__, "timeout_minutes", timeout_minutes)
        if tolerations is not None:
            pulumi.set(__self__, "tolerations", tolerations)
        if triggers is not None:
            pulumi.set(__self__, "triggers", triggers)

    @_builtins.property
    @pulumi.getter
    def criteria(self) -> pulumi.Input['RecipeCriteriaArgs']:
        """
        Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
        the object inline.
        """
        return pulumi.get(self, "criteria")

    @criteria.setter
    def criteria(self, value: pulumi.Input['RecipeCriteriaArgs']):
        pulumi.set(self, "criteria", value)

    @_builtins.property
    @pulumi.getter
    def context(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kubeconfig context to select. Defaults to the kubeconfig's current-context.
        """
        return pulumi.get(self, "context")

    @context.setter
    def context(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "context", value)

    @_builtins.property
    @pulumi.getter(name="imagePullSecrets")
    def image_pull_secrets(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Names of image pull Secrets (in the validation namespace) for the
        validation pods.
        """
        return pulumi.get(self, "image_pull_secrets")

    @image_pull_secrets.setter
    def image_pull_secrets(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "image_pull_secrets", value)

    @_builtins.property
    @pulumi.getter(name="imageRegistry")
    def image_registry(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Registry override for the snapshot-agent and validator images (air-gapped
        mirrors). Unset keeps the default registry (ghcr.io).
        """
        return pulumi.get(self, "image_registry")

    @image_registry.setter
    def image_registry(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "image_registry", value)

    @_builtins.property
    @pulumi.getter(name="includeCtrfReport")
    def include_ctrf_report(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
        Default: false (state-size control; per-check results are always in
        `phaseResults`).
        """
        return pulumi.get(self, "include_ctrf_report")

    @include_ctrf_report.setter
    def include_ctrf_report(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "include_ctrf_report", value)

    @_builtins.property
    @pulumi.getter
    def kubeconfig(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Kubeconfig contents for the target cluster. Mutually exclusive with
        `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
        var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
        duration of the run and removed afterward.
        """
        return pulumi.get(self, "kubeconfig")

    @kubeconfig.setter
    def kubeconfig(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kubeconfig", value)

    @_builtins.property
    @pulumi.getter(name="kubeconfigPath")
    def kubeconfig_path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        """
        return pulumi.get(self, "kubeconfig_path")

    @kubeconfig_path.setter
    def kubeconfig_path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "kubeconfig_path", value)

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Namespace for the validation harness — use a dedicated one: it hosts the
        privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
        on first run and deliberately never deletes it. Must be a valid DNS-1123
        label and not a "kube-" system namespace. Default: "aicr-validation".
        """
        return pulumi.get(self, "namespace")

    @namespace.setter
    def namespace(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "namespace", value)

    @_builtins.property
    @pulumi.getter(name="nodeSelector")
    def node_selector(self) -> pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Node selector applied to the validation workload pods. Use when GPU nodes
        carry non-standard labels.
        """
        return pulumi.get(self, "node_selector")

    @node_selector.setter
    def node_selector(self, value: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "node_selector", value)

    @_builtins.property
    @pulumi.getter
    def phases(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Validation phases to run: any of "deployment", "conformance",
        "performance". Default: ["deployment", "conformance"] — "performance" is an
        explicit opt-in (long-running and hardware-bound).
        """
        return pulumi.get(self, "phases")

    @phases.setter
    def phases(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "phases", value)

    @_builtins.property
    @pulumi.getter(name="recipeDataVersion")
    def recipe_data_version(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Recipe-data version assertion (not a pin). When set, it must equal this
        provider build's embedded AICR recipe-data version or Create fails before
        any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
        provider upgrade between deploy and validate.
        """
        return pulumi.get(self, "recipe_data_version")

    @recipe_data_version.setter
    def recipe_data_version(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "recipe_data_version", value)

    @_builtins.property
    @pulumi.getter(name="requireGpu")
    def require_gpu(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the snapshot agent requires GPU nodes. Set false for
        hardware-free clusters (kind). Default: true.
        """
        return pulumi.get(self, "require_gpu")

    @require_gpu.setter
    def require_gpu(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "require_gpu", value)

    @_builtins.property
    @pulumi.getter
    def strict(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        If true, a failed (or readiness-failed) validation fails the update while
        still persisting the full results in state. The engine then re-runs
        validation on every subsequent `pulumi up` until it passes. Default: false —
        results are recorded and the update succeeds; read the `status` output.
        """
        return pulumi.get(self, "strict")

    @strict.setter
    def strict(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "strict", value)

    @_builtins.property
    @pulumi.getter(name="timeoutMinutes")
    def timeout_minutes(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
        """
        return pulumi.get(self, "timeout_minutes")

    @timeout_minutes.setter
    def timeout_minutes(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "timeout_minutes", value)

    @_builtins.property
    @pulumi.getter
    def tolerations(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['TolerationArgs']]]]:
        """
        Tolerations applied to the validation workload pods (e.g. NCCL benchmark
        pods). Required in practice on tainted GPU node groups; when unset, the
        validator's default tolerate-all is kept.
        """
        return pulumi.get(self, "tolerations")

    @tolerations.setter
    def tolerations(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['TolerationArgs']]]]):
        pulumi.set(self, "tolerations", value)

    @_builtins.property
    @pulumi.getter
    def triggers(self) -> pulumi.Input[Optional[Sequence[Any]]]:
        """
        Arbitrary values; changing any of them replaces the resource and re-runs
        validation (every input change does). Wire `triggers: [stack.deployedComponents]`
        for re-validation cadence.
        """
        return pulumi.get(self, "triggers")

    @triggers.setter
    def triggers(self, value: pulumi.Input[Optional[Sequence[Any]]]):
        pulumi.set(self, "triggers", value)


@pulumi.type_token("nvidia-aicr:index:ValidationRun")
class ValidationRun(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 context: pulumi.Input[Optional[_builtins.str]] = None,
                 criteria: pulumi.Input[Optional[Union['RecipeCriteriaArgs', 'RecipeCriteriaArgsDict']]] = None,
                 image_pull_secrets: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 image_registry: pulumi.Input[Optional[_builtins.str]] = None,
                 include_ctrf_report: pulumi.Input[Optional[_builtins.bool]] = None,
                 kubeconfig: pulumi.Input[Optional[_builtins.str]] = None,
                 kubeconfig_path: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 node_selector: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 phases: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 recipe_data_version: pulumi.Input[Optional[_builtins.str]] = None,
                 require_gpu: pulumi.Input[Optional[_builtins.bool]] = None,
                 strict: pulumi.Input[Optional[_builtins.bool]] = None,
                 timeout_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 tolerations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['TolerationArgs', 'TolerationArgsDict']]]]] = None,
                 triggers: pulumi.Input[Optional[Sequence[Any]]] = None,
                 __props__=None):
        """
        Runs an AICR recipe's empirical validation (cluster snapshot +
        deployment/conformance/performance checks) against a live cluster and
        records structured per-check results in Pulumi state.

        The run happens at deploy time (never at preview). The validation harness
        deploys short-lived agent and validator Jobs plus per-run RBAC on the target
        cluster and cleans them up afterward; the validation namespace (default
        "aicr-validation") is created on first run and deliberately persists.

        Privilege level: the snapshot-agent Job runs as a privileged container
        (bound to a read-only node-inspection ClusterRole), and validator Jobs run
        under a per-run cluster-admin ClusterRoleBinding — both removed after the
        run, including on cancellation. The kubeconfig identity needs RBAC to
        create/patch Namespaces, ClusterRoles, and ClusterRoleBindings.

        Any input change replaces the resource, which re-runs validation (delete is
        a no-op). With `strict: true`, a failed run fails the update while persisting
        full results, and validation re-runs on every subsequent `pulumi up` until it
        passes — use `dependsOn` to gate downstream resources on it.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] context: Kubeconfig context to select. Defaults to the kubeconfig's current-context.
        :param pulumi.Input[Union['RecipeCriteriaArgs', 'RecipeCriteriaArgsDict']] criteria: Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
               the object inline.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] image_pull_secrets: Names of image pull Secrets (in the validation namespace) for the
               validation pods.
        :param pulumi.Input[_builtins.str] image_registry: Registry override for the snapshot-agent and validator images (air-gapped
               mirrors). Unset keeps the default registry (ghcr.io).
        :param pulumi.Input[_builtins.bool] include_ctrf_report: If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
               Default: false (state-size control; per-check results are always in
               `phaseResults`).
        :param pulumi.Input[_builtins.str] kubeconfig: Kubeconfig contents for the target cluster. Mutually exclusive with
               `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
               var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
               duration of the run and removed afterward.
        :param pulumi.Input[_builtins.str] kubeconfig_path: Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        :param pulumi.Input[_builtins.str] namespace: Namespace for the validation harness — use a dedicated one: it hosts the
               privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
               on first run and deliberately never deletes it. Must be a valid DNS-1123
               label and not a "kube-" system namespace. Default: "aicr-validation".
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] node_selector: Node selector applied to the validation workload pods. Use when GPU nodes
               carry non-standard labels.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] phases: Validation phases to run: any of "deployment", "conformance",
               "performance". Default: ["deployment", "conformance"] — "performance" is an
               explicit opt-in (long-running and hardware-bound).
        :param pulumi.Input[_builtins.str] recipe_data_version: Recipe-data version assertion (not a pin). When set, it must equal this
               provider build's embedded AICR recipe-data version or Create fails before
               any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
               provider upgrade between deploy and validate.
        :param pulumi.Input[_builtins.bool] require_gpu: Whether the snapshot agent requires GPU nodes. Set false for
               hardware-free clusters (kind). Default: true.
        :param pulumi.Input[_builtins.bool] strict: If true, a failed (or readiness-failed) validation fails the update while
               still persisting the full results in state. The engine then re-runs
               validation on every subsequent `pulumi up` until it passes. Default: false —
               results are recorded and the update succeeds; read the `status` output.
        :param pulumi.Input[_builtins.int] timeout_minutes: Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
        :param pulumi.Input[Sequence[pulumi.Input[Union['TolerationArgs', 'TolerationArgsDict']]]] tolerations: Tolerations applied to the validation workload pods (e.g. NCCL benchmark
               pods). Required in practice on tainted GPU node groups; when unset, the
               validator's default tolerate-all is kept.
        :param pulumi.Input[Sequence[Any]] triggers: Arbitrary values; changing any of them replaces the resource and re-runs
               validation (every input change does). Wire `triggers: [stack.deployedComponents]`
               for re-validation cadence.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ValidationRunArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Runs an AICR recipe's empirical validation (cluster snapshot +
        deployment/conformance/performance checks) against a live cluster and
        records structured per-check results in Pulumi state.

        The run happens at deploy time (never at preview). The validation harness
        deploys short-lived agent and validator Jobs plus per-run RBAC on the target
        cluster and cleans them up afterward; the validation namespace (default
        "aicr-validation") is created on first run and deliberately persists.

        Privilege level: the snapshot-agent Job runs as a privileged container
        (bound to a read-only node-inspection ClusterRole), and validator Jobs run
        under a per-run cluster-admin ClusterRoleBinding — both removed after the
        run, including on cancellation. The kubeconfig identity needs RBAC to
        create/patch Namespaces, ClusterRoles, and ClusterRoleBindings.

        Any input change replaces the resource, which re-runs validation (delete is
        a no-op). With `strict: true`, a failed run fails the update while persisting
        full results, and validation re-runs on every subsequent `pulumi up` until it
        passes — use `dependsOn` to gate downstream resources on it.


        :param str resource_name: The name of the resource.
        :param ValidationRunArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ValidationRunArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 context: pulumi.Input[Optional[_builtins.str]] = None,
                 criteria: pulumi.Input[Optional[Union['RecipeCriteriaArgs', 'RecipeCriteriaArgsDict']]] = None,
                 image_pull_secrets: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 image_registry: pulumi.Input[Optional[_builtins.str]] = None,
                 include_ctrf_report: pulumi.Input[Optional[_builtins.bool]] = None,
                 kubeconfig: pulumi.Input[Optional[_builtins.str]] = None,
                 kubeconfig_path: pulumi.Input[Optional[_builtins.str]] = None,
                 namespace: pulumi.Input[Optional[_builtins.str]] = None,
                 node_selector: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 phases: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 recipe_data_version: pulumi.Input[Optional[_builtins.str]] = None,
                 require_gpu: pulumi.Input[Optional[_builtins.bool]] = None,
                 strict: pulumi.Input[Optional[_builtins.bool]] = None,
                 timeout_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 tolerations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['TolerationArgs', 'TolerationArgsDict']]]]] = None,
                 triggers: pulumi.Input[Optional[Sequence[Any]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ValidationRunArgs.__new__(ValidationRunArgs)

            __props__.__dict__["context"] = context
            if criteria is None and not opts.urn:
                raise TypeError("Missing required property 'criteria'")
            __props__.__dict__["criteria"] = criteria
            __props__.__dict__["image_pull_secrets"] = image_pull_secrets
            __props__.__dict__["image_registry"] = image_registry
            if include_ctrf_report is None:
                include_ctrf_report = False
            __props__.__dict__["include_ctrf_report"] = include_ctrf_report
            __props__.__dict__["kubeconfig"] = None if kubeconfig is None else pulumi.Output.secret(kubeconfig)
            __props__.__dict__["kubeconfig_path"] = kubeconfig_path
            if namespace is None:
                namespace = 'aicr-validation'
            __props__.__dict__["namespace"] = namespace
            __props__.__dict__["node_selector"] = node_selector
            __props__.__dict__["phases"] = phases
            __props__.__dict__["recipe_data_version"] = recipe_data_version
            if require_gpu is None:
                require_gpu = True
            __props__.__dict__["require_gpu"] = require_gpu
            if strict is None:
                strict = False
            __props__.__dict__["strict"] = strict
            if timeout_minutes is None:
                timeout_minutes = 30
            __props__.__dict__["timeout_minutes"] = timeout_minutes
            __props__.__dict__["tolerations"] = tolerations
            __props__.__dict__["triggers"] = triggers
            __props__.__dict__["completed_at"] = None
            __props__.__dict__["ctrf_report"] = None
            __props__.__dict__["failed"] = None
            __props__.__dict__["other"] = None
            __props__.__dict__["passed"] = None
            __props__.__dict__["phase_results"] = None
            __props__.__dict__["readiness_message"] = None
            __props__.__dict__["recipe_name"] = None
            __props__.__dict__["recipe_version"] = None
            __props__.__dict__["run_id"] = None
            __props__.__dict__["skipped"] = None
            __props__.__dict__["status"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["kubeconfig"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ValidationRun, __self__).__init__(
            'nvidia-aicr:index:ValidationRun',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ValidationRun':
        """
        Get an existing ValidationRun resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ValidationRunArgs.__new__(ValidationRunArgs)

        __props__.__dict__["completed_at"] = None
        __props__.__dict__["context"] = None
        __props__.__dict__["criteria"] = None
        __props__.__dict__["ctrf_report"] = None
        __props__.__dict__["failed"] = None
        __props__.__dict__["image_pull_secrets"] = None
        __props__.__dict__["image_registry"] = None
        __props__.__dict__["include_ctrf_report"] = None
        __props__.__dict__["kubeconfig"] = None
        __props__.__dict__["kubeconfig_path"] = None
        __props__.__dict__["namespace"] = None
        __props__.__dict__["node_selector"] = None
        __props__.__dict__["other"] = None
        __props__.__dict__["passed"] = None
        __props__.__dict__["phase_results"] = None
        __props__.__dict__["phases"] = None
        __props__.__dict__["readiness_message"] = None
        __props__.__dict__["recipe_data_version"] = None
        __props__.__dict__["recipe_name"] = None
        __props__.__dict__["recipe_version"] = None
        __props__.__dict__["require_gpu"] = None
        __props__.__dict__["run_id"] = None
        __props__.__dict__["skipped"] = None
        __props__.__dict__["status"] = None
        __props__.__dict__["strict"] = None
        __props__.__dict__["timeout_minutes"] = None
        __props__.__dict__["tolerations"] = None
        __props__.__dict__["triggers"] = None
        return ValidationRun(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="completedAt")
    def completed_at(self) -> pulumi.Output[_builtins.str]:
        """
        When the run completed, RFC 3339.
        """
        return pulumi.get(self, "completed_at")

    @_builtins.property
    @pulumi.getter
    def context(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Kubeconfig context to select. Defaults to the kubeconfig's current-context.
        """
        return pulumi.get(self, "context")

    @_builtins.property
    @pulumi.getter
    def criteria(self) -> pulumi.Output['outputs.RecipeCriteria']:
        """
        Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
        the object inline.
        """
        return pulumi.get(self, "criteria")

    @_builtins.property
    @pulumi.getter(name="ctrfReport")
    def ctrf_report(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
        """
        return pulumi.get(self, "ctrf_report")

    @_builtins.property
    @pulumi.getter
    def failed(self) -> pulumi.Output[_builtins.int]:
        """
        Number of checks that failed.
        """
        return pulumi.get(self, "failed")

    @_builtins.property
    @pulumi.getter(name="imagePullSecrets")
    def image_pull_secrets(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Names of image pull Secrets (in the validation namespace) for the
        validation pods.
        """
        return pulumi.get(self, "image_pull_secrets")

    @_builtins.property
    @pulumi.getter(name="imageRegistry")
    def image_registry(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Registry override for the snapshot-agent and validator images (air-gapped
        mirrors). Unset keeps the default registry (ghcr.io).
        """
        return pulumi.get(self, "image_registry")

    @_builtins.property
    @pulumi.getter(name="includeCtrfReport")
    def include_ctrf_report(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
        Default: false (state-size control; per-check results are always in
        `phaseResults`).
        """
        return pulumi.get(self, "include_ctrf_report")

    @_builtins.property
    @pulumi.getter
    def kubeconfig(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Kubeconfig contents for the target cluster. Mutually exclusive with
        `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
        var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
        duration of the run and removed afterward.
        """
        return pulumi.get(self, "kubeconfig")

    @_builtins.property
    @pulumi.getter(name="kubeconfigPath")
    def kubeconfig_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        """
        return pulumi.get(self, "kubeconfig_path")

    @_builtins.property
    @pulumi.getter
    def namespace(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Namespace for the validation harness — use a dedicated one: it hosts the
        privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
        on first run and deliberately never deletes it. Must be a valid DNS-1123
        label and not a "kube-" system namespace. Default: "aicr-validation".
        """
        return pulumi.get(self, "namespace")

    @_builtins.property
    @pulumi.getter(name="nodeSelector")
    def node_selector(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Node selector applied to the validation workload pods. Use when GPU nodes
        carry non-standard labels.
        """
        return pulumi.get(self, "node_selector")

    @_builtins.property
    @pulumi.getter
    def other(self) -> pulumi.Output[_builtins.int]:
        """
        Number of checks with an inconclusive outcome (crash, OOM, timeout;
        includes CTRF "pending").
        """
        return pulumi.get(self, "other")

    @_builtins.property
    @pulumi.getter
    def passed(self) -> pulumi.Output[_builtins.int]:
        """
        Number of checks that passed.
        """
        return pulumi.get(self, "passed")

    @_builtins.property
    @pulumi.getter(name="phaseResults")
    def phase_results(self) -> pulumi.Output[Sequence['outputs.CheckResult']]:
        """
        Per-check results across all phases run.
        """
        return pulumi.get(self, "phase_results")

    @_builtins.property
    @pulumi.getter
    def phases(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Validation phases to run: any of "deployment", "conformance",
        "performance". Default: ["deployment", "conformance"] — "performance" is an
        explicit opt-in (long-running and hardware-bound).
        """
        return pulumi.get(self, "phases")

    @_builtins.property
    @pulumi.getter(name="readinessMessage")
    def readiness_message(self) -> pulumi.Output[_builtins.str]:
        """
        The readiness pre-flight failure message; empty unless status is
        "readiness-failed".
        """
        return pulumi.get(self, "readiness_message")

    @_builtins.property
    @pulumi.getter(name="recipeDataVersion")
    def recipe_data_version(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Recipe-data version assertion (not a pin). When set, it must equal this
        provider build's embedded AICR recipe-data version or Create fails before
        any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
        provider upgrade between deploy and validate.
        """
        return pulumi.get(self, "recipe_data_version")

    @_builtins.property
    @pulumi.getter(name="recipeName")
    def recipe_name(self) -> pulumi.Output[_builtins.str]:
        """
        The resolved AICR recipe name that was validated.
        """
        return pulumi.get(self, "recipe_name")

    @_builtins.property
    @pulumi.getter(name="recipeVersion")
    def recipe_version(self) -> pulumi.Output[_builtins.str]:
        """
        The AICR recipe data version that was validated.
        """
        return pulumi.get(self, "recipe_version")

    @_builtins.property
    @pulumi.getter(name="requireGpu")
    def require_gpu(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the snapshot agent requires GPU nodes. Set false for
        hardware-free clusters (kind). Default: true.
        """
        return pulumi.get(self, "require_gpu")

    @_builtins.property
    @pulumi.getter(name="runId")
    def run_id(self) -> pulumi.Output[_builtins.str]:
        """
        The run identifier labeling this run's cluster-side artifacts.
        """
        return pulumi.get(self, "run_id")

    @_builtins.property
    @pulumi.getter
    def skipped(self) -> pulumi.Output[_builtins.int]:
        """
        Number of checks that were skipped.
        """
        return pulumi.get(self, "skipped")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[_builtins.str]:
        """
        Rollup verdict: "passed", "failed", or "readiness-failed". Checks with
        status "other" never flip the rollup (they are counted and listed).
        Infrastructure errors have no status — they fail the update outright.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter
    def strict(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        If true, a failed (or readiness-failed) validation fails the update while
        still persisting the full results in state. The engine then re-runs
        validation on every subsequent `pulumi up` until it passes. Default: false —
        results are recorded and the update succeeds; read the `status` output.
        """
        return pulumi.get(self, "strict")

    @_builtins.property
    @pulumi.getter(name="timeoutMinutes")
    def timeout_minutes(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
        """
        return pulumi.get(self, "timeout_minutes")

    @_builtins.property
    @pulumi.getter
    def tolerations(self) -> pulumi.Output[Optional[Sequence['outputs.Toleration']]]:
        """
        Tolerations applied to the validation workload pods (e.g. NCCL benchmark
        pods). Required in practice on tainted GPU node groups; when unset, the
        validator's default tolerate-all is kept.
        """
        return pulumi.get(self, "tolerations")

    @_builtins.property
    @pulumi.getter
    def triggers(self) -> pulumi.Output[Optional[Sequence[Any]]]:
        """
        Arbitrary values; changing any of them replaces the resource and re-runs
        validation (every input change does). Wire `triggers: [stack.deployedComponents]`
        for re-validation cadence.
        """
        return pulumi.get(self, "triggers")

