// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.nvidiaaicr.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Object;
import java.lang.String;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Per-component override settings. Each field is optional; only the fields
 * you set are applied on top of the recipe defaults.
 * 
 */
public final class ComponentOverrideArgs extends com.pulumi.resources.ResourceArgs {

    public static final ComponentOverrideArgs Empty = new ComponentOverrideArgs();

    /**
     * Override the target Kubernetes namespace.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return Override the target Kubernetes namespace.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * Additional or override Helm values, deep-merged with the recipe defaults.
     * 
     */
    @Import(name="values")
    private @Nullable Output<Map<String,Object>> values;

    /**
     * @return Additional or override Helm values, deep-merged with the recipe defaults.
     * 
     */
    public Optional<Output<Map<String,Object>>> values() {
        return Optional.ofNullable(this.values);
    }

    /**
     * Override the Helm chart version. If unset, the recipe-pinned version is used.
     * 
     */
    @Import(name="version")
    private @Nullable Output<String> version;

    /**
     * @return Override the Helm chart version. If unset, the recipe-pinned version is used.
     * 
     */
    public Optional<Output<String>> version() {
        return Optional.ofNullable(this.version);
    }

    private ComponentOverrideArgs() {}

    private ComponentOverrideArgs(ComponentOverrideArgs $) {
        this.namespace = $.namespace;
        this.values = $.values;
        this.version = $.version;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ComponentOverrideArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ComponentOverrideArgs $;

        public Builder() {
            $ = new ComponentOverrideArgs();
        }

        public Builder(ComponentOverrideArgs defaults) {
            $ = new ComponentOverrideArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param namespace Override the target Kubernetes namespace.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace Override the target Kubernetes namespace.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param values Additional or override Helm values, deep-merged with the recipe defaults.
         * 
         * @return builder
         * 
         */
        public Builder values(@Nullable Output<Map<String,Object>> values) {
            $.values = values;
            return this;
        }

        /**
         * @param values Additional or override Helm values, deep-merged with the recipe defaults.
         * 
         * @return builder
         * 
         */
        public Builder values(Map<String,Object> values) {
            return values(Output.of(values));
        }

        /**
         * @param version Override the Helm chart version. If unset, the recipe-pinned version is used.
         * 
         * @return builder
         * 
         */
        public Builder version(@Nullable Output<String> version) {
            $.version = version;
            return this;
        }

        /**
         * @param version Override the Helm chart version. If unset, the recipe-pinned version is used.
         * 
         * @return builder
         * 
         */
        public Builder version(String version) {
            return version(Output.of(version));
        }

        public ComponentOverrideArgs build() {
            return $;
        }
    }

}
