// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * Recipe-selection criteria, mirroring ClusterStack&#39;s accelerator / service /
 * intent / os / platform / nodes inputs. Wire a ClusterStack&#39;s `criteria`
 * output here so deployment and validation resolve the identical recipe.
 * 
 */
public final class RecipeCriteriaArgs extends com.pulumi.resources.ResourceArgs {

    public static final RecipeCriteriaArgs Empty = new RecipeCriteriaArgs();

    /**
     * GPU accelerator type. Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
     * 
     */
    @Import(name="accelerator", required=true)
    private Output<String> accelerator;

    /**
     * @return GPU accelerator type. Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
     * 
     */
    public Output<String> accelerator() {
        return this.accelerator;
    }

    /**
     * Workload intent. Supported values: &#34;training&#34;, &#34;inference&#34;.
     * 
     */
    @Import(name="intent", required=true)
    private Output<String> intent;

    /**
     * @return Workload intent. Supported values: &#34;training&#34;, &#34;inference&#34;.
     * 
     */
    public Output<String> intent() {
        return this.intent;
    }

    /**
     * Worker-node count hint used to size the recipe.
     * 
     */
    @Import(name="nodes")
    private @Nullable Output<Integer> nodes;

    /**
     * @return Worker-node count hint used to size the recipe.
     * 
     */
    public Optional<Output<Integer>> nodes() {
        return Optional.ofNullable(this.nodes);
    }

    /**
     * Operating system flavor of the worker nodes. Leave unset for OS-agnostic
     * resolution. Supported values: &#34;ubuntu&#34;, &#34;cos&#34;, &#34;ol&#34;.
     * 
     */
    @Import(name="os")
    private @Nullable Output<String> os;

    /**
     * @return Operating system flavor of the worker nodes. Leave unset for OS-agnostic
     * resolution. Supported values: &#34;ubuntu&#34;, &#34;cos&#34;, &#34;ol&#34;.
     * 
     */
    public Optional<Output<String>> os() {
        return Optional.ofNullable(this.os);
    }

    /**
     * ML platform/framework. Supported values: &#34;kubeflow&#34; (training),
     * &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
     * 
     */
    @Import(name="platform")
    private @Nullable Output<String> platform;

    /**
     * @return ML platform/framework. Supported values: &#34;kubeflow&#34; (training),
     * &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
     * 
     */
    public Optional<Output<String>> platform() {
        return Optional.ofNullable(this.platform);
    }

    /**
     * Kubernetes service. Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;.
     * 
     */
    @Import(name="service", required=true)
    private Output<String> service;

    /**
     * @return Kubernetes service. Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;.
     * 
     */
    public Output<String> service() {
        return this.service;
    }

    private RecipeCriteriaArgs() {}

    private RecipeCriteriaArgs(RecipeCriteriaArgs $) {
        this.accelerator = $.accelerator;
        this.intent = $.intent;
        this.nodes = $.nodes;
        this.os = $.os;
        this.platform = $.platform;
        this.service = $.service;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(RecipeCriteriaArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private RecipeCriteriaArgs $;

        public Builder() {
            $ = new RecipeCriteriaArgs();
        }

        public Builder(RecipeCriteriaArgs defaults) {
            $ = new RecipeCriteriaArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accelerator GPU accelerator type. Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
         * 
         * @return builder
         * 
         */
        public Builder accelerator(Output<String> accelerator) {
            $.accelerator = accelerator;
            return this;
        }

        /**
         * @param accelerator GPU accelerator type. Supported values: &#34;h100&#34;, &#34;gb200&#34;, &#34;b200&#34;.
         * 
         * @return builder
         * 
         */
        public Builder accelerator(String accelerator) {
            return accelerator(Output.of(accelerator));
        }

        /**
         * @param intent Workload intent. Supported values: &#34;training&#34;, &#34;inference&#34;.
         * 
         * @return builder
         * 
         */
        public Builder intent(Output<String> intent) {
            $.intent = intent;
            return this;
        }

        /**
         * @param intent Workload intent. Supported values: &#34;training&#34;, &#34;inference&#34;.
         * 
         * @return builder
         * 
         */
        public Builder intent(String intent) {
            return intent(Output.of(intent));
        }

        /**
         * @param nodes Worker-node count hint used to size the recipe.
         * 
         * @return builder
         * 
         */
        public Builder nodes(@Nullable Output<Integer> nodes) {
            $.nodes = nodes;
            return this;
        }

        /**
         * @param nodes Worker-node count hint used to size the recipe.
         * 
         * @return builder
         * 
         */
        public Builder nodes(Integer nodes) {
            return nodes(Output.of(nodes));
        }

        /**
         * @param os Operating system flavor of the worker nodes. Leave unset for OS-agnostic
         * resolution. Supported values: &#34;ubuntu&#34;, &#34;cos&#34;, &#34;ol&#34;.
         * 
         * @return builder
         * 
         */
        public Builder os(@Nullable Output<String> os) {
            $.os = os;
            return this;
        }

        /**
         * @param os Operating system flavor of the worker nodes. Leave unset for OS-agnostic
         * resolution. Supported values: &#34;ubuntu&#34;, &#34;cos&#34;, &#34;ol&#34;.
         * 
         * @return builder
         * 
         */
        public Builder os(String os) {
            return os(Output.of(os));
        }

        /**
         * @param platform ML platform/framework. Supported values: &#34;kubeflow&#34; (training),
         * &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
         * 
         * @return builder
         * 
         */
        public Builder platform(@Nullable Output<String> platform) {
            $.platform = platform;
            return this;
        }

        /**
         * @param platform ML platform/framework. Supported values: &#34;kubeflow&#34; (training),
         * &#34;dynamo&#34; (inference), &#34;nim&#34; (inference, EKS+H100 only).
         * 
         * @return builder
         * 
         */
        public Builder platform(String platform) {
            return platform(Output.of(platform));
        }

        /**
         * @param service Kubernetes service. Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;.
         * 
         * @return builder
         * 
         */
        public Builder service(Output<String> service) {
            $.service = service;
            return this;
        }

        /**
         * @param service Kubernetes service. Supported values: &#34;aks&#34;, &#34;eks&#34;, &#34;gke&#34;, &#34;kind&#34;, &#34;oke&#34;.
         * 
         * @return builder
         * 
         */
        public Builder service(String service) {
            return service(Output.of(service));
        }

        public RecipeCriteriaArgs build() {
            if ($.accelerator == null) {
                throw new MissingRequiredPropertyException("RecipeCriteriaArgs", "accelerator");
            }
            if ($.intent == null) {
                throw new MissingRequiredPropertyException("RecipeCriteriaArgs", "intent");
            }
            if ($.service == null) {
                throw new MissingRequiredPropertyException("RecipeCriteriaArgs", "service");
            }
            return $;
        }
    }

}
