// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


/**
 * A Kubernetes pod toleration applied to validation workload pods.
 * 
 */
public final class TolerationArgs extends com.pulumi.resources.ResourceArgs {

    public static final TolerationArgs Empty = new TolerationArgs();

    /**
     * The taint effect to match: &#34;NoSchedule&#34;, &#34;PreferNoSchedule&#34;, or
     * &#34;NoExecute&#34;. Empty matches all effects.
     * 
     */
    @Import(name="effect")
    private @Nullable Output<String> effect;

    /**
     * @return The taint effect to match: &#34;NoSchedule&#34;, &#34;PreferNoSchedule&#34;, or
     * &#34;NoExecute&#34;. Empty matches all effects.
     * 
     */
    public Optional<Output<String>> effect() {
        return Optional.ofNullable(this.effect);
    }

    /**
     * The taint key the toleration applies to. Empty means match all keys
     * (with operator &#34;Exists&#34;).
     * 
     */
    @Import(name="key")
    private @Nullable Output<String> key;

    /**
     * @return The taint key the toleration applies to. Empty means match all keys
     * (with operator &#34;Exists&#34;).
     * 
     */
    public Optional<Output<String>> key() {
        return Optional.ofNullable(this.key);
    }

    /**
     * Key-value relationship: &#34;Exists&#34; or &#34;Equal&#34;. Default: &#34;Equal&#34;.
     * 
     */
    @Import(name="operator")
    private @Nullable Output<String> operator;

    /**
     * @return Key-value relationship: &#34;Exists&#34; or &#34;Equal&#34;. Default: &#34;Equal&#34;.
     * 
     */
    public Optional<Output<String>> operator() {
        return Optional.ofNullable(this.operator);
    }

    /**
     * How long the pod tolerates a &#34;NoExecute&#34; taint, in seconds.
     * 
     */
    @Import(name="tolerationSeconds")
    private @Nullable Output<Integer> tolerationSeconds;

    /**
     * @return How long the pod tolerates a &#34;NoExecute&#34; taint, in seconds.
     * 
     */
    public Optional<Output<Integer>> tolerationSeconds() {
        return Optional.ofNullable(this.tolerationSeconds);
    }

    /**
     * The taint value to match (with operator &#34;Equal&#34;).
     * 
     */
    @Import(name="value")
    private @Nullable Output<String> value;

    /**
     * @return The taint value to match (with operator &#34;Equal&#34;).
     * 
     */
    public Optional<Output<String>> value() {
        return Optional.ofNullable(this.value);
    }

    private TolerationArgs() {}

    private TolerationArgs(TolerationArgs $) {
        this.effect = $.effect;
        this.key = $.key;
        this.operator = $.operator;
        this.tolerationSeconds = $.tolerationSeconds;
        this.value = $.value;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(TolerationArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private TolerationArgs $;

        public Builder() {
            $ = new TolerationArgs();
        }

        public Builder(TolerationArgs defaults) {
            $ = new TolerationArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param effect The taint effect to match: &#34;NoSchedule&#34;, &#34;PreferNoSchedule&#34;, or
         * &#34;NoExecute&#34;. Empty matches all effects.
         * 
         * @return builder
         * 
         */
        public Builder effect(@Nullable Output<String> effect) {
            $.effect = effect;
            return this;
        }

        /**
         * @param effect The taint effect to match: &#34;NoSchedule&#34;, &#34;PreferNoSchedule&#34;, or
         * &#34;NoExecute&#34;. Empty matches all effects.
         * 
         * @return builder
         * 
         */
        public Builder effect(String effect) {
            return effect(Output.of(effect));
        }

        /**
         * @param key The taint key the toleration applies to. Empty means match all keys
         * (with operator &#34;Exists&#34;).
         * 
         * @return builder
         * 
         */
        public Builder key(@Nullable Output<String> key) {
            $.key = key;
            return this;
        }

        /**
         * @param key The taint key the toleration applies to. Empty means match all keys
         * (with operator &#34;Exists&#34;).
         * 
         * @return builder
         * 
         */
        public Builder key(String key) {
            return key(Output.of(key));
        }

        /**
         * @param operator Key-value relationship: &#34;Exists&#34; or &#34;Equal&#34;. Default: &#34;Equal&#34;.
         * 
         * @return builder
         * 
         */
        public Builder operator(@Nullable Output<String> operator) {
            $.operator = operator;
            return this;
        }

        /**
         * @param operator Key-value relationship: &#34;Exists&#34; or &#34;Equal&#34;. Default: &#34;Equal&#34;.
         * 
         * @return builder
         * 
         */
        public Builder operator(String operator) {
            return operator(Output.of(operator));
        }

        /**
         * @param tolerationSeconds How long the pod tolerates a &#34;NoExecute&#34; taint, in seconds.
         * 
         * @return builder
         * 
         */
        public Builder tolerationSeconds(@Nullable Output<Integer> tolerationSeconds) {
            $.tolerationSeconds = tolerationSeconds;
            return this;
        }

        /**
         * @param tolerationSeconds How long the pod tolerates a &#34;NoExecute&#34; taint, in seconds.
         * 
         * @return builder
         * 
         */
        public Builder tolerationSeconds(Integer tolerationSeconds) {
            return tolerationSeconds(Output.of(tolerationSeconds));
        }

        /**
         * @param value The taint value to match (with operator &#34;Equal&#34;).
         * 
         * @return builder
         * 
         */
        public Builder value(@Nullable Output<String> value) {
            $.value = value;
            return this;
        }

        /**
         * @param value The taint value to match (with operator &#34;Equal&#34;).
         * 
         * @return builder
         * 
         */
        public Builder value(String value) {
            return value(Output.of(value));
        }

        public TolerationArgs build() {
            return $;
        }
    }

}
