// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Inputs
{

    /// <summary>
    /// Per-component override settings. Each field is optional; only the fields
    /// you set are applied on top of the recipe defaults.
    /// </summary>
    public sealed class ComponentOverrideArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Override the target Kubernetes namespace.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("values")]
        private InputMap<object>? _values;

        /// <summary>
        /// Additional or override Helm values, deep-merged on top of the
        /// recipe-resolved values.
        /// 
        /// Merge semantics: nested maps merge recursively; scalars and arrays replace
        /// the recipe's value; setting a key to null removes it from the
        /// recipe-resolved values, restoring the chart's own default for that key.
        /// Note the null asymmetry: a null *in the recipe data* is passed through to
        /// Helm (explicitly clearing the chart default), while a null *here* removes
        /// the recipe's setting. There is currently no way to pass a literal null
        /// through to Helm from this input — and some language SDKs drop null map
        /// entries during serialization before they reach the provider at all.
        /// </summary>
        public InputMap<object> Values
        {
            get => _values ?? (_values = new InputMap<object>());
            set => _values = value;
        }

        /// <summary>
        /// Override the Helm chart version. If unset, the recipe-pinned version is used.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ComponentOverrideArgs()
        {
        }
        public static new ComponentOverrideArgs Empty => new ComponentOverrideArgs();
    }
}
