// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Inputs
{

    /// <summary>
    /// Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
    /// intent / os / platform / nodes inputs. Wire a ClusterStack's `criteria`
    /// output here so deployment and validation resolve the identical recipe.
    /// </summary>
    public sealed class RecipeCriteriaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GPU accelerator type. Supported values: "h100", "gb200", "b200".
        /// </summary>
        [Input("accelerator", required: true)]
        public Input<string> Accelerator { get; set; } = null!;

        /// <summary>
        /// Workload intent. Supported values: "training", "inference".
        /// </summary>
        [Input("intent", required: true)]
        public Input<string> Intent { get; set; } = null!;

        /// <summary>
        /// Worker-node count hint used to size the recipe.
        /// </summary>
        [Input("nodes")]
        public Input<int>? Nodes { get; set; }

        /// <summary>
        /// Operating system flavor of the worker nodes. Leave unset for OS-agnostic
        /// resolution. Supported values: "ubuntu", "cos", "ol".
        /// </summary>
        [Input("os")]
        public Input<string>? Os { get; set; }

        /// <summary>
        /// ML platform/framework. Supported values: "kubeflow" (training),
        /// "dynamo" (inference), "nim" (inference, EKS+H100 only).
        /// </summary>
        [Input("platform")]
        public Input<string>? Platform { get; set; }

        /// <summary>
        /// Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
        /// </summary>
        [Input("service", required: true)]
        public Input<string> Service { get; set; } = null!;

        public RecipeCriteriaArgs()
        {
        }
        public static new RecipeCriteriaArgs Empty => new RecipeCriteriaArgs();
    }
}
