// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Inputs
{

    /// <summary>
    /// Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
    /// intent / os / platform / nodes inputs, plus the skipComponents the stack
    /// deployed without. Wire a ClusterStack's `criteria` output here so deployment
    /// and validation resolve the identical recipe and agree on which of its
    /// components are in scope.
    /// </summary>
    public sealed class RecipeCriteriaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// GPU accelerator type. Supported values: "h100", "gb200", "b200", "rtx-pro-6000" (eks/lke only).
        /// </summary>
        [Input("accelerator", required: true)]
        public Input<string> Accelerator { get; set; } = null!;

        /// <summary>
        /// Workload intent. Supported values: "training", "inference".
        /// </summary>
        [Input("intent", required: true)]
        public Input<string> Intent { get; set; } = null!;

        /// <summary>
        /// Worker-node count hint used to size the recipe.
        /// </summary>
        [Input("nodes")]
        public Input<int>? Nodes { get; set; }

        /// <summary>
        /// Operating system flavor of the worker nodes. Leave unset for OS-agnostic
        /// resolution. Supported values: "ubuntu", "cos", "ol".
        /// </summary>
        [Input("os")]
        public Input<string>? Os { get; set; }

        /// <summary>
        /// ML platform/framework. Supported values: "kubeflow" (training),
        /// "dynamo" (inference), "nim" (inference, EKS+H100 only).
        /// </summary>
        [Input("platform")]
        public Input<string>? Platform { get; set; }

        /// <summary>
        /// Kubernetes service. Supported values: "aks", "bcm", "eks", "gke", "kind", "lke", "oke".
        /// </summary>
        [Input("service", required: true)]
        public Input<string> Service { get; set; } = null!;

        [Input("skipComponents")]
        private InputList<string>? _skipComponents;

        /// <summary>
        /// Recipe components the stack intentionally did not deploy (ClusterStack's
        /// `skipComponents`). ValidationRun treats them as out of scope rather than
        /// missing: checks that presuppose one of them (e.g. the gpu-operator health,
        /// DCGM metrics, and GPU-HPA checks when "gpu-operator" is skipped) are reported
        /// "skipped" with a reason instead of failing, and the SDK's component-aware
        /// checks see the components as disabled. A ClusterStack's `criteria` output
        /// carries its own skipComponents, so wiring it keeps validation aligned with
        /// the deployed subset automatically. Skipping does not verify a replacement
        /// you run yourself — those checks are simply not made.
        /// </summary>
        public InputList<string> SkipComponents
        {
            get => _skipComponents ?? (_skipComponents = new InputList<string>());
            set => _skipComponents = value;
        }

        public RecipeCriteriaArgs()
        {
        }
        public static new RecipeCriteriaArgs Empty => new RecipeCriteriaArgs();
    }
}
