// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr.Inputs
{

    /// <summary>
    /// A Kubernetes pod toleration applied to validation workload pods.
    /// </summary>
    public sealed class TolerationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The taint effect to match: "NoSchedule", "PreferNoSchedule", or
        /// "NoExecute". Empty matches all effects.
        /// </summary>
        [Input("effect")]
        public Input<string>? Effect { get; set; }

        /// <summary>
        /// The taint key the toleration applies to. Empty means match all keys
        /// (with operator "Exists").
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Key-value relationship: "Exists" or "Equal". Default: "Equal".
        /// </summary>
        [Input("operator")]
        public Input<string>? Operator { get; set; }

        /// <summary>
        /// How long the pod tolerates a "NoExecute" taint, in seconds.
        /// </summary>
        [Input("tolerationSeconds")]
        public Input<int>? TolerationSeconds { get; set; }

        /// <summary>
        /// The taint value to match (with operator "Equal").
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public TolerationArgs()
        {
        }
        public static new TolerationArgs Empty => new TolerationArgs();
    }
}
