// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.core.internal.Codegen;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.labs.nvidiaaicr.inputs.RecipeCriteriaArgs;
import com.pulumi.labs.nvidiaaicr.inputs.TolerationArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ValidationRunArgs extends com.pulumi.resources.ResourceArgs {

    public static final ValidationRunArgs Empty = new ValidationRunArgs();

    /**
     * Kubeconfig context to select. Defaults to the kubeconfig&#39;s current-context.
     * 
     */
    @Import(name="context")
    private @Nullable Output<String> context;

    /**
     * @return Kubeconfig context to select. Defaults to the kubeconfig&#39;s current-context.
     * 
     */
    public Optional<Output<String>> context() {
        return Optional.ofNullable(this.context);
    }

    /**
     * Recipe criteria. Wire a ClusterStack&#39;s `criteria` output here, or build
     * the object inline.
     * 
     */
    @Import(name="criteria", required=true)
    private Output<RecipeCriteriaArgs> criteria;

    /**
     * @return Recipe criteria. Wire a ClusterStack&#39;s `criteria` output here, or build
     * the object inline.
     * 
     */
    public Output<RecipeCriteriaArgs> criteria() {
        return this.criteria;
    }

    /**
     * Names of image pull Secrets (in the validation namespace) for the
     * validation pods.
     * 
     */
    @Import(name="imagePullSecrets")
    private @Nullable Output<List<String>> imagePullSecrets;

    /**
     * @return Names of image pull Secrets (in the validation namespace) for the
     * validation pods.
     * 
     */
    public Optional<Output<List<String>>> imagePullSecrets() {
        return Optional.ofNullable(this.imagePullSecrets);
    }

    /**
     * Registry override for the snapshot-agent and validator images (air-gapped
     * mirrors). Unset keeps the default registry (ghcr.io).
     * 
     */
    @Import(name="imageRegistry")
    private @Nullable Output<String> imageRegistry;

    /**
     * @return Registry override for the snapshot-agent and validator images (air-gapped
     * mirrors). Unset keeps the default registry (ghcr.io).
     * 
     */
    public Optional<Output<String>> imageRegistry() {
        return Optional.ofNullable(this.imageRegistry);
    }

    /**
     * If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
     * Default: false (state-size control; per-check results are always in
     * `phaseResults`).
     * 
     */
    @Import(name="includeCtrfReport")
    private @Nullable Output<Boolean> includeCtrfReport;

    /**
     * @return If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
     * Default: false (state-size control; per-check results are always in
     * `phaseResults`).
     * 
     */
    public Optional<Output<Boolean>> includeCtrfReport() {
        return Optional.ofNullable(this.includeCtrfReport);
    }

    /**
     * Kubeconfig contents for the target cluster. Mutually exclusive with
     * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
     * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
     * duration of the run and removed afterward.
     * 
     */
    @Import(name="kubeconfig")
    private @Nullable Output<String> kubeconfig;

    /**
     * @return Kubeconfig contents for the target cluster. Mutually exclusive with
     * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
     * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
     * duration of the run and removed afterward.
     * 
     */
    public Optional<Output<String>> kubeconfig() {
        return Optional.ofNullable(this.kubeconfig);
    }

    /**
     * Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * 
     */
    @Import(name="kubeconfigPath")
    private @Nullable Output<String> kubeconfigPath;

    /**
     * @return Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * 
     */
    public Optional<Output<String>> kubeconfigPath() {
        return Optional.ofNullable(this.kubeconfigPath);
    }

    /**
     * Namespace for the validation harness — use a dedicated one: it hosts the
     * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
     * on first run and deliberately never deletes it. Must be a valid DNS-1123
     * label and not a &#34;kube-&#34; system namespace. Default: &#34;aicr-validation&#34;.
     * 
     */
    @Import(name="namespace")
    private @Nullable Output<String> namespace;

    /**
     * @return Namespace for the validation harness — use a dedicated one: it hosts the
     * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
     * on first run and deliberately never deletes it. Must be a valid DNS-1123
     * label and not a &#34;kube-&#34; system namespace. Default: &#34;aicr-validation&#34;.
     * 
     */
    public Optional<Output<String>> namespace() {
        return Optional.ofNullable(this.namespace);
    }

    /**
     * Node selector applied to the validation workload pods. Use when GPU nodes
     * carry non-standard labels.
     * 
     */
    @Import(name="nodeSelector")
    private @Nullable Output<Map<String,String>> nodeSelector;

    /**
     * @return Node selector applied to the validation workload pods. Use when GPU nodes
     * carry non-standard labels.
     * 
     */
    public Optional<Output<Map<String,String>>> nodeSelector() {
        return Optional.ofNullable(this.nodeSelector);
    }

    /**
     * Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
     * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
     * explicit opt-in (long-running and hardware-bound).
     * 
     */
    @Import(name="phases")
    private @Nullable Output<List<String>> phases;

    /**
     * @return Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
     * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
     * explicit opt-in (long-running and hardware-bound).
     * 
     */
    public Optional<Output<List<String>>> phases() {
        return Optional.ofNullable(this.phases);
    }

    /**
     * Recipe-data version assertion (not a pin). When set, it must equal this
     * provider build&#39;s embedded AICR recipe-data version or Create fails before
     * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
     * provider upgrade between deploy and validate.
     * 
     */
    @Import(name="recipeDataVersion")
    private @Nullable Output<String> recipeDataVersion;

    /**
     * @return Recipe-data version assertion (not a pin). When set, it must equal this
     * provider build&#39;s embedded AICR recipe-data version or Create fails before
     * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
     * provider upgrade between deploy and validate.
     * 
     */
    public Optional<Output<String>> recipeDataVersion() {
        return Optional.ofNullable(this.recipeDataVersion);
    }

    /**
     * Whether the snapshot agent requires GPU nodes. Set false for
     * hardware-free clusters (kind). Default: true.
     * 
     */
    @Import(name="requireGpu")
    private @Nullable Output<Boolean> requireGpu;

    /**
     * @return Whether the snapshot agent requires GPU nodes. Set false for
     * hardware-free clusters (kind). Default: true.
     * 
     */
    public Optional<Output<Boolean>> requireGpu() {
        return Optional.ofNullable(this.requireGpu);
    }

    /**
     * If true, a failed (or readiness-failed) validation fails the update while
     * still persisting the full results in state. The engine then re-runs
     * validation on every subsequent `pulumi up` until it passes. Default: false —
     * results are recorded and the update succeeds; read the `status` output.
     * 
     */
    @Import(name="strict")
    private @Nullable Output<Boolean> strict;

    /**
     * @return If true, a failed (or readiness-failed) validation fails the update while
     * still persisting the full results in state. The engine then re-runs
     * validation on every subsequent `pulumi up` until it passes. Default: false —
     * results are recorded and the update succeeds; read the `status` output.
     * 
     */
    public Optional<Output<Boolean>> strict() {
        return Optional.ofNullable(this.strict);
    }

    /**
     * Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
     * 
     */
    @Import(name="timeoutMinutes")
    private @Nullable Output<Integer> timeoutMinutes;

    /**
     * @return Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
     * 
     */
    public Optional<Output<Integer>> timeoutMinutes() {
        return Optional.ofNullable(this.timeoutMinutes);
    }

    /**
     * Tolerations applied to the validation workload pods (e.g. NCCL benchmark
     * pods). Required in practice on tainted GPU node groups; when unset, the
     * validator&#39;s default tolerate-all is kept.
     * 
     */
    @Import(name="tolerations")
    private @Nullable Output<List<TolerationArgs>> tolerations;

    /**
     * @return Tolerations applied to the validation workload pods (e.g. NCCL benchmark
     * pods). Required in practice on tainted GPU node groups; when unset, the
     * validator&#39;s default tolerate-all is kept.
     * 
     */
    public Optional<Output<List<TolerationArgs>>> tolerations() {
        return Optional.ofNullable(this.tolerations);
    }

    /**
     * Arbitrary values; changing any of them replaces the resource and re-runs
     * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
     * for re-validation cadence.
     * 
     */
    @Import(name="triggers")
    private @Nullable Output<List<Object>> triggers;

    /**
     * @return Arbitrary values; changing any of them replaces the resource and re-runs
     * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
     * for re-validation cadence.
     * 
     */
    public Optional<Output<List<Object>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    private ValidationRunArgs() {}

    private ValidationRunArgs(ValidationRunArgs $) {
        this.context = $.context;
        this.criteria = $.criteria;
        this.imagePullSecrets = $.imagePullSecrets;
        this.imageRegistry = $.imageRegistry;
        this.includeCtrfReport = $.includeCtrfReport;
        this.kubeconfig = $.kubeconfig;
        this.kubeconfigPath = $.kubeconfigPath;
        this.namespace = $.namespace;
        this.nodeSelector = $.nodeSelector;
        this.phases = $.phases;
        this.recipeDataVersion = $.recipeDataVersion;
        this.requireGpu = $.requireGpu;
        this.strict = $.strict;
        this.timeoutMinutes = $.timeoutMinutes;
        this.tolerations = $.tolerations;
        this.triggers = $.triggers;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ValidationRunArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ValidationRunArgs $;

        public Builder() {
            $ = new ValidationRunArgs();
        }

        public Builder(ValidationRunArgs defaults) {
            $ = new ValidationRunArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param context Kubeconfig context to select. Defaults to the kubeconfig&#39;s current-context.
         * 
         * @return builder
         * 
         */
        public Builder context(@Nullable Output<String> context) {
            $.context = context;
            return this;
        }

        /**
         * @param context Kubeconfig context to select. Defaults to the kubeconfig&#39;s current-context.
         * 
         * @return builder
         * 
         */
        public Builder context(String context) {
            return context(Output.of(context));
        }

        /**
         * @param criteria Recipe criteria. Wire a ClusterStack&#39;s `criteria` output here, or build
         * the object inline.
         * 
         * @return builder
         * 
         */
        public Builder criteria(Output<RecipeCriteriaArgs> criteria) {
            $.criteria = criteria;
            return this;
        }

        /**
         * @param criteria Recipe criteria. Wire a ClusterStack&#39;s `criteria` output here, or build
         * the object inline.
         * 
         * @return builder
         * 
         */
        public Builder criteria(RecipeCriteriaArgs criteria) {
            return criteria(Output.of(criteria));
        }

        /**
         * @param imagePullSecrets Names of image pull Secrets (in the validation namespace) for the
         * validation pods.
         * 
         * @return builder
         * 
         */
        public Builder imagePullSecrets(@Nullable Output<List<String>> imagePullSecrets) {
            $.imagePullSecrets = imagePullSecrets;
            return this;
        }

        /**
         * @param imagePullSecrets Names of image pull Secrets (in the validation namespace) for the
         * validation pods.
         * 
         * @return builder
         * 
         */
        public Builder imagePullSecrets(List<String> imagePullSecrets) {
            return imagePullSecrets(Output.of(imagePullSecrets));
        }

        /**
         * @param imagePullSecrets Names of image pull Secrets (in the validation namespace) for the
         * validation pods.
         * 
         * @return builder
         * 
         */
        public Builder imagePullSecrets(String... imagePullSecrets) {
            return imagePullSecrets(List.of(imagePullSecrets));
        }

        /**
         * @param imageRegistry Registry override for the snapshot-agent and validator images (air-gapped
         * mirrors). Unset keeps the default registry (ghcr.io).
         * 
         * @return builder
         * 
         */
        public Builder imageRegistry(@Nullable Output<String> imageRegistry) {
            $.imageRegistry = imageRegistry;
            return this;
        }

        /**
         * @param imageRegistry Registry override for the snapshot-agent and validator images (air-gapped
         * mirrors). Unset keeps the default registry (ghcr.io).
         * 
         * @return builder
         * 
         */
        public Builder imageRegistry(String imageRegistry) {
            return imageRegistry(Output.of(imageRegistry));
        }

        /**
         * @param includeCtrfReport If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
         * Default: false (state-size control; per-check results are always in
         * `phaseResults`).
         * 
         * @return builder
         * 
         */
        public Builder includeCtrfReport(@Nullable Output<Boolean> includeCtrfReport) {
            $.includeCtrfReport = includeCtrfReport;
            return this;
        }

        /**
         * @param includeCtrfReport If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
         * Default: false (state-size control; per-check results are always in
         * `phaseResults`).
         * 
         * @return builder
         * 
         */
        public Builder includeCtrfReport(Boolean includeCtrfReport) {
            return includeCtrfReport(Output.of(includeCtrfReport));
        }

        /**
         * @param kubeconfig Kubeconfig contents for the target cluster. Mutually exclusive with
         * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
         * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
         * duration of the run and removed afterward.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfig(@Nullable Output<String> kubeconfig) {
            $.kubeconfig = kubeconfig;
            return this;
        }

        /**
         * @param kubeconfig Kubeconfig contents for the target cluster. Mutually exclusive with
         * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
         * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
         * duration of the run and removed afterward.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfig(String kubeconfig) {
            return kubeconfig(Output.of(kubeconfig));
        }

        /**
         * @param kubeconfigPath Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfigPath(@Nullable Output<String> kubeconfigPath) {
            $.kubeconfigPath = kubeconfigPath;
            return this;
        }

        /**
         * @param kubeconfigPath Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
         * 
         * @return builder
         * 
         */
        public Builder kubeconfigPath(String kubeconfigPath) {
            return kubeconfigPath(Output.of(kubeconfigPath));
        }

        /**
         * @param namespace Namespace for the validation harness — use a dedicated one: it hosts the
         * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
         * on first run and deliberately never deletes it. Must be a valid DNS-1123
         * label and not a &#34;kube-&#34; system namespace. Default: &#34;aicr-validation&#34;.
         * 
         * @return builder
         * 
         */
        public Builder namespace(@Nullable Output<String> namespace) {
            $.namespace = namespace;
            return this;
        }

        /**
         * @param namespace Namespace for the validation harness — use a dedicated one: it hosts the
         * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
         * on first run and deliberately never deletes it. Must be a valid DNS-1123
         * label and not a &#34;kube-&#34; system namespace. Default: &#34;aicr-validation&#34;.
         * 
         * @return builder
         * 
         */
        public Builder namespace(String namespace) {
            return namespace(Output.of(namespace));
        }

        /**
         * @param nodeSelector Node selector applied to the validation workload pods. Use when GPU nodes
         * carry non-standard labels.
         * 
         * @return builder
         * 
         */
        public Builder nodeSelector(@Nullable Output<Map<String,String>> nodeSelector) {
            $.nodeSelector = nodeSelector;
            return this;
        }

        /**
         * @param nodeSelector Node selector applied to the validation workload pods. Use when GPU nodes
         * carry non-standard labels.
         * 
         * @return builder
         * 
         */
        public Builder nodeSelector(Map<String,String> nodeSelector) {
            return nodeSelector(Output.of(nodeSelector));
        }

        /**
         * @param phases Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
         * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
         * explicit opt-in (long-running and hardware-bound).
         * 
         * @return builder
         * 
         */
        public Builder phases(@Nullable Output<List<String>> phases) {
            $.phases = phases;
            return this;
        }

        /**
         * @param phases Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
         * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
         * explicit opt-in (long-running and hardware-bound).
         * 
         * @return builder
         * 
         */
        public Builder phases(List<String> phases) {
            return phases(Output.of(phases));
        }

        /**
         * @param phases Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
         * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
         * explicit opt-in (long-running and hardware-bound).
         * 
         * @return builder
         * 
         */
        public Builder phases(String... phases) {
            return phases(List.of(phases));
        }

        /**
         * @param recipeDataVersion Recipe-data version assertion (not a pin). When set, it must equal this
         * provider build&#39;s embedded AICR recipe-data version or Create fails before
         * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
         * provider upgrade between deploy and validate.
         * 
         * @return builder
         * 
         */
        public Builder recipeDataVersion(@Nullable Output<String> recipeDataVersion) {
            $.recipeDataVersion = recipeDataVersion;
            return this;
        }

        /**
         * @param recipeDataVersion Recipe-data version assertion (not a pin). When set, it must equal this
         * provider build&#39;s embedded AICR recipe-data version or Create fails before
         * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
         * provider upgrade between deploy and validate.
         * 
         * @return builder
         * 
         */
        public Builder recipeDataVersion(String recipeDataVersion) {
            return recipeDataVersion(Output.of(recipeDataVersion));
        }

        /**
         * @param requireGpu Whether the snapshot agent requires GPU nodes. Set false for
         * hardware-free clusters (kind). Default: true.
         * 
         * @return builder
         * 
         */
        public Builder requireGpu(@Nullable Output<Boolean> requireGpu) {
            $.requireGpu = requireGpu;
            return this;
        }

        /**
         * @param requireGpu Whether the snapshot agent requires GPU nodes. Set false for
         * hardware-free clusters (kind). Default: true.
         * 
         * @return builder
         * 
         */
        public Builder requireGpu(Boolean requireGpu) {
            return requireGpu(Output.of(requireGpu));
        }

        /**
         * @param strict If true, a failed (or readiness-failed) validation fails the update while
         * still persisting the full results in state. The engine then re-runs
         * validation on every subsequent `pulumi up` until it passes. Default: false —
         * results are recorded and the update succeeds; read the `status` output.
         * 
         * @return builder
         * 
         */
        public Builder strict(@Nullable Output<Boolean> strict) {
            $.strict = strict;
            return this;
        }

        /**
         * @param strict If true, a failed (or readiness-failed) validation fails the update while
         * still persisting the full results in state. The engine then re-runs
         * validation on every subsequent `pulumi up` until it passes. Default: false —
         * results are recorded and the update succeeds; read the `status` output.
         * 
         * @return builder
         * 
         */
        public Builder strict(Boolean strict) {
            return strict(Output.of(strict));
        }

        /**
         * @param timeoutMinutes Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
         * 
         * @return builder
         * 
         */
        public Builder timeoutMinutes(@Nullable Output<Integer> timeoutMinutes) {
            $.timeoutMinutes = timeoutMinutes;
            return this;
        }

        /**
         * @param timeoutMinutes Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
         * 
         * @return builder
         * 
         */
        public Builder timeoutMinutes(Integer timeoutMinutes) {
            return timeoutMinutes(Output.of(timeoutMinutes));
        }

        /**
         * @param tolerations Tolerations applied to the validation workload pods (e.g. NCCL benchmark
         * pods). Required in practice on tainted GPU node groups; when unset, the
         * validator&#39;s default tolerate-all is kept.
         * 
         * @return builder
         * 
         */
        public Builder tolerations(@Nullable Output<List<TolerationArgs>> tolerations) {
            $.tolerations = tolerations;
            return this;
        }

        /**
         * @param tolerations Tolerations applied to the validation workload pods (e.g. NCCL benchmark
         * pods). Required in practice on tainted GPU node groups; when unset, the
         * validator&#39;s default tolerate-all is kept.
         * 
         * @return builder
         * 
         */
        public Builder tolerations(List<TolerationArgs> tolerations) {
            return tolerations(Output.of(tolerations));
        }

        /**
         * @param tolerations Tolerations applied to the validation workload pods (e.g. NCCL benchmark
         * pods). Required in practice on tainted GPU node groups; when unset, the
         * validator&#39;s default tolerate-all is kept.
         * 
         * @return builder
         * 
         */
        public Builder tolerations(TolerationArgs... tolerations) {
            return tolerations(List.of(tolerations));
        }

        /**
         * @param triggers Arbitrary values; changing any of them replaces the resource and re-runs
         * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
         * for re-validation cadence.
         * 
         * @return builder
         * 
         */
        public Builder triggers(@Nullable Output<List<Object>> triggers) {
            $.triggers = triggers;
            return this;
        }

        /**
         * @param triggers Arbitrary values; changing any of them replaces the resource and re-runs
         * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
         * for re-validation cadence.
         * 
         * @return builder
         * 
         */
        public Builder triggers(List<Object> triggers) {
            return triggers(Output.of(triggers));
        }

        /**
         * @param triggers Arbitrary values; changing any of them replaces the resource and re-runs
         * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
         * for re-validation cadence.
         * 
         * @return builder
         * 
         */
        public Builder triggers(Object... triggers) {
            return triggers(List.of(triggers));
        }

        public ValidationRunArgs build() {
            if ($.criteria == null) {
                throw new MissingRequiredPropertyException("ValidationRunArgs", "criteria");
            }
            $.includeCtrfReport = Codegen.booleanProp("includeCtrfReport").output().arg($.includeCtrfReport).def(false).getNullable();
            $.namespace = Codegen.stringProp("namespace").output().arg($.namespace).def("aicr-validation").getNullable();
            $.requireGpu = Codegen.booleanProp("requireGpu").output().arg($.requireGpu).def(true).getNullable();
            $.strict = Codegen.booleanProp("strict").output().arg($.strict).def(false).getNullable();
            $.timeoutMinutes = Codegen.integerProp("timeoutMinutes").output().arg($.timeoutMinutes).def(30).getNullable();
            return $;
        }
    }

}
