// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.labs.nvidiaaicr;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.labs.nvidiaaicr.Utilities;
import com.pulumi.labs.nvidiaaicr.ValidationRunArgs;
import com.pulumi.labs.nvidiaaicr.outputs.CheckResult;
import com.pulumi.labs.nvidiaaicr.outputs.RecipeCriteria;
import com.pulumi.labs.nvidiaaicr.outputs.Toleration;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Runs an AICR recipe&#39;s empirical validation (cluster snapshot +
 * deployment/conformance/performance checks) against a live cluster and
 * records structured per-check results in Pulumi state.
 * 
 * The run happens at deploy time (never at preview). The validation harness
 * deploys short-lived agent and validator Jobs plus per-run RBAC on the target
 * cluster and cleans them up afterward; the validation namespace (default
 * &#34;aicr-validation&#34;) is created on first run and deliberately persists.
 * 
 * Privilege level: the snapshot-agent Job runs as a privileged container
 * (bound to a read-only node-inspection ClusterRole), and validator Jobs run
 * under a per-run cluster-admin ClusterRoleBinding — both removed after the
 * run, including on cancellation. The kubeconfig identity needs RBAC to
 * create/patch Namespaces, ClusterRoles, and ClusterRoleBindings.
 * 
 * Any input change replaces the resource, which re-runs validation (delete is
 * a no-op). With `strict: true`, a failed run fails the update while persisting
 * full results, and validation re-runs on every subsequent `pulumi up` until it
 * passes — use `dependsOn` to gate downstream resources on it.
 * 
 */
@ResourceType(type="nvidia-aicr:index:ValidationRun")
public class ValidationRun extends com.pulumi.resources.CustomResource {
    /**
     * When the run completed, RFC 3339.
     * 
     */
    @Export(name="completedAt", refs={String.class}, tree="[0]")
    private Output<String> completedAt;

    /**
     * @return When the run completed, RFC 3339.
     * 
     */
    public Output<String> completedAt() {
        return this.completedAt;
    }
    /**
     * Kubeconfig context to select. Defaults to the kubeconfig&#39;s current-context.
     * 
     */
    @Export(name="context", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> context;

    /**
     * @return Kubeconfig context to select. Defaults to the kubeconfig&#39;s current-context.
     * 
     */
    public Output<Optional<String>> context() {
        return Codegen.optional(this.context);
    }
    /**
     * Recipe criteria. Wire a ClusterStack&#39;s `criteria` output here, or build
     * the object inline.
     * 
     */
    @Export(name="criteria", refs={RecipeCriteria.class}, tree="[0]")
    private Output<RecipeCriteria> criteria;

    /**
     * @return Recipe criteria. Wire a ClusterStack&#39;s `criteria` output here, or build
     * the object inline.
     * 
     */
    public Output<RecipeCriteria> criteria() {
        return this.criteria;
    }
    /**
     * The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
     * 
     */
    @Export(name="ctrfReport", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ctrfReport;

    /**
     * @return The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
     * 
     */
    public Output<Optional<String>> ctrfReport() {
        return Codegen.optional(this.ctrfReport);
    }
    /**
     * Number of checks that failed.
     * 
     */
    @Export(name="failed", refs={Integer.class}, tree="[0]")
    private Output<Integer> failed;

    /**
     * @return Number of checks that failed.
     * 
     */
    public Output<Integer> failed() {
        return this.failed;
    }
    /**
     * Names of image pull Secrets (in the validation namespace) for the
     * validation pods.
     * 
     */
    @Export(name="imagePullSecrets", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> imagePullSecrets;

    /**
     * @return Names of image pull Secrets (in the validation namespace) for the
     * validation pods.
     * 
     */
    public Output<Optional<List<String>>> imagePullSecrets() {
        return Codegen.optional(this.imagePullSecrets);
    }
    /**
     * Registry override for the snapshot-agent and validator images (air-gapped
     * mirrors). Unset keeps the default registry (ghcr.io).
     * 
     */
    @Export(name="imageRegistry", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> imageRegistry;

    /**
     * @return Registry override for the snapshot-agent and validator images (air-gapped
     * mirrors). Unset keeps the default registry (ghcr.io).
     * 
     */
    public Output<Optional<String>> imageRegistry() {
        return Codegen.optional(this.imageRegistry);
    }
    /**
     * If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
     * Default: false (state-size control; per-check results are always in
     * `phaseResults`).
     * 
     */
    @Export(name="includeCtrfReport", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> includeCtrfReport;

    /**
     * @return If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
     * Default: false (state-size control; per-check results are always in
     * `phaseResults`).
     * 
     */
    public Output<Optional<Boolean>> includeCtrfReport() {
        return Codegen.optional(this.includeCtrfReport);
    }
    /**
     * Kubeconfig contents for the target cluster. Mutually exclusive with
     * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
     * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
     * duration of the run and removed afterward.
     * 
     */
    @Export(name="kubeconfig", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> kubeconfig;

    /**
     * @return Kubeconfig contents for the target cluster. Mutually exclusive with
     * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
     * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
     * duration of the run and removed afterward.
     * 
     */
    public Output<Optional<String>> kubeconfig() {
        return Codegen.optional(this.kubeconfig);
    }
    /**
     * Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * 
     */
    @Export(name="kubeconfigPath", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> kubeconfigPath;

    /**
     * @return Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * 
     */
    public Output<Optional<String>> kubeconfigPath() {
        return Codegen.optional(this.kubeconfigPath);
    }
    /**
     * Namespace for the validation harness — use a dedicated one: it hosts the
     * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
     * on first run and deliberately never deletes it. Must be a valid DNS-1123
     * label and not a &#34;kube-&#34; system namespace. Default: &#34;aicr-validation&#34;.
     * 
     */
    @Export(name="namespace", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> namespace;

    /**
     * @return Namespace for the validation harness — use a dedicated one: it hosts the
     * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
     * on first run and deliberately never deletes it. Must be a valid DNS-1123
     * label and not a &#34;kube-&#34; system namespace. Default: &#34;aicr-validation&#34;.
     * 
     */
    public Output<Optional<String>> namespace() {
        return Codegen.optional(this.namespace);
    }
    /**
     * Node selector applied to the validation workload pods. Use when GPU nodes
     * carry non-standard labels.
     * 
     */
    @Export(name="nodeSelector", refs={Map.class,String.class}, tree="[0,1,1]")
    private Output</* @Nullable */ Map<String,String>> nodeSelector;

    /**
     * @return Node selector applied to the validation workload pods. Use when GPU nodes
     * carry non-standard labels.
     * 
     */
    public Output<Optional<Map<String,String>>> nodeSelector() {
        return Codegen.optional(this.nodeSelector);
    }
    /**
     * Number of checks with an inconclusive outcome (crash, OOM, timeout;
     * includes CTRF &#34;pending&#34;).
     * 
     */
    @Export(name="other", refs={Integer.class}, tree="[0]")
    private Output<Integer> other;

    /**
     * @return Number of checks with an inconclusive outcome (crash, OOM, timeout;
     * includes CTRF &#34;pending&#34;).
     * 
     */
    public Output<Integer> other() {
        return this.other;
    }
    /**
     * Number of checks that passed.
     * 
     */
    @Export(name="passed", refs={Integer.class}, tree="[0]")
    private Output<Integer> passed;

    /**
     * @return Number of checks that passed.
     * 
     */
    public Output<Integer> passed() {
        return this.passed;
    }
    /**
     * Per-check results across all phases run.
     * 
     */
    @Export(name="phaseResults", refs={List.class,CheckResult.class}, tree="[0,1]")
    private Output<List<CheckResult>> phaseResults;

    /**
     * @return Per-check results across all phases run.
     * 
     */
    public Output<List<CheckResult>> phaseResults() {
        return this.phaseResults;
    }
    /**
     * Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
     * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
     * explicit opt-in (long-running and hardware-bound).
     * 
     */
    @Export(name="phases", refs={List.class,String.class}, tree="[0,1]")
    private Output</* @Nullable */ List<String>> phases;

    /**
     * @return Validation phases to run: any of &#34;deployment&#34;, &#34;conformance&#34;,
     * &#34;performance&#34;. Default: [&#34;deployment&#34;, &#34;conformance&#34;] — &#34;performance&#34; is an
     * explicit opt-in (long-running and hardware-bound).
     * 
     */
    public Output<Optional<List<String>>> phases() {
        return Codegen.optional(this.phases);
    }
    /**
     * The readiness pre-flight failure message; empty unless status is
     * &#34;readiness-failed&#34;.
     * 
     */
    @Export(name="readinessMessage", refs={String.class}, tree="[0]")
    private Output<String> readinessMessage;

    /**
     * @return The readiness pre-flight failure message; empty unless status is
     * &#34;readiness-failed&#34;.
     * 
     */
    public Output<String> readinessMessage() {
        return this.readinessMessage;
    }
    /**
     * Recipe-data version assertion (not a pin). When set, it must equal this
     * provider build&#39;s embedded AICR recipe-data version or Create fails before
     * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
     * provider upgrade between deploy and validate.
     * 
     */
    @Export(name="recipeDataVersion", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> recipeDataVersion;

    /**
     * @return Recipe-data version assertion (not a pin). When set, it must equal this
     * provider build&#39;s embedded AICR recipe-data version or Create fails before
     * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
     * provider upgrade between deploy and validate.
     * 
     */
    public Output<Optional<String>> recipeDataVersion() {
        return Codegen.optional(this.recipeDataVersion);
    }
    /**
     * The resolved AICR recipe name that was validated.
     * 
     */
    @Export(name="recipeName", refs={String.class}, tree="[0]")
    private Output<String> recipeName;

    /**
     * @return The resolved AICR recipe name that was validated.
     * 
     */
    public Output<String> recipeName() {
        return this.recipeName;
    }
    /**
     * The AICR recipe data version that was validated.
     * 
     */
    @Export(name="recipeVersion", refs={String.class}, tree="[0]")
    private Output<String> recipeVersion;

    /**
     * @return The AICR recipe data version that was validated.
     * 
     */
    public Output<String> recipeVersion() {
        return this.recipeVersion;
    }
    /**
     * Whether the snapshot agent requires GPU nodes. Set false for
     * hardware-free clusters (kind). Default: true.
     * 
     */
    @Export(name="requireGpu", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> requireGpu;

    /**
     * @return Whether the snapshot agent requires GPU nodes. Set false for
     * hardware-free clusters (kind). Default: true.
     * 
     */
    public Output<Optional<Boolean>> requireGpu() {
        return Codegen.optional(this.requireGpu);
    }
    /**
     * The run identifier labeling this run&#39;s cluster-side artifacts.
     * 
     */
    @Export(name="runId", refs={String.class}, tree="[0]")
    private Output<String> runId;

    /**
     * @return The run identifier labeling this run&#39;s cluster-side artifacts.
     * 
     */
    public Output<String> runId() {
        return this.runId;
    }
    /**
     * Number of checks that were skipped.
     * 
     */
    @Export(name="skipped", refs={Integer.class}, tree="[0]")
    private Output<Integer> skipped;

    /**
     * @return Number of checks that were skipped.
     * 
     */
    public Output<Integer> skipped() {
        return this.skipped;
    }
    /**
     * Rollup verdict: &#34;passed&#34;, &#34;failed&#34;, or &#34;readiness-failed&#34;. Checks with
     * status &#34;other&#34; never flip the rollup (they are counted and listed).
     * Infrastructure errors have no status — they fail the update outright.
     * 
     */
    @Export(name="status", refs={String.class}, tree="[0]")
    private Output<String> status;

    /**
     * @return Rollup verdict: &#34;passed&#34;, &#34;failed&#34;, or &#34;readiness-failed&#34;. Checks with
     * status &#34;other&#34; never flip the rollup (they are counted and listed).
     * Infrastructure errors have no status — they fail the update outright.
     * 
     */
    public Output<String> status() {
        return this.status;
    }
    /**
     * If true, a failed (or readiness-failed) validation fails the update while
     * still persisting the full results in state. The engine then re-runs
     * validation on every subsequent `pulumi up` until it passes. Default: false —
     * results are recorded and the update succeeds; read the `status` output.
     * 
     */
    @Export(name="strict", refs={Boolean.class}, tree="[0]")
    private Output</* @Nullable */ Boolean> strict;

    /**
     * @return If true, a failed (or readiness-failed) validation fails the update while
     * still persisting the full results in state. The engine then re-runs
     * validation on every subsequent `pulumi up` until it passes. Default: false —
     * results are recorded and the update succeeds; read the `status` output.
     * 
     */
    public Output<Optional<Boolean>> strict() {
        return Codegen.optional(this.strict);
    }
    /**
     * Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
     * 
     */
    @Export(name="timeoutMinutes", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> timeoutMinutes;

    /**
     * @return Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
     * 
     */
    public Output<Optional<Integer>> timeoutMinutes() {
        return Codegen.optional(this.timeoutMinutes);
    }
    /**
     * Tolerations applied to the validation workload pods (e.g. NCCL benchmark
     * pods). Required in practice on tainted GPU node groups; when unset, the
     * validator&#39;s default tolerate-all is kept.
     * 
     */
    @Export(name="tolerations", refs={List.class,Toleration.class}, tree="[0,1]")
    private Output</* @Nullable */ List<Toleration>> tolerations;

    /**
     * @return Tolerations applied to the validation workload pods (e.g. NCCL benchmark
     * pods). Required in practice on tainted GPU node groups; when unset, the
     * validator&#39;s default tolerate-all is kept.
     * 
     */
    public Output<Optional<List<Toleration>>> tolerations() {
        return Codegen.optional(this.tolerations);
    }
    /**
     * Arbitrary values; changing any of them replaces the resource and re-runs
     * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
     * for re-validation cadence.
     * 
     */
    @Export(name="triggers", refs={List.class,Object.class}, tree="[0,1]")
    private Output</* @Nullable */ List<Object>> triggers;

    /**
     * @return Arbitrary values; changing any of them replaces the resource and re-runs
     * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
     * for re-validation cadence.
     * 
     */
    public Output<Optional<List<Object>>> triggers() {
        return Codegen.optional(this.triggers);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ValidationRun(java.lang.String name) {
        this(name, ValidationRunArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ValidationRun(java.lang.String name, ValidationRunArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ValidationRun(java.lang.String name, ValidationRunArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nvidia-aicr:index:ValidationRun", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ValidationRun(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("nvidia-aicr:index:ValidationRun", name, null, makeResourceOptions(options, id), false);
    }

    private static ValidationRunArgs makeArgs(ValidationRunArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ValidationRunArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumi-labs/pulumi-nvidia-aicr")
            .additionalSecretOutputs(List.of(
                "kubeconfig"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ValidationRun get(java.lang.String name, Output<java.lang.String> id, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ValidationRun(name, id, options);
    }
}
