// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumi.Labs.NvidiaAicr
{
    /// <summary>
    /// Runs an AICR recipe's empirical validation (cluster snapshot +
    /// deployment/conformance/performance checks) against a live cluster and
    /// records structured per-check results in Pulumi state.
    /// 
    /// The run happens at deploy time (never at preview). The validation harness
    /// deploys short-lived agent and validator Jobs plus per-run RBAC on the target
    /// cluster and cleans them up afterward; the validation namespace (default
    /// "aicr-validation") is created on first run and deliberately persists.
    /// 
    /// Privilege level: the snapshot-agent Job runs as a privileged container
    /// (bound to a read-only node-inspection ClusterRole), and validator Jobs run
    /// under a per-run cluster-admin ClusterRoleBinding — both removed after the
    /// run, including on cancellation. The kubeconfig identity needs RBAC to
    /// create/patch Namespaces, ClusterRoles, and ClusterRoleBindings.
    /// 
    /// Any input change replaces the resource, which re-runs validation (delete is
    /// a no-op). With `strict: true`, a failed run fails the update while persisting
    /// full results, and validation re-runs on every subsequent `pulumi up` until it
    /// passes — use `dependsOn` to gate downstream resources on it.
    /// </summary>
    [NvidiaAicrResourceType("nvidia-aicr:index:ValidationRun")]
    public partial class ValidationRun : global::Pulumi.CustomResource
    {
        /// <summary>
        /// When the run completed, RFC 3339.
        /// </summary>
        [Output("completedAt")]
        public Output<string> CompletedAt { get; private set; } = null!;

        /// <summary>
        /// Kubeconfig context to select. Defaults to the kubeconfig's current-context.
        /// </summary>
        [Output("context")]
        public Output<string?> Context { get; private set; } = null!;

        /// <summary>
        /// Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
        /// the object inline.
        /// </summary>
        [Output("criteria")]
        public Output<Outputs.RecipeCriteria> Criteria { get; private set; } = null!;

        /// <summary>
        /// The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
        /// </summary>
        [Output("ctrfReport")]
        public Output<string?> CtrfReport { get; private set; } = null!;

        /// <summary>
        /// Number of checks that failed.
        /// </summary>
        [Output("failed")]
        public Output<int> Failed { get; private set; } = null!;

        /// <summary>
        /// Names of image pull Secrets (in the validation namespace) for the
        /// validation pods.
        /// </summary>
        [Output("imagePullSecrets")]
        public Output<ImmutableArray<string>> ImagePullSecrets { get; private set; } = null!;

        /// <summary>
        /// Registry override for the snapshot-agent and validator images (air-gapped
        /// mirrors). Unset keeps the default registry (ghcr.io).
        /// </summary>
        [Output("imageRegistry")]
        public Output<string?> ImageRegistry { get; private set; } = null!;

        /// <summary>
        /// If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
        /// Default: false (state-size control; per-check results are always in
        /// `phaseResults`).
        /// </summary>
        [Output("includeCtrfReport")]
        public Output<bool?> IncludeCtrfReport { get; private set; } = null!;

        /// <summary>
        /// Kubeconfig contents for the target cluster. Mutually exclusive with
        /// `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
        /// var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
        /// duration of the run and removed afterward.
        /// </summary>
        [Output("kubeconfig")]
        public Output<string?> Kubeconfig { get; private set; } = null!;

        /// <summary>
        /// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        /// </summary>
        [Output("kubeconfigPath")]
        public Output<string?> KubeconfigPath { get; private set; } = null!;

        /// <summary>
        /// Namespace for the validation harness — use a dedicated one: it hosts the
        /// privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
        /// on first run and deliberately never deletes it. Must be a valid DNS-1123
        /// label and not a "kube-" system namespace. Default: "aicr-validation".
        /// </summary>
        [Output("namespace")]
        public Output<string?> Namespace { get; private set; } = null!;

        /// <summary>
        /// Node selector applied to the validation workload pods. Use when GPU nodes
        /// carry non-standard labels.
        /// </summary>
        [Output("nodeSelector")]
        public Output<ImmutableDictionary<string, string>?> NodeSelector { get; private set; } = null!;

        /// <summary>
        /// Number of checks with an inconclusive outcome (crash, OOM, timeout;
        /// includes CTRF "pending").
        /// </summary>
        [Output("other")]
        public Output<int> Other { get; private set; } = null!;

        /// <summary>
        /// Number of checks that passed.
        /// </summary>
        [Output("passed")]
        public Output<int> Passed { get; private set; } = null!;

        /// <summary>
        /// Per-check results across all phases run.
        /// </summary>
        [Output("phaseResults")]
        public Output<ImmutableArray<Outputs.CheckResult>> PhaseResults { get; private set; } = null!;

        /// <summary>
        /// Validation phases to run: any of "deployment", "conformance",
        /// "performance". Default: ["deployment", "conformance"] — "performance" is an
        /// explicit opt-in (long-running and hardware-bound).
        /// </summary>
        [Output("phases")]
        public Output<ImmutableArray<string>> Phases { get; private set; } = null!;

        /// <summary>
        /// The readiness pre-flight failure message; empty unless status is
        /// "readiness-failed".
        /// </summary>
        [Output("readinessMessage")]
        public Output<string> ReadinessMessage { get; private set; } = null!;

        /// <summary>
        /// Recipe-data version assertion (not a pin). When set, it must equal this
        /// provider build's embedded AICR recipe-data version or Create fails before
        /// any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
        /// provider upgrade between deploy and validate.
        /// </summary>
        [Output("recipeDataVersion")]
        public Output<string?> RecipeDataVersion { get; private set; } = null!;

        /// <summary>
        /// The resolved AICR recipe name that was validated.
        /// </summary>
        [Output("recipeName")]
        public Output<string> RecipeName { get; private set; } = null!;

        /// <summary>
        /// The AICR recipe data version that was validated.
        /// </summary>
        [Output("recipeVersion")]
        public Output<string> RecipeVersion { get; private set; } = null!;

        /// <summary>
        /// Whether the snapshot agent requires GPU nodes. Set false for
        /// hardware-free clusters (kind). Default: true.
        /// </summary>
        [Output("requireGpu")]
        public Output<bool?> RequireGpu { get; private set; } = null!;

        /// <summary>
        /// The run identifier labeling this run's cluster-side artifacts.
        /// </summary>
        [Output("runId")]
        public Output<string> RunId { get; private set; } = null!;

        /// <summary>
        /// Number of checks that were skipped.
        /// </summary>
        [Output("skipped")]
        public Output<int> Skipped { get; private set; } = null!;

        /// <summary>
        /// Rollup verdict: "passed", "failed", or "readiness-failed". Checks with
        /// status "other" never flip the rollup (they are counted and listed).
        /// Infrastructure errors have no status — they fail the update outright.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// If true, a failed (or readiness-failed) validation fails the update while
        /// still persisting the full results in state. The engine then re-runs
        /// validation on every subsequent `pulumi up` until it passes. Default: false —
        /// results are recorded and the update succeeds; read the `status` output.
        /// </summary>
        [Output("strict")]
        public Output<bool?> Strict { get; private set; } = null!;

        /// <summary>
        /// Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
        /// </summary>
        [Output("timeoutMinutes")]
        public Output<int?> TimeoutMinutes { get; private set; } = null!;

        /// <summary>
        /// Tolerations applied to the validation workload pods (e.g. NCCL benchmark
        /// pods). Required in practice on tainted GPU node groups; when unset, the
        /// validator's default tolerate-all is kept.
        /// </summary>
        [Output("tolerations")]
        public Output<ImmutableArray<Outputs.Toleration>> Tolerations { get; private set; } = null!;

        /// <summary>
        /// Arbitrary values; changing any of them replaces the resource and re-runs
        /// validation (every input change does). Wire `triggers: [stack.deployedComponents]`
        /// for re-validation cadence.
        /// </summary>
        [Output("triggers")]
        public Output<ImmutableArray<object>> Triggers { get; private set; } = null!;


        /// <summary>
        /// Create a ValidationRun resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ValidationRun(string name, ValidationRunArgs args, CustomResourceOptions? options = null)
            : base("nvidia-aicr:index:ValidationRun", name, args ?? new ValidationRunArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ValidationRun(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("nvidia-aicr:index:ValidationRun", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi-labs/pulumi-nvidia-aicr",
                AdditionalSecretOutputs =
                {
                    "kubeconfig",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ValidationRun resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ValidationRun Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ValidationRun(name, id, options);
        }
    }

    public sealed class ValidationRunArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Kubeconfig context to select. Defaults to the kubeconfig's current-context.
        /// </summary>
        [Input("context")]
        public Input<string>? Context { get; set; }

        /// <summary>
        /// Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
        /// the object inline.
        /// </summary>
        [Input("criteria", required: true)]
        public Input<Inputs.RecipeCriteriaArgs> Criteria { get; set; } = null!;

        [Input("imagePullSecrets")]
        private InputList<string>? _imagePullSecrets;

        /// <summary>
        /// Names of image pull Secrets (in the validation namespace) for the
        /// validation pods.
        /// </summary>
        public InputList<string> ImagePullSecrets
        {
            get => _imagePullSecrets ?? (_imagePullSecrets = new InputList<string>());
            set => _imagePullSecrets = value;
        }

        /// <summary>
        /// Registry override for the snapshot-agent and validator images (air-gapped
        /// mirrors). Unset keeps the default registry (ghcr.io).
        /// </summary>
        [Input("imageRegistry")]
        public Input<string>? ImageRegistry { get; set; }

        /// <summary>
        /// If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
        /// Default: false (state-size control; per-check results are always in
        /// `phaseResults`).
        /// </summary>
        [Input("includeCtrfReport")]
        public Input<bool>? IncludeCtrfReport { get; set; }

        [Input("kubeconfig")]
        private Input<string>? _kubeconfig;

        /// <summary>
        /// Kubeconfig contents for the target cluster. Mutually exclusive with
        /// `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
        /// var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
        /// duration of the run and removed afterward.
        /// </summary>
        public Input<string>? Kubeconfig
        {
            get => _kubeconfig;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _kubeconfig = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
        /// </summary>
        [Input("kubeconfigPath")]
        public Input<string>? KubeconfigPath { get; set; }

        /// <summary>
        /// Namespace for the validation harness — use a dedicated one: it hosts the
        /// privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
        /// on first run and deliberately never deletes it. Must be a valid DNS-1123
        /// label and not a "kube-" system namespace. Default: "aicr-validation".
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("nodeSelector")]
        private InputMap<string>? _nodeSelector;

        /// <summary>
        /// Node selector applied to the validation workload pods. Use when GPU nodes
        /// carry non-standard labels.
        /// </summary>
        public InputMap<string> NodeSelector
        {
            get => _nodeSelector ?? (_nodeSelector = new InputMap<string>());
            set => _nodeSelector = value;
        }

        [Input("phases")]
        private InputList<string>? _phases;

        /// <summary>
        /// Validation phases to run: any of "deployment", "conformance",
        /// "performance". Default: ["deployment", "conformance"] — "performance" is an
        /// explicit opt-in (long-running and hardware-bound).
        /// </summary>
        public InputList<string> Phases
        {
            get => _phases ?? (_phases = new InputList<string>());
            set => _phases = value;
        }

        /// <summary>
        /// Recipe-data version assertion (not a pin). When set, it must equal this
        /// provider build's embedded AICR recipe-data version or Create fails before
        /// any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
        /// provider upgrade between deploy and validate.
        /// </summary>
        [Input("recipeDataVersion")]
        public Input<string>? RecipeDataVersion { get; set; }

        /// <summary>
        /// Whether the snapshot agent requires GPU nodes. Set false for
        /// hardware-free clusters (kind). Default: true.
        /// </summary>
        [Input("requireGpu")]
        public Input<bool>? RequireGpu { get; set; }

        /// <summary>
        /// If true, a failed (or readiness-failed) validation fails the update while
        /// still persisting the full results in state. The engine then re-runs
        /// validation on every subsequent `pulumi up` until it passes. Default: false —
        /// results are recorded and the update succeeds; read the `status` output.
        /// </summary>
        [Input("strict")]
        public Input<bool>? Strict { get; set; }

        /// <summary>
        /// Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
        /// </summary>
        [Input("timeoutMinutes")]
        public Input<int>? TimeoutMinutes { get; set; }

        [Input("tolerations")]
        private InputList<Inputs.TolerationArgs>? _tolerations;

        /// <summary>
        /// Tolerations applied to the validation workload pods (e.g. NCCL benchmark
        /// pods). Required in practice on tainted GPU node groups; when unset, the
        /// validator's default tolerate-all is kept.
        /// </summary>
        public InputList<Inputs.TolerationArgs> Tolerations
        {
            get => _tolerations ?? (_tolerations = new InputList<Inputs.TolerationArgs>());
            set => _tolerations = value;
        }

        [Input("triggers")]
        private InputList<object>? _triggers;

        /// <summary>
        /// Arbitrary values; changing any of them replaces the resource and re-runs
        /// validation (every input change does). Wire `triggers: [stack.deployedComponents]`
        /// for re-validation cadence.
        /// </summary>
        public InputList<object> Triggers
        {
            get => _triggers ?? (_triggers = new InputList<object>());
            set => _triggers = value;
        }

        public ValidationRunArgs()
        {
            IncludeCtrfReport = false;
            Namespace = "aicr-validation";
            RequireGpu = true;
            Strict = false;
            TimeoutMinutes = 30;
        }
        public static new ValidationRunArgs Empty => new ValidationRunArgs();
    }
}
