// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ComponentOverrideArgs {
    namespace?: pulumi.Input<string>;
    values?: pulumi.Input<{[key: string]: any}>;
    version?: pulumi.Input<string>;
}
