// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

/**
 * Per-component override settings. Each field is optional; only the fields
 * you set are applied on top of the recipe defaults.
 */
export interface ComponentOverrideArgs {
    /**
     * Override the target Kubernetes namespace.
     */
    namespace?: pulumi.Input<string | undefined>;
    /**
     * Additional or override Helm values, deep-merged on top of the
     * recipe-resolved values.
     *
     * Merge semantics: nested maps merge recursively; scalars and arrays replace
     * the recipe's value; setting a key to null removes it from the
     * recipe-resolved values, restoring the chart's own default for that key.
     * Note the null asymmetry: a null *in the recipe data* is passed through to
     * Helm (explicitly clearing the chart default), while a null *here* removes
     * the recipe's setting. There is currently no way to pass a literal null
     * through to Helm from this input — and some language SDKs drop null map
     * entries during serialization before they reach the provider at all.
     */
    values?: pulumi.Input<{[key: string]: any} | undefined>;
    /**
     * Override the Helm chart version. If unset, the recipe-pinned version is used.
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
 * intent / os / platform / nodes inputs, plus the skipComponents the stack
 * deployed without. Wire a ClusterStack's `criteria` output here so deployment
 * and validation resolve the identical recipe and agree on which of its
 * components are in scope.
 */
export interface RecipeCriteriaArgs {
    /**
     * GPU accelerator type. Supported values: "h100", "gb200", "b200".
     */
    accelerator: pulumi.Input<string>;
    /**
     * Workload intent. Supported values: "training", "inference".
     */
    intent: pulumi.Input<string>;
    /**
     * Worker-node count hint used to size the recipe.
     */
    nodes?: pulumi.Input<number | undefined>;
    /**
     * Operating system flavor of the worker nodes. Leave unset for OS-agnostic
     * resolution. Supported values: "ubuntu", "cos", "ol".
     */
    os?: pulumi.Input<string | undefined>;
    /**
     * ML platform/framework. Supported values: "kubeflow" (training),
     * "dynamo" (inference), "nim" (inference, EKS+H100 only).
     */
    platform?: pulumi.Input<string | undefined>;
    /**
     * Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
     */
    service: pulumi.Input<string>;
    /**
     * Recipe components the stack intentionally did not deploy (ClusterStack's
     * `skipComponents`). ValidationRun treats them as out of scope rather than
     * missing: checks that presuppose one of them (e.g. the gpu-operator health,
     * DCGM metrics, and GPU-HPA checks when "gpu-operator" is skipped) are reported
     * "skipped" with a reason instead of failing, and the SDK's component-aware
     * checks see the components as disabled. A ClusterStack's `criteria` output
     * carries its own skipComponents, so wiring it keeps validation aligned with
     * the deployed subset automatically. Skipping does not verify a replacement
     * you run yourself — those checks are simply not made.
     */
    skipComponents?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

/**
 * A Kubernetes pod toleration applied to validation workload pods.
 */
export interface TolerationArgs {
    /**
     * The taint effect to match: "NoSchedule", "PreferNoSchedule", or
     * "NoExecute". Empty matches all effects.
     */
    effect?: pulumi.Input<string | undefined>;
    /**
     * The taint key the toleration applies to. Empty means match all keys
     * (with operator "Exists").
     */
    key?: pulumi.Input<string | undefined>;
    /**
     * Key-value relationship: "Exists" or "Equal". Default: "Equal".
     */
    operator?: pulumi.Input<string | undefined>;
    /**
     * How long the pod tolerates a "NoExecute" taint, in seconds.
     */
    tolerationSeconds?: pulumi.Input<number | undefined>;
    /**
     * The taint value to match (with operator "Equal").
     */
    value?: pulumi.Input<string | undefined>;
}
