// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

/**
 * The outcome of one validator check.
 */
export interface CheckResult {
    /**
     * The check's failure or diagnostic message, if any.
     */
    message: string;
    /**
     * The check's name (e.g. "gpu-operator-health").
     */
    name: string;
    /**
     * The validation phase the check ran in.
     */
    phase: string;
    /**
     * The check's status: "passed", "failed", "skipped", "pending", or "other".
     */
    status: string;
}

/**
 * Recipe-selection criteria, mirroring ClusterStack's accelerator / service /
 * intent / os / platform / nodes inputs, plus the skipComponents the stack
 * deployed without. Wire a ClusterStack's `criteria` output here so deployment
 * and validation resolve the identical recipe and agree on which of its
 * components are in scope.
 */
export interface RecipeCriteria {
    /**
     * GPU accelerator type. Supported values: "h100", "gb200", "b200".
     */
    accelerator: string;
    /**
     * Workload intent. Supported values: "training", "inference".
     */
    intent: string;
    /**
     * Worker-node count hint used to size the recipe.
     */
    nodes?: number;
    /**
     * Operating system flavor of the worker nodes. Leave unset for OS-agnostic
     * resolution. Supported values: "ubuntu", "cos", "ol".
     */
    os?: string;
    /**
     * ML platform/framework. Supported values: "kubeflow" (training),
     * "dynamo" (inference), "nim" (inference, EKS+H100 only).
     */
    platform?: string;
    /**
     * Kubernetes service. Supported values: "aks", "eks", "gke", "kind", "oke".
     */
    service: string;
    /**
     * Recipe components the stack intentionally did not deploy (ClusterStack's
     * `skipComponents`). ValidationRun treats them as out of scope rather than
     * missing: checks that presuppose one of them (e.g. the gpu-operator health,
     * DCGM metrics, and GPU-HPA checks when "gpu-operator" is skipped) are reported
     * "skipped" with a reason instead of failing, and the SDK's component-aware
     * checks see the components as disabled. A ClusterStack's `criteria` output
     * carries its own skipComponents, so wiring it keeps validation aligned with
     * the deployed subset automatically. Skipping does not verify a replacement
     * you run yourself — those checks are simply not made.
     */
    skipComponents?: string[];
}

/**
 * A Kubernetes pod toleration applied to validation workload pods.
 */
export interface Toleration {
    /**
     * The taint effect to match: "NoSchedule", "PreferNoSchedule", or
     * "NoExecute". Empty matches all effects.
     */
    effect?: string;
    /**
     * The taint key the toleration applies to. Empty means match all keys
     * (with operator "Exists").
     */
    key?: string;
    /**
     * Key-value relationship: "Exists" or "Equal". Default: "Equal".
     */
    operator?: string;
    /**
     * How long the pod tolerates a "NoExecute" taint, in seconds.
     */
    tolerationSeconds?: number;
    /**
     * The taint value to match (with operator "Equal").
     */
    value?: string;
}

