// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NvidiaAicr.Inputs
{

    /// <summary>
    /// Per-component override settings. Each field is optional; only the fields
    /// you set are applied on top of the recipe defaults.
    /// </summary>
    public sealed class ComponentOverrideArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Override the target Kubernetes namespace.
        /// </summary>
        [Input("namespace")]
        public Input<string>? Namespace { get; set; }

        [Input("values")]
        private InputMap<object>? _values;

        /// <summary>
        /// Additional or override Helm values, deep-merged with the recipe defaults.
        /// </summary>
        public InputMap<object> Values
        {
            get => _values ?? (_values = new InputMap<object>());
            set => _values = value;
        }

        /// <summary>
        /// Override the Helm chart version. If unset, the recipe-pinned version is used.
        /// </summary>
        [Input("version")]
        public Input<string>? Version { get; set; }

        public ComponentOverrideArgs()
        {
        }
        public static new ComponentOverrideArgs Empty => new ComponentOverrideArgs();
    }
}
