// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ClusterStack extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nvidia-aicr:index:ClusterStack';

    /**
     * Returns true if the given object is an instance of ClusterStack.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterStack {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterStack.__pulumiType;
    }

    declare public /*out*/ readonly componentCount: pulumi.Output<number>;
    declare public /*out*/ readonly deployedComponents: pulumi.Output<string[]>;
    declare public /*out*/ readonly recipeName: pulumi.Output<string>;
    declare public /*out*/ readonly recipeVersion: pulumi.Output<string>;

    /**
     * Create a ClusterStack resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterStackArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.accelerator === undefined && !opts.urn) {
                throw new Error("Missing required property 'accelerator'");
            }
            if (args?.intent === undefined && !opts.urn) {
                throw new Error("Missing required property 'intent'");
            }
            if (args?.service === undefined && !opts.urn) {
                throw new Error("Missing required property 'service'");
            }
            resourceInputs["accelerator"] = args?.accelerator;
            resourceInputs["componentOverrides"] = args?.componentOverrides;
            resourceInputs["context"] = args?.context;
            resourceInputs["intent"] = args?.intent;
            resourceInputs["kubeconfig"] = args?.kubeconfig;
            resourceInputs["kubeconfigPath"] = args?.kubeconfigPath;
            resourceInputs["os"] = args?.os;
            resourceInputs["platform"] = args?.platform;
            resourceInputs["service"] = args?.service;
            resourceInputs["skipAwait"] = args?.skipAwait;
            resourceInputs["skipComponents"] = args?.skipComponents;
            resourceInputs["componentCount"] = undefined /*out*/;
            resourceInputs["deployedComponents"] = undefined /*out*/;
            resourceInputs["recipeName"] = undefined /*out*/;
            resourceInputs["recipeVersion"] = undefined /*out*/;
        } else {
            resourceInputs["componentCount"] = undefined /*out*/;
            resourceInputs["deployedComponents"] = undefined /*out*/;
            resourceInputs["recipeName"] = undefined /*out*/;
            resourceInputs["recipeVersion"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterStack.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ClusterStack resource.
 */
export interface ClusterStackArgs {
    accelerator: string;
    componentOverrides?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ComponentOverrideArgs>}>;
    context?: string;
    intent: string;
    kubeconfig?: pulumi.Input<string>;
    kubeconfigPath?: string;
    os?: string;
    platform?: string;
    service: string;
    skipAwait?: boolean;
    skipComponents?: pulumi.Input<string[]>;
}
