// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class ClusterStack extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'nvidia-aicr:index:ClusterStack';

    /**
     * Returns true if the given object is an instance of ClusterStack.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ClusterStack {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ClusterStack.__pulumiType;
    }

    /**
     * Number of components deployed.
     */
    declare public /*out*/ readonly componentCount: pulumi.Output<number>;
    /**
     * The canonicalized recipe criteria this stack resolved with, including its
     * `skipComponents`. Wire it into a ValidationRun's `criteria` input so deployment and
     * validation share a single source of truth — the same recipe, and the same
     * components in scope.
     */
    declare public /*out*/ readonly criteria: pulumi.Output<outputs.RecipeCriteria>;
    /**
     * Names of all components deployed as part of this stack, in topological order.
     */
    declare public /*out*/ readonly deployedComponents: pulumi.Output<string[]>;
    /**
     * The resolved AICR recipe name (e.g., "h100-eks-ubuntu-training-kubeflow").
     */
    declare public /*out*/ readonly recipeName: pulumi.Output<string>;
    /**
     * The AICR recipe data version embedded in this provider build.
     */
    declare public /*out*/ readonly recipeVersion: pulumi.Output<string>;

    /**
     * Create a ClusterStack resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ClusterStackArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.accelerator === undefined && !opts.urn) {
                throw new Error("Missing required property 'accelerator'");
            }
            if (args?.intent === undefined && !opts.urn) {
                throw new Error("Missing required property 'intent'");
            }
            if (args?.service === undefined && !opts.urn) {
                throw new Error("Missing required property 'service'");
            }
            resourceInputs["accelerator"] = args?.accelerator;
            resourceInputs["componentOverrides"] = args?.componentOverrides;
            resourceInputs["context"] = args?.context;
            resourceInputs["intent"] = args?.intent;
            resourceInputs["kubeconfig"] = args?.kubeconfig;
            resourceInputs["kubeconfigPath"] = args?.kubeconfigPath;
            resourceInputs["nodes"] = args?.nodes;
            resourceInputs["os"] = args?.os;
            resourceInputs["platform"] = args?.platform;
            resourceInputs["service"] = args?.service;
            resourceInputs["skipAwait"] = (args?.skipAwait) ?? false;
            resourceInputs["skipComponents"] = args?.skipComponents;
            resourceInputs["componentCount"] = undefined /*out*/;
            resourceInputs["criteria"] = undefined /*out*/;
            resourceInputs["deployedComponents"] = undefined /*out*/;
            resourceInputs["recipeName"] = undefined /*out*/;
            resourceInputs["recipeVersion"] = undefined /*out*/;
        } else {
            resourceInputs["componentCount"] = undefined /*out*/;
            resourceInputs["criteria"] = undefined /*out*/;
            resourceInputs["deployedComponents"] = undefined /*out*/;
            resourceInputs["recipeName"] = undefined /*out*/;
            resourceInputs["recipeVersion"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ClusterStack.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a ClusterStack resource.
 */
export interface ClusterStackArgs {
    /**
     * GPU accelerator type. Selects the AICR recipe family.
     *
     * Supported values: "h100", "gb200", "b200", "rtx-pro-6000" (eks/lke only —
     * the services with rtx-pro-6000-tuned recipes in the pinned AICR data).
     */
    accelerator: string;
    /**
     * Per-component overrides. Map of AICR component name to override settings
     * (version, namespace, Helm values). Values are deep-merged with the recipe
     * defaults; only the keys you specify are changed.
     */
    componentOverrides?: pulumi.Input<{[key: string]: pulumi.Input<inputs.ComponentOverrideArgs>} | undefined>;
    /**
     * Kubeconfig context to select. Defaults to the current-context in the kubeconfig.
     */
    context?: string;
    /**
     * Workload intent. Selects between training-oriented and inference-oriented
     * component sets.
     *
     * Supported values: "training", "inference".
     */
    intent: string;
    /**
     * Kubeconfig contents (or path to a kubeconfig file) for the target cluster.
     * Accepts computed outputs from cluster resources (e.g., an EKS cluster's
     * KubeconfigJson). Mutually exclusive with `kubeconfigPath`.
     *
     * If neither `kubeconfig` nor `kubeconfigPath` is set, the ambient kubeconfig
     * (KUBECONFIG env var or ~/.kube/config) is used.
     */
    kubeconfig?: pulumi.Input<string | undefined>;
    /**
     * Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     * Prefer `kubeconfig` when chaining off a cluster resource's output.
     */
    kubeconfigPath?: string;
    /**
     * Worker-node count hint used to size the recipe (number of nodes, not GPUs).
     * Leave unset to let AICR pick the default-sized recipe.
     */
    nodes?: number;
    /**
     * Operating system flavor of the worker nodes.
     *
     * Supported values: "ubuntu", "cos" (Container-Optimized OS, GKE only), "ol"
     * (Oracle Linux, OKE) — the values with backing recipes in this provider's
     * pinned AICR data. Additional OS values (rhel, amazonlinux, talos) arrive
     * through AICR SDK upgrades.
     *
     * Leave unset for OS-agnostic resolution: OS-pinned recipe overlays (kernel
     * tuning, driver constraints) are skipped and the OS-agnostic recipe is used.
     * Set it when the cluster's OS is known. Some combinations require an OS
     * (e.g. gke requires "cos"; eks platform recipes require "ubuntu") and fail
     * with a message listing the valid values; kind recipes require it unset.
     */
    os?: string;
    /**
     * ML platform/framework to layer on top of the base recipe.
     *
     * Supported values: "kubeflow" (training), "dynamo" (inference), "nim"
     * (inference, eks with h100 or rtx-pro-6000 only). kubeflow and dynamo have no
     * recipes on lke/bcm in the pinned AICR data.
     *
     * Leave unset for the base recipe without a platform-specific runtime. Note
     * that intent="inference" always includes an inference gateway (part of the
     * base inference stack); choosing a platform layers a runtime ("dynamo",
     * "nim") on top. intent="training" leaves training-runtime components out
     * entirely when platform is unset.
     */
    platform?: string;
    /**
     * Kubernetes service. Selects cloud-specific operators and storage drivers.
     *
     * Supported values: "aks", "bcm", "eks", "gke", "kind", "lke", "oke". bcm and
     * lke are the cloud-neutral leaves (no hyperscaler CSI/EFA components) and
     * double as stand-ins for providers without an AICR criteria value yet (e.g.
     * CoreWeave CKS deploys the lke leaf). Use "kind" for local
     * hardware-free development of the deployment pipeline.
     */
    service: string;
    /**
     * If true, do not wait for each Helm release to become ready before continuing.
     * Faster previews/updates at the cost of losing readiness signal. Default: false.
     */
    skipAwait?: boolean;
    /**
     * Component names to exclude from the deployment. Useful for swapping in your
     * own installation of a component (e.g., bring-your-own cert-manager) or for
     * deploying onto bare-metal where cloud-specific operators are not relevant.
     */
    skipComponents?: pulumi.Input<string[] | undefined>;
}
