// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Runs an AICR recipe's empirical validation (cluster snapshot +
 * deployment/conformance/performance checks) against a live cluster and
 * records structured per-check results in Pulumi state.
 *
 * The run happens at deploy time (never at preview). The validation harness
 * deploys short-lived agent and validator Jobs plus per-run RBAC on the target
 * cluster and cleans them up afterward; the validation namespace (default
 * "aicr-validation") is created on first run and deliberately persists.
 *
 * Privilege level: the snapshot-agent Job runs as a privileged container
 * (bound to a read-only node-inspection ClusterRole), and validator Jobs run
 * under a per-run cluster-admin ClusterRoleBinding — both removed after the
 * run, including on cancellation. The kubeconfig identity needs RBAC to
 * create/patch Namespaces, ClusterRoles, and ClusterRoleBindings.
 *
 * Any input change replaces the resource, which re-runs validation (delete is
 * a no-op). With `strict: true`, a failed run fails the update while persisting
 * full results, and validation re-runs on every subsequent `pulumi up` until it
 * passes — use `dependsOn` to gate downstream resources on it.
 */
export class ValidationRun extends pulumi.CustomResource {
    /**
     * Get an existing ValidationRun resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ValidationRun {
        return new ValidationRun(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'nvidia-aicr:index:ValidationRun';

    /**
     * Returns true if the given object is an instance of ValidationRun.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ValidationRun {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ValidationRun.__pulumiType;
    }

    /**
     * When the run completed, RFC 3339.
     */
    declare public /*out*/ readonly completedAt: pulumi.Output<string>;
    /**
     * Kubeconfig context to select. Defaults to the kubeconfig's current-context.
     */
    declare public readonly context: pulumi.Output<string | undefined>;
    /**
     * Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
     * the object inline.
     */
    declare public readonly criteria: pulumi.Output<outputs.RecipeCriteria>;
    /**
     * The merged CTRF JSON report. Set only when `includeCtrfReport` is true.
     */
    declare public /*out*/ readonly ctrfReport: pulumi.Output<string | undefined>;
    /**
     * Number of checks that failed.
     */
    declare public /*out*/ readonly failed: pulumi.Output<number>;
    /**
     * Names of image pull Secrets (in the validation namespace) for the
     * validation pods.
     */
    declare public readonly imagePullSecrets: pulumi.Output<string[] | undefined>;
    /**
     * Registry override for the snapshot-agent and validator images (air-gapped
     * mirrors). Unset keeps the default registry (ghcr.io).
     */
    declare public readonly imageRegistry: pulumi.Output<string | undefined>;
    /**
     * If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
     * Default: false (state-size control; per-check results are always in
     * `phaseResults`).
     */
    declare public readonly includeCtrfReport: pulumi.Output<boolean | undefined>;
    /**
     * Kubeconfig contents for the target cluster. Mutually exclusive with
     * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
     * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
     * duration of the run and removed afterward.
     */
    declare public readonly kubeconfig: pulumi.Output<string | undefined>;
    /**
     * Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     */
    declare public readonly kubeconfigPath: pulumi.Output<string | undefined>;
    /**
     * Namespace for the validation harness — use a dedicated one: it hosts the
     * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
     * on first run and deliberately never deletes it. Must be a valid DNS-1123
     * label and not a "kube-" system namespace. Default: "aicr-validation".
     */
    declare public readonly namespace: pulumi.Output<string | undefined>;
    /**
     * Node selector applied to the validation workload pods. Use when GPU nodes
     * carry non-standard labels.
     */
    declare public readonly nodeSelector: pulumi.Output<{[key: string]: string} | undefined>;
    /**
     * Number of checks with an inconclusive outcome (crash, OOM, timeout;
     * includes CTRF "pending").
     */
    declare public /*out*/ readonly other: pulumi.Output<number>;
    /**
     * Number of checks that passed.
     */
    declare public /*out*/ readonly passed: pulumi.Output<number>;
    /**
     * Per-check results across all phases run.
     */
    declare public /*out*/ readonly phaseResults: pulumi.Output<outputs.CheckResult[]>;
    /**
     * Validation phases to run: any of "deployment", "conformance",
     * "performance". Default: ["deployment", "conformance"] — "performance" is an
     * explicit opt-in (long-running and hardware-bound).
     */
    declare public readonly phases: pulumi.Output<string[] | undefined>;
    /**
     * The readiness pre-flight failure message; empty unless status is
     * "readiness-failed".
     */
    declare public /*out*/ readonly readinessMessage: pulumi.Output<string>;
    /**
     * Recipe-data version assertion (not a pin). When set, it must equal this
     * provider build's embedded AICR recipe-data version or Create fails before
     * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
     * provider upgrade between deploy and validate.
     */
    declare public readonly recipeDataVersion: pulumi.Output<string | undefined>;
    /**
     * The resolved AICR recipe name that was validated.
     */
    declare public /*out*/ readonly recipeName: pulumi.Output<string>;
    /**
     * The AICR recipe data version that was validated.
     */
    declare public /*out*/ readonly recipeVersion: pulumi.Output<string>;
    /**
     * Whether the snapshot agent requires GPU nodes. Set false for
     * hardware-free clusters (kind). Default: true.
     */
    declare public readonly requireGpu: pulumi.Output<boolean | undefined>;
    /**
     * The run identifier labeling this run's cluster-side artifacts.
     */
    declare public /*out*/ readonly runId: pulumi.Output<string>;
    /**
     * Number of checks that were skipped.
     */
    declare public /*out*/ readonly skipped: pulumi.Output<number>;
    /**
     * Rollup verdict: "passed", "failed", or "readiness-failed". Checks with
     * status "other" never flip the rollup (they are counted and listed).
     * Infrastructure errors have no status — they fail the update outright.
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;
    /**
     * If true, a failed (or readiness-failed) validation fails the update while
     * still persisting the full results in state. The engine then re-runs
     * validation on every subsequent `pulumi up` until it passes. Default: false —
     * results are recorded and the update succeeds; read the `status` output.
     */
    declare public readonly strict: pulumi.Output<boolean | undefined>;
    /**
     * Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
     */
    declare public readonly timeoutMinutes: pulumi.Output<number | undefined>;
    /**
     * Tolerations applied to the validation workload pods (e.g. NCCL benchmark
     * pods). Required in practice on tainted GPU node groups; when unset, the
     * validator's default tolerate-all is kept.
     */
    declare public readonly tolerations: pulumi.Output<outputs.Toleration[] | undefined>;
    /**
     * Arbitrary values; changing any of them replaces the resource and re-runs
     * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
     * for re-validation cadence.
     */
    declare public readonly triggers: pulumi.Output<any[] | undefined>;

    /**
     * Create a ValidationRun resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ValidationRunArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.criteria === undefined && !opts.urn) {
                throw new Error("Missing required property 'criteria'");
            }
            resourceInputs["context"] = args?.context;
            resourceInputs["criteria"] = args?.criteria;
            resourceInputs["imagePullSecrets"] = args?.imagePullSecrets;
            resourceInputs["imageRegistry"] = args?.imageRegistry;
            resourceInputs["includeCtrfReport"] = (args?.includeCtrfReport) ?? false;
            resourceInputs["kubeconfig"] = args?.kubeconfig ? pulumi.secret(args.kubeconfig) : undefined;
            resourceInputs["kubeconfigPath"] = args?.kubeconfigPath;
            resourceInputs["namespace"] = (args?.namespace) ?? "aicr-validation";
            resourceInputs["nodeSelector"] = args?.nodeSelector;
            resourceInputs["phases"] = args?.phases;
            resourceInputs["recipeDataVersion"] = args?.recipeDataVersion;
            resourceInputs["requireGpu"] = (args?.requireGpu) ?? true;
            resourceInputs["strict"] = (args?.strict) ?? false;
            resourceInputs["timeoutMinutes"] = (args?.timeoutMinutes) ?? 30;
            resourceInputs["tolerations"] = args?.tolerations;
            resourceInputs["triggers"] = args?.triggers;
            resourceInputs["completedAt"] = undefined /*out*/;
            resourceInputs["ctrfReport"] = undefined /*out*/;
            resourceInputs["failed"] = undefined /*out*/;
            resourceInputs["other"] = undefined /*out*/;
            resourceInputs["passed"] = undefined /*out*/;
            resourceInputs["phaseResults"] = undefined /*out*/;
            resourceInputs["readinessMessage"] = undefined /*out*/;
            resourceInputs["recipeName"] = undefined /*out*/;
            resourceInputs["recipeVersion"] = undefined /*out*/;
            resourceInputs["runId"] = undefined /*out*/;
            resourceInputs["skipped"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        } else {
            resourceInputs["completedAt"] = undefined /*out*/;
            resourceInputs["context"] = undefined /*out*/;
            resourceInputs["criteria"] = undefined /*out*/;
            resourceInputs["ctrfReport"] = undefined /*out*/;
            resourceInputs["failed"] = undefined /*out*/;
            resourceInputs["imagePullSecrets"] = undefined /*out*/;
            resourceInputs["imageRegistry"] = undefined /*out*/;
            resourceInputs["includeCtrfReport"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
            resourceInputs["kubeconfigPath"] = undefined /*out*/;
            resourceInputs["namespace"] = undefined /*out*/;
            resourceInputs["nodeSelector"] = undefined /*out*/;
            resourceInputs["other"] = undefined /*out*/;
            resourceInputs["passed"] = undefined /*out*/;
            resourceInputs["phaseResults"] = undefined /*out*/;
            resourceInputs["phases"] = undefined /*out*/;
            resourceInputs["readinessMessage"] = undefined /*out*/;
            resourceInputs["recipeDataVersion"] = undefined /*out*/;
            resourceInputs["recipeName"] = undefined /*out*/;
            resourceInputs["recipeVersion"] = undefined /*out*/;
            resourceInputs["requireGpu"] = undefined /*out*/;
            resourceInputs["runId"] = undefined /*out*/;
            resourceInputs["skipped"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["strict"] = undefined /*out*/;
            resourceInputs["timeoutMinutes"] = undefined /*out*/;
            resourceInputs["tolerations"] = undefined /*out*/;
            resourceInputs["triggers"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["kubeconfig"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(ValidationRun.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ValidationRun resource.
 */
export interface ValidationRunArgs {
    /**
     * Kubeconfig context to select. Defaults to the kubeconfig's current-context.
     */
    context?: pulumi.Input<string | undefined>;
    /**
     * Recipe criteria. Wire a ClusterStack's `criteria` output here, or build
     * the object inline.
     */
    criteria: pulumi.Input<inputs.RecipeCriteriaArgs>;
    /**
     * Names of image pull Secrets (in the validation namespace) for the
     * validation pods.
     */
    imagePullSecrets?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Registry override for the snapshot-agent and validator images (air-gapped
     * mirrors). Unset keeps the default registry (ghcr.io).
     */
    imageRegistry?: pulumi.Input<string | undefined>;
    /**
     * If true, the merged CTRF JSON report is stored in the `ctrfReport` output.
     * Default: false (state-size control; per-check results are always in
     * `phaseResults`).
     */
    includeCtrfReport?: pulumi.Input<boolean | undefined>;
    /**
     * Kubeconfig contents for the target cluster. Mutually exclusive with
     * `kubeconfigPath`. If neither is set, the ambient kubeconfig (KUBECONFIG env
     * var or ~/.kube/config) is used. Written to a mode-0600 temp file for the
     * duration of the run and removed afterward.
     */
    kubeconfig?: pulumi.Input<string | undefined>;
    /**
     * Path to a kubeconfig file on disk. Mutually exclusive with `kubeconfig`.
     */
    kubeconfigPath?: pulumi.Input<string | undefined>;
    /**
     * Namespace for the validation harness — use a dedicated one: it hosts the
     * privileged agent and cluster-admin-bound validator Jobs. The SDK creates it
     * on first run and deliberately never deletes it. Must be a valid DNS-1123
     * label and not a "kube-" system namespace. Default: "aicr-validation".
     */
    namespace?: pulumi.Input<string | undefined>;
    /**
     * Node selector applied to the validation workload pods. Use when GPU nodes
     * carry non-standard labels.
     */
    nodeSelector?: pulumi.Input<{[key: string]: pulumi.Input<string>} | undefined>;
    /**
     * Validation phases to run: any of "deployment", "conformance",
     * "performance". Default: ["deployment", "conformance"] — "performance" is an
     * explicit opt-in (long-running and hardware-bound).
     */
    phases?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Recipe-data version assertion (not a pin). When set, it must equal this
     * provider build's embedded AICR recipe-data version or Create fails before
     * any cluster work — wire `recipeDataVersion: stack.recipeVersion` to catch a
     * provider upgrade between deploy and validate.
     */
    recipeDataVersion?: pulumi.Input<string | undefined>;
    /**
     * Whether the snapshot agent requires GPU nodes. Set false for
     * hardware-free clusters (kind). Default: true.
     */
    requireGpu?: pulumi.Input<boolean | undefined>;
    /**
     * If true, a failed (or readiness-failed) validation fails the update while
     * still persisting the full results in state. The engine then re-runs
     * validation on every subsequent `pulumi up` until it passes. Default: false —
     * results are recorded and the update succeeds; read the `status` output.
     */
    strict?: pulumi.Input<boolean | undefined>;
    /**
     * Overall run timeout in minutes. Default: 30. Maximum: 1440 (24 hours).
     */
    timeoutMinutes?: pulumi.Input<number | undefined>;
    /**
     * Tolerations applied to the validation workload pods (e.g. NCCL benchmark
     * pods). Required in practice on tainted GPU node groups; when unset, the
     * validator's default tolerate-all is kept.
     */
    tolerations?: pulumi.Input<pulumi.Input<inputs.TolerationArgs>[] | undefined>;
    /**
     * Arbitrary values; changing any of them replaces the resource and re-runs
     * validation (every input change does). Wire `triggers: [stack.deployedComponents]`
     * for re-validation cadence.
     */
    triggers?: pulumi.Input<any[] | undefined>;
}
